### ISSUE TITLE
Version numbers in README.md don't make any sense

### ISSUE THREAD

**Issue by oittaa** [linuxserver/docker-wireguard#103]
06.10.20 > 04.10.20

but

27.09.20 < 04.10.20 ???

**Comment by Roxedus** [comment]
DD.MM.YY makes tons of sense.

**Comment by oittaa** [comment]
Oh, you're using the worst date format out there. Maybe you should be using YYYY-MM-DD or some other non-retarded time format.

**Comment by aptalca** [comment]
thanks for the lovely feedback

**Comment by oittaa** [comment]
No worries, there's an RFC that might help you. https://tools.ietf.org/html/rfc3339
