### ISSUE TITLE
SERVERPORT does not update wg0.conf:ListenPort = 51820

### ISSUE THREAD

**Issue by sh3llc0de** [linuxserver/docker-wireguard#104]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

When specifying SERVERPORT I would expect ListenPort to be updated appropriately in the wg0.conf
[Interface]
Address = 10.13.13.1
ListenPort = 51820

I tried updating the templates/server.conf but after redeploying the container it overwrites my ListenPort in wg0.conf
------------------------------

## Expected Behavior
I would expect ListenPort to represent the passed in SERVERPORT

## Current Behavior
resets the ListenPort to the default

## Steps to Reproduce

1. -p 5555:5555/udp -v /media/data/wireguard:/config -v /lib/modules:/lib/modules --cap-add=NET_ADMIN --cap-add=SYS_MODULE -e SERVERPORT=5555 -e SERVERURL=some.ip -e PEERS=phone,laptop -e PEERDNS=auto -e INTERNAL_SUBNET=10.13.13.0 -e ALLOWEDIPS=10.13.13.1/32,10.0.1.0/24,10.0.2.0/24

## Environment
**OS:**
➤  cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
**CPU architecture:** x86_64/arm32/arm64
uname -a
Linux matrix 5.8.0-44-generic #50-Ubuntu SMP Tue Feb 9 06:29:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
**How docker service was installed:**
apt-get

**Comment by sh3llc0de** [comment]
ugg... I just re-deployed and the issue didn't persist.. so feel free to ignore.. And I just realized I can change my port mapping.

**Comment by aptalca** [comment]
Serverport var is for the external port (wan) so the clients connect to the right port on the wan/host

**Comment by sh3llc0de** [comment]
Thanks for the quick response.  The issue is closed and I figured out my own dumbness working like a charm.
