### ISSUE TITLE
INTERNAL_SUBNET CIDR notation ignored

### ISSUE THREAD

**Issue by alonbg** [linuxserver/docker-wireguard#107]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

for example `INTERNAL_SUBNET=10.8.0.0/16`
should be set in `wg0.conf` as
```
[Interface]
Address = 10.8.0.1/16
```
and the correct IPv4 mask on the wg interface (255.255.0.0 in this example)

## Current Behavior

no CIDR notation in `wg0.conf`
```
[Interface]
Address = 10.8.0.1
```
and accordingly wg0 interface mask is 255.255.255.255

## Steps to Reproduce

1. configure docker env with INTERNAL_SUBNET=10.8.0.0/16

2. after modifying  `Address` in `wg0.conf` as in `INTERNAL_SUBNET` interface is configured as expected.

**Comment by aptalca** [comment]
It's not proper CIDR. It basically uses a bash script to take the first 3 numbers and uses the subnet `XX.YY.ZZ.0/24`

The env var doesn't really accept `XX.XX.XX.XX/YY`, it accepts `XX.XX.XX.0`

**Comment by alonbg** [comment]
In which case INTERNAL_SUBNET seems a bit confusing (to me at least :).
Considering you'd want to support CIDR notation (which is needed in my case) then I suggest changing [this line](https://github.com/linuxserver/docker-wireguard/blob/65c7fe480c7294712dc15c7b2a823cf5cb194050/root/etc/cont-init.d/30-config#L246) to:
```sh
  # INTERNAL_SUBNET format net/mask: XX.XX.XX.XX[/YY]
  NET=${INTERNAL_SUBNET%/*} # XX.XX.XX.XX
  INTERFACE=${NET%.*} #  XX.XX.XX without last octet
  if echo "${INTERNAL_SUBNET}" | grep /; then # mask was specified
    export MASK=${INTERNAL_SUBNET#*/} # YY
  fi
 ```

And accordingly in `server.conf` template:
`Address = ${INTERFACE}.1/${MASK:-32}`

**Comment by aptalca** [comment]
I don't necessarily _want_ to support CIDR notation. I agree the wording can be a bit confusing due to the var name.

How is CIDR notation needed in your case? Do you have more than 256 devices?

Internal subnet is only used within the tunnel and is arbitrary. The only reason we allow setting a custom value is so you can make sure it's not the same as your existing subnet.

**Comment by alonbg** [comment]
I'm using a /16 size subnet. I'v divided this /16 subnet into 64 /24 CIDR ranges.
I'v configured pi-hole groups with these client IP subnets. Each group gives a different blocking combination.
With another service I'm allocating and keeping track of ip addresses according to ad hoc blocking needs.

**Comment by aptalca** [comment]
I don't see how that prevents you from using a dedicated /24 for wireguard

**Comment by alonbg** [comment]
I have 7 blocking categories. each one is a pi-hole group. enumerated id from 0x0.
That's 7! group combinations.
If I use /16 net size it can produce 64 CIDR ranges of 1024 addresses each (/22).  enumerated id from 0x0
Why 1024 ? because that's what the server can take. CIDR ranges are configured in pi-hole.
`(cidr-id|group-id) == true`  produces 193 combinations where this client range is configured for this group in pi-hole.
These are the valid combinations.
Accordingly, when a user chosen a combination, the IP [for the peer] will be allocated from the CIDR range id which was configured in pi-hole for all the groups in the combination.

**Comment by aptalca** [comment]
Feel free to set up multiple wireguard containers with different /24 blocks if you need to support more than 255 peers
