### ISSUE TITLE
ARM error

### ISSUE THREAD

**Issue by Kawabountou** [linuxserver/docker-wireguard#11]
hi and thant you for you job

i comme to you because I have this error when I launch the docker

run-parts: executing /etc/kernel/header_postinst.d/dkms 4.19.97-v8+
,
 * dkms: running auto installation service for kernel 4.19.97-v8+        
Error! Your kernel headers for kernel 4.19.97-v8+ cannot be found.
,
Please install the linux-headers-4.19.97-v8+ package,
,
or use the --kernelsourcedir option to tell DKMS where it's located
,

this kernel is missing?
that's why i can't connect?

thank you

**Comment by aptalca** [comment]
Please fill out the issue template, I have no idea what I'm looking at
