### ISSUE TITLE
client logs

### ISSUE THREAD

**Issue by ragnarok22** [linuxserver/docker-wireguard#110]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

currently the wireguard server does not keep any records of clients

------------------------------

## Desired Behavior
Hello, I would like to keep a record of user requests. In case of an incident, have a persistent record of the data of the people who connect to the server

## Current Behavior
currently the wireguard server does not keep any records of clients

## Alternatives Considered
I have tried to activate the logs through the linux kernel but it does not seem to support it. I followed these articles
https://serverfault.com/questions/1020279/how-to-see-debug-logs-for-wireguard-e-g-to-see-authentication-attempts
https://www.reddit.com/r/WireGuard/comments/jf72ja/wireguard_server_logs/g9jynse/

**Comment by drizuid** [comment]
This sounds like an issue to open with wireguard and not us.
