### ISSUE TITLE
Allow optional Server and/or Client MTU numeric environment variable for when behind IPv6 or DSL/PPoE connections

### ISSUE THREAD

**Issue by apainter2** [linuxserver/docker-wireguard#111]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Optional environment variable to allow a custom MTU setting for either Server or Peer, default MTU of 1500 does not work when you have the WireGuardserver on a DSL connection.

Due to the PPoE header being added to the MTU packet, Meaning whereas an MTU would normally be set to 1500, hosted WG on a PPoE based connection the MTU setting in wg0.conf (server-side) needs to be set to 1412. This gets worse if you need to take into account other MTU elements such as IPv4 to IPv6 etc.

Example: PEER_MTU=1412 would insert MTU=1412 into the peer.conf files, whereas SERVER_MTU=1412 would insert MTU=1412 into the server/wg0.conf file.

## Current Behavior
Tunnel is not established, and handshake errors/time-outs occur.

## Alternatives Considered
None available. Adjusting the MTU is the only way.

**Comment by ohthehugemanatee** [comment]
Is this problem verified by other users? I'm on a DSL/PPoE connection and having trouble with slow/broken connections between a roaming peer and my home wireguard server. What's a good way to validate that this MTU issue is what's happening to me?

**Comment by aptalca** [comment]
You can add mtu to the server and peer templates and then all confs will be generated with that mtu setting.

If you want to add it to a single peer, you can manually add it when you're setting up the client.

**Comment by brandonros** [comment]
> You can add mtu to the server and peer templates and then all confs will be generated with that mtu setting.
> 
> If you want to add it to a single peer, you can manually add it when you're setting up the client.

How? What's the setting name?

**Comment by aptalca** [comment]
It's `MTU`.

Did you try googling `wireguard mtu setting`?
