### ISSUE TITLE
ListenPort for peer template should be configurable

### ISSUE THREAD

**Issue by wiruzman** [linuxserver/docker-wireguard#112]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
ListenPort for peer template should be configurable because it can run into a loop if endpoint points to same ip on the same port. For development purposes it is needed.

## Current Behavior
ListenPort for peer template is not configurable and running into a loop if the endpoint is pointing to same ip.

## Alternatives Considered
Using another port for endpoint.

**Comment by aptalca** [comment]
Why would endpoint point to same ip and port? The listen port is only the container port and can be mapped to any port on host.

Sounds like you need to explain your use case more clearly.
