### ISSUE TITLE
Publish documentation which tells users how to route traffic from host to wireguard container

### ISSUE THREAD

**Issue by nickshanks347** [linuxserver/docker-wireguard#115]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Let's say you have two docker container: wireguard and nginx_proxymanager. You can ping each container because they're on the same docker network, but, wireguard has another interface, wg0, with a different network address (10.13.13.0). I've read a lot of forum posts and a lot of people have the same issue. The whole point of nginx_proxymanager is to reverse proxy traffic - it's proving difficult to call the vpn subnet from within the nginx container because it doesn't know wg0 exists. It can ping the wireguard container through the interface that's on the docker network, but that's expected. I'm hoping a contributor can set out the steps so that the vpn subnet is accessible from other containers (or from the host, or both)

## Current Behavior
VPN subnet isn't accessible to other containers.

**Comment by GilbN** [comment]
Take a look at https://spad.uk/wireguard-as-a-vpn-client-in-docker-using-pia/

Please use discord or Discourse for support.

https://www.linuxserver.io/support

**Comment by nickshanks347** [comment]
Please add that link to this repositories README file, it will make a lot of peoples lives easier.
