### ISSUE TITLE
Not regenerating peer config when using peer name list

### ISSUE THREAD

**Issue by bmorrellbunnings** [linuxserver/docker-wireguard#118]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Deleting a peer config then restarting the docker image should regenerate that config without changing the existing peer configs.
Adding a new named peer to the `PEERS` list should also create that new peer without changing the existing peer configs.

## Current Behavior
When I add a new peer to the comma separated list `PEERS`, or delete a peer config from the `config/` folder, it never gets generated. If I delete the entire `config/` folder it generates all the peer configs successfully.

## Steps to Reproduce
1. Setup `PEERS` with 3 or for named peers and generate them by running the image
2. Now, delete one of those peer's configs from the `config/` folder
3. Restart the image

Or

1. Setup `PEERS` with 3 or for named peers and generate them by running the image
2. Add a new peer to the peers list
3. Restart the image

## Environment
**OS:** Linux pi 5.10.43-1-MANJARO-ARM
**CPU architecture:** arm64
**How docker service was installed:**
From official repo

## Command used to create docker container (run/create/compose/screenshot)

`sudo docker-compose up -d`

## Docker logs

```
wireguard    | Brought to you by linuxserver.io
wireguard    | -------------------------------------
wireguard    |
wireguard    | To support the app dev(s) visit:
wireguard    | WireGuard: https://www.wireguard.com/donations/
wireguard    |
wireguard    | To support LSIO projects visit:
wireguard    | https://www.linuxserver.io/donate/
wireguard    | -------------------------------------
wireguard    | GID/UID
wireguard    | -------------------------------------
wireguard    |
wireguard    | User uid:    1000
wireguard    | User gid:    1000
wireguard    | -------------------------------------
wireguard    |
wireguard    | [cont-init.d] 10-adduser: exited 0.
wireguard    | [cont-init.d] 30-config: executing...
wireguard    | Uname info: Linux 825b46d090b5 5.10.43-1-MANJARO-ARM #1 SMP PREEMPT Mon Jun 14 14:31:41 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
wireguard    | **** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
wireguard    | **** Server mode is selected ****
wireguard    | **** SERVERURL var is either not set or is set to "auto", setting external IP to auto detected value of 180.150.123.244 ****
wireguard    | **** External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container ****
wireguard    | **** Internal subnet is set to 10.13.13.0 ****
wireguard    | **** AllowedIPs for peers 0.0.0.0/0 ****
wireguard    | **** PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.13.13.1 to use wireguard docker host's DNS. ****
wireguard    | **** Server mode is selected ****
wireguard    | **** No changes to parameters. Existing configs are used. ****
wireguard    | [cont-init.d] 30-config: exited 0.
wireguard    | [cont-init.d] 99-custom-scripts: executing...
wireguard    | [custom-init] no custom files found exiting...
wireguard    | [cont-init.d] 99-custom-scripts: exited 0.
wireguard    | [cont-init.d] done.
wireguard    | [services.d] starting services
wireguard    | [services.d] done.
wireguard    | [#] ip link add wg0 type wireguard
wireguard    | [#] wg setconf wg0 /dev/fd/63
wireguard    | [#] ip -4 address add 10.13.13.1 dev wg0
wireguard    | .:53
wireguard    | CoreDNS-1.8.4
wireguard    | linux/arm64, go1.16.4, 053c4d5
wireguard    | [#] ip link set mtu 1420 up dev wg0
wireguard    | [#] ip -4 route add 10.13.13.5/32 dev wg0
wireguard    | [#] ip -4 route add 10.13.13.4/32 dev wg0
wireguard    | [#] ip -4 route add 10.13.13.3/32 dev wg0
wireguard    | [#] ip -4 route add 10.13.13.2/32 dev wg0
wireguard    | [#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
```

**Comment by aptalca** [comment]
You need to recreate the container, not restart

**Comment by bmorrellbunnings** [comment]
Commands
```
sudo docker-compose down
sudo docker-compose up -d --force-recreate
```
does not regenerate config.
Confirmed the container was destroyed with `sudo docker container ls -a` after the down

**Comment by jpdsc** [comment]
Same issue here. I changed peer1.conf which should re-create a new QR and it didn't. QR code has the same information.
In this case, I changed the `AllowedIPs = 0.0.0.0/0` line

**Comment by mpeter50** [comment]
I also have this problem, where if I delete some of the `/config/peer_peername` directories it won't get regenerated when I restart the container with `docker-compose down; docker-compose up -d` or with `docker-compose up -d --force-recreate`.

Though I think I noticed something that hasn't been mentioned before: the logs contain an error message that might be relevant.
Running `docker-compose logs -ft` I get the container logs, from what there is this few lines:
```
wireguard    | 2021-12-29T17:28:04.288491478Z **** Server mode is selected ****
wireguard    | 2021-12-29T17:28:04.289039913Z **** Server related environment variables changed, regenerating 1 server and PEER1,PEER2,PEER3 peer/client confs ****
wireguard    | 2021-12-29T17:28:04.371310048Z /var/run/s6/etc/cont-init.d/40-confs: line 54: SERVER_ALLOWEDIPS_PEER_PEER1: bad substitution
wireguard    | 2021-12-29T17:28:04.383393403Z [cont-init.d] 40-confs: exited 0.
wireguard    | 2021-12-29T17:28:04.389403304Z [cont-init.d] 90-custom-folders: executing...
```

In the log lines above I replaced the peer list in the second line and the peername in the third line.
The third line indicates an error here: https://github.com/linuxserver/docker-wireguard/blob/1a97e86822faca2faae19f4b58283f46c6195e56/root/etc/cont-init.d/40-confs#L54

I experience this with the container image with the ID `f0c1033ce62c`.
I've just updated from `8af4bdfe2956`, and after going back to that container image the scripts are regenerated as expected.

**Comment by aptalca** [comment]
My guess is your peer names contain non-alphanumeric characters, which is not allowed. But I can't be sure because you redacted them

**Comment by mpeter50** [comment]
well, it contains alphanumeric characters and hyphens. Are hyphens forbidden?

**Comment by aptalca** [comment]
hyphen is not alphanumeric

**Comment by mpeter50** [comment]
oh, sorry, it just seemed natural that it is accepted too.
I think the issue is kind of solved on my end.
