### ISSUE TITLE
Setting a custom listen port

### ISSUE THREAD

**Issue by Baitinq** [linuxserver/docker-wireguard#119]
It would be really cool if there was a variable to change the listen port, instead of it being defaulted to 51820. This way you could use a custom port with --net=host.

Let me know what you think about this,

Thanks

**Comment by SamuelBartik** [comment]
You can change it in the wg0.conf file as far as I know.

**Comment by drizuid** [comment]
We dont plan to support this running in host mode so this wouldn't make sense. you can fork and modify or use docker-mods to make it work how you want to though.
https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
