### ISSUE TITLE
Error! Your kernel headers for kernel 4.19.97-v8+ cannot be found

### ISSUE THREAD

**Issue by tynor88** [linuxserver/docker-wireguard#12]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
No errors in log when checking for kernel headers

## Current Behavior
Logs in error when installing kernel-headers after image update / first install. The container seems to work though (might not be critical)

## Steps to Reproduce
docker run -d --name=wireguard --net=host --cap-add NET_ADMIN --device=/dev/net/tun --cap-add=SYS_MODULE --net=HOST -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -v /home/pi/docker-apps/wireguard/config:/config -v /lib/modules:/lib/modules --sysctl="net.ipv4.conf.all.src_valid_mark=1" -e SERVERURL=xxx.xxx.xxx -e SERVERPORT=51820 -e PEERS=1 -e INTERNAL_SUBNET=10.253.1.0 -p 51820:51820/udp --restart unless-stopped linuxserver/wireguard

## Environment
**OS:** Raspbian
**CPU architecture:** armhf (RaspberryPI 3 B)
**How docker service was installed:** docker run       

## Command used to create docker container (run/create/compose/screenshot)
docker run -d --name=wireguard --net=host --cap-add NET_ADMIN --device=/dev/net/tun --cap-add=SYS_MODULE --net=HOST -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -v /home/pi/docker-apps/wireguard/config:/config -v /lib/modules:/lib/modules --sysctl="net.ipv4.conf.all.src_valid_mark=1" -e SERVERURL=xxx.xxx.xxx -e SERVERPORT=51820 -e PEERS=1 -e INTERNAL_SUBNET=10.253.1.0 -p 51820:51820/udp --restart unless-stopped linuxserver/wireguard

## Docker logs

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 01-envfile: executing...
> [cont-init.d] 01-envfile: exited 0.
> [cont-init.d] 10-adduser: executing...
> 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> -------------------------------------
> 
> To support the app dev(s) visit:
> WireGuard: https://www.wireguard.com/donations/
> 
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> 
> User uid:    1000
> User gid:    1000
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 30-config: executing...
> Get:1 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic InRelease [15.9 kB]
> Get:2 http://ports.ubuntu.com/ubuntu-ports bionic InRelease [242 kB]
> Get:3 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease [88.7 kB]
> Get:4 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease [74.6 kB]
> Get:5 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease [88.7 kB]
> Get:6 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main Sources [1,170 B]
> Get:7 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main armhf Packages [925 B]
> Get:8 http://ports.ubuntu.com/ubuntu-ports bionic/multiverse armhf Packages [157 kB]
> Get:9 http://ports.ubuntu.com/ubuntu-ports bionic/universe armhf Packages [11.0 MB]
> Get:10 http://ports.ubuntu.com/ubuntu-ports bionic/main armhf Packages [1,277 kB]
> Get:11 http://ports.ubuntu.com/ubuntu-ports bionic/restricted armhf Packages [12.5 kB]
> Get:12 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe armhf Packages [1,146 kB]
> Get:13 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main armhf Packages [787 kB]
> Get:14 http://ports.ubuntu.com/ubuntu-ports bionic-updates/multiverse armhf Packages [4,605 B]
> Get:15 http://ports.ubuntu.com/ubuntu-ports bionic-updates/restricted armhf Packages [10.6 kB]
> Get:16 http://ports.ubuntu.com/ubuntu-ports bionic-backports/main armhf Packages [2,490 B]
> Get:17 http://ports.ubuntu.com/ubuntu-ports bionic-backports/universe armhf Packages [4,239 B]
> Get:18 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe armhf Packages [675 kB]
> Get:19 http://ports.ubuntu.com/ubuntu-ports bionic-security/restricted armhf Packages [5,013 B]
> Get:20 http://ports.ubuntu.com/ubuntu-ports bionic-security/main armhf Packages [519 kB]
> Get:21 http://ports.ubuntu.com/ubuntu-ports bionic-security/multiverse armhf Packages [2,077 B]
> Fetched 16.1 MB in 14s (1,134 kB/s)
> Reading package lists...
> Raspbian kernel naming convention detected, attempting to install raspbian kernel headers
> Warning: apt-key output should not be parsed (stdout is not a terminal)
> OK
> Hit:1 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic InRelease
> Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
> Get:3 http://archive.raspberrypi.org/debian buster InRelease [25.1 kB]
> Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
> Hit:5 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
> Hit:6 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
> Get:7 http://archive.raspberrypi.org/debian buster/main Sources [91.4 kB]
> Get:8 http://archive.raspberrypi.org/debian buster/main armhf Packages [326 kB]
> Fetched 443 kB in 3s (160 kB/s)
> Reading package lists...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> The following additional packages will be installed:
>   wireguard-dkms wireguard-tools
> The following NEW packages will be installed:
>   raspberrypi-kernel-headers wireguard wireguard-dkms wireguard-tools
> 0 upgraded, 4 newly installed, 0 to remove and 6 not upgraded.
> Need to get 25.3 MB of archives.
> After this operation, 165 MB of additional disk space will be used.
> Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20200212-1 [24.9 MB]
> Get:2 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main armhf wireguard-dkms all 1.0.20200401-1ubuntu1~18.04 [253 kB]
> Get:3 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main armhf wireguard-tools armhf 1.0.20200319-0ppa1~18.04 [78.8 kB]
> Get:4 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main armhf wireguard all 1.0.20200319-0ppa1~18.04 [7,980 B]
> Fetched 25.3 MB in 8s (3,308 kB/s)
> Selecting previously unselected package raspberrypi-kernel-headers.
> (Reading database ... 46143 files and directories currently installed.)
> Preparing to unpack .../raspberrypi-kernel-headers_1.20200212-1_armhf.deb ...
> Unpacking raspberrypi-kernel-headers (1.20200212-1) ...
> Selecting previously unselected package wireguard-dkms.
> Preparing to unpack .../wireguard-dkms_1.0.20200401-1ubuntu1~18.04_all.deb ...
> Unpacking wireguard-dkms (1.0.20200401-1ubuntu1~18.04) ...
> Selecting previously unselected package wireguard-tools.
> Preparing to unpack .../wireguard-tools_1.0.20200319-0ppa1~18.04_armhf.deb ...
> Unpacking wireguard-tools (1.0.20200319-0ppa1~18.04) ...
> Selecting previously unselected package wireguard.
> Preparing to unpack .../wireguard_1.0.20200319-0ppa1~18.04_all.deb ...
> Unpacking wireguard (1.0.20200319-0ppa1~18.04) ...
> Setting up wireguard-dkms (1.0.20200401-1ubuntu1~18.04) ...
> Loading new wireguard-1.0.20200401 DKMS files...
> It is likely that 4.19.97-v7+ belongs to a chroot's host
> Building for 4.19.114+, 4.19.114-v7+, 4.19.97+, 4.19.97-v7+, 4.19.97-v7l+ and 4.19.97-v8+
> Module build for kernel 4.19.114+ was skipped since the
> kernel headers for this kernel does not seem to be installed.
> Module build for kernel 4.19.114-v7+ was skipped since the
> kernel headers for this kernel does not seem to be installed.
> Building initial module for 4.19.97+
> Done.
> 
> wireguard:
> Running module version sanity check.
> 
> Good news! Module version 1.0.20200401 for wireguard.ko
> exactly matches what is already found in kernel 4.19.97+.
> DKMS will not replace this module.
> You may override by specifying --force.
> 
> depmod....
> 
> DKMS: install completed.
> Building initial module for 4.19.97-v7+
> Done.
> 
> wireguard:
> Running module version sanity check.
> 
> Good news! Module version 1.0.20200401 for wireguard.ko
> exactly matches what is already found in kernel 4.19.97-v7+.
> DKMS will not replace this module.
> You may override by specifying --force.
> 
> depmod....
> 
> DKMS: install completed.
> Building initial module for 4.19.97-v7l+
> Done.
> 
> wireguard:
> Running module version sanity check.
> 
> Good news! Module version 1.0.20200401 for wireguard.ko
> exactly matches what is already found in kernel 4.19.97-v7l+.
> DKMS will not replace this module.
> You may override by specifying --force.
> 
> depmod....
> 
> DKMS: install completed.
> Module build for kernel 4.19.97-v8+ was skipped since the
> kernel headers for this kernel does not seem to be installed.
> Setting up wireguard-tools (1.0.20200319-0ppa1~18.04) ...
> Setting up raspberrypi-kernel-headers (1.20200212-1) ...
> run-parts: executing /etc/kernel/header_postinst.d/dkms 4.19.97+
>  * dkms: running auto installation service for kernel 4.19.97+           [ OK ]
> run-parts: executing /etc/kernel/header_postinst.d/dkms 4.19.97-v7+
>  * dkms: running auto installation service for kernel 4.19.97-v7+        [ OK ]
> run-parts: executing /etc/kernel/header_postinst.d/dkms 4.19.97-v7l+
>  * dkms: running auto installation service for kernel 4.19.97-v7l+       [ OK ]
> run-parts: executing /etc/kernel/header_postinst.d/dkms 4.19.97-v8+
>  * dkms: running auto installation service for kernel 4.19.97-v8+               Error! Your kernel headers for kernel 4.19.97-v8+ cannot be found.
> Please install the linux-headers-4.19.97-v8+ package,
> or use the --kernelsourcedir option to tell DKMS where it's located
>                                                                          [ OK ]
> Setting up wireguard (1.0.20200319-0ppa1~18.04) ...
> Server mode is selected
> External server address is set to xxx.xxx.xxx
> External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container
> Internal subnet is set to 10.253.1.0
> PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.253.1.1 to use wireguard docker host's DNS.
> Server mode is selected
> No changes to parameters. Existing configs are used.
> [cont-init.d] 30-config: exited 0.
> [cont-init.d] 99-custom-scripts: executing...
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-scripts: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> Warning: `/config/wg0.conf' is world accessible
> [#] ip link add wg0 type wireguard
> [#] wg setconf wg0 /dev/fd/63
> [#] ip -4 address add 10.253.1.3 dev wg0
> [#] ip link set mtu 1420 up dev wg0
> [#] ip -4 route add 192.168.1.0/24 dev wg0
> [#] ip -4 route add 10.253.1.0/24 dev wg0
> [#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
> .:53
> CoreDNS-1.6.9
> linux/arm, go1.14.1, 1766568

**Comment by tynor88** [comment]
Same issue as https://github.com/linuxserver/docker-wireguard/issues/11 I just created the issue through the template

**Comment by aptalca** [comment]
There is no issue, it's installed and it's working. Don't use host networking and no idea why you mapped net/tun

**Comment by n1ghtw0lf1** [comment]
And how i can use host networking ?
