### ISSUE TITLE
Option to disable masquerading

### ISSUE THREAD

**Issue by codecat** [linuxserver/docker-wireguard#121]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Allow setting an option to disable the masquerading `iptables` calls in `PostUp` and `PostDown` for the first configuration.

## Current Behavior
Currently, masquerading is always enabled, and this may not be desired.

## Alternatives Considered
I've manually modified `config/wg0.conf` to remove the masquerading rules, which works, but is not ideal.

**Comment by drizuid** [comment]
you're free to customize our container as you see fit, but we have no intention of making any changes currently.
