### ISSUE TITLE
Kernel headers don't seem to be available

### ISSUE THREAD

**Issue by uinguzero** [linuxserver/docker-wireguard#122]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Current Behavior
when viewing the logs of the container i get this:

**** No kernel headers found in the Ubuntu or Debian repos!! Will try the headers from host (if mapped), may or may not work ****
**** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ****

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:** 
Fedora 34
**CPU architecture:** x86_64/arm32/arm64
x64
**How docker service was installed:**

podman that came with fedroa

## Docker logs

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Uname info: Linux 43efaf8d4cf7 5.13.5-200.fc34.x86_64 #1 SMP Sun Jul 25 16:19:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Error: Unknown device type.
**** The wireguard module is not active, will attempt kernel header install and module compilation. ****
**** Attempting kernel header install ****
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/multiverse Sources [216 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/main Sources [1,063 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/restricted Sources [5,823 B]
Get:8 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Sources [16.4 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [576 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Sources [27.1 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [647 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [537 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [33.6 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2,694 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,194 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-security/multiverse Sources [8,780 B]
Get:21 http://archive.ubuntu.com/ubuntu bionic-security/universe Sources [348 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-security/restricted Sources [23.6 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-security/main Sources [324 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,420 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [505 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2,258 kB]
Get:27 http://archive.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [26.7 kB]
Fetched 37.7 MB in 6s (6,477 kB/s)
Reading package lists...
**** No kernel headers found in the Ubuntu or Debian repos!! Will try the headers from host (if mapped), may or may not work ****
**** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ****

**Comment by TheSpad** [comment]
As per the readme

> This image is designed for Ubuntu and Debian based systems mainly (it works on some others, but ymmv). During container start, it will first check if the wireguard module is already installed and loaded. If not, it will then check if the kernel headers are already installed (in /usr/src) and if not, attempt to download the necessary kernel headers from the ubuntu/debian/raspbian repos; then will compile and install the kernel module.

You'll need to provide and map your own kernel headers if you're running on Fedora. Note that we don't test with podman so you may run into issue there as well.

**Comment by shinsenter** [comment]
> If you are trying to run this Wireguard image on Fedora/CentOS/RHEL using Podman then try using `--cap-add=ALL`. Once it is up and running, then add Linux capabilities one-by-one until the container runs without issues.
> 
> Edit: I will update further when I find the bare-minimum Linux capabilities that are required

Not working on CentOS 7

**Comment by Ashkaan** [comment]
I'm having the exact same issue on Synology DSM 7 Docker.  I mapped /lib/modules properly and still have the same issue.  Is there another mapping that I'm supposed to do?

**Comment by Silversurfer79** [comment]
Im finding the comments specially in this topic "Wireguard", across a lot of forums are less than helpful and assume a lot. It seems to be a reoccurring theme, almost like this community doesn't want to be helpful and I don't say this lightly. Some of the people are asking because they don't understand the basic Linux fundamentals and the answers seem less than helpful. 

I am yet to see a actual answer where specific instructions are give or what to do. 

I mean look at this statement, 
> @Ashkaan on Synology, you need to use the third party module and install that on the host first before you can use the container.

What third party modules, I'm I don't want start installing all sort of crap on my NAS and as in most cases these are multi role devices. 

It would seem that this specific community seems very guarded for some reason.

**Comment by Silversurfer79** [comment]
I'm also running this on a Synology NAS and have the same issue, what in clear and plain non ambiguous English needs to happen in order to get thee container up and running please.

OS: DMS7
Platform: Docker and Portainer being used

Error:
**** No kernel headers found in the Ubuntu or Debian repos!! Will try the headers from host (if mapped), may or may not work ****
**** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ****

What 3rd party module do I need to use and how do I install it?

**Comment by j0nnymoe** [comment]
A module like this is something you'll need to run: https://github.com/runfalk/synology-wireguard
but we do not test our wireguard container with these types of modules so your milage may vary.

**Comment by Silversurfer79** [comment]
That's a great answer thanks, much appreciated!

**Comment by Silversurfer79** [comment]
So based on what I have read, this is more of risk than I'm prepared to carry out on my NAS, so Ill try run on a separate device like a Raspberry PI instead. thanks for the advise.

**Comment by BorisTheTripper** [comment]
Can this be used on WSL? I'm not a Linux user at all, I'm just trying to run some Docker containers making sure the requests inside them are sent with Mullvad VPN, and I'm getting this same same issue. The` /lib/modules` folder is always empty on WSL, I'm not sure what that means. I also did as described [here](https://github.com/microsoft/WSL2-Linux-Kernel), and the terminal said the kernel is now ready. Running `uname -a` returns `Linux LAPTOP-A4TCO76A 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`. Here are the wireguard container logs:

```
Uname info: Linux d45c2577f51d 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
RTNETLINK answers: Operation not permitted
**** The wireguard module is not active, will attempt kernel header install and module compilation. ****
**** Attempting kernel header install ****
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/restricted Sources [5,823 B]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main Sources [1,063 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/multiverse Sources [216 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [651 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Sources [18.1 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Sources [29.1 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [587 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2,867 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [699 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,219 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [34.4 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-security/universe Sources [356 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-security/restricted Sources [25.7 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-security/main Sources [326 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-security/multiverse Sources [8,784 B]
Get:24 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2,430 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [666 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [26.8 kB]
Get:27 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,439 kB]
Fetched 38.5 MB in 2min 9s (298 kB/s)
Reading package lists...
**** No kernel headers found in the Ubuntu or Debian repos!! Will try the headers from host (if mapped), may or may not work ****
**** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ****
```

**Comment by aptalca** [comment]
You'll have to install the kernel headers on host and map their location in, or compile the kernel module on host (in wsl)

**Comment by mulzhang** [comment]
install kernel : 
https://blog.csdn.net/m0_49807299/article/details/108181664
