### ISSUE TITLE
Option to remove DNS from Peer Config

### ISSUE THREAD

**Issue by rmayobre** [linuxserver/docker-wireguard#126]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

I couldn't find any documentation on removing the `DNS` settings in a peer config file. If this isn't a feature that's currently support, I would very much like to request this as a feature.

My main usage for this is to utilize Wireguard as a means to tunnel traffic of a specific sub net to a remote server that privately hosts services. I don't want all my peer's internet tunneling into Wireguard, so I set the `AllowedIPs` to the specific subnet; however, when I do that I lose internet.

An idea I had was to create another environment variable that acts a boolean flag: include DNS config, or not?

### Example
```shell
- NOPEERDNS = 1 # default value is 0
```

## Current Behavior

The way a peer's DNS is configure is by utilizing `PEERDNS`, but if you remove it or set it blank; it defaults to `auto`. If i set it explicitly to a blank value, the default behavior could remove the DNS field entirely.

## Alternatives Considered

The only solution is to remove the `DNS` settings in the peer config file. I was hoping I could automate this instead of manually editing the wireguard config files.

**Comment by rmayobre** [comment]
I'm going to close this issue. You can set the env `PEERDNS` value as `- PEERDNS=''` and it will set all peer's conf file with `DNS = ''`. Wireguard will then ignore the `DNS` setting and you can use the peer connection without forcing a DNS tunneling. Not the most elegant solution, but it works.

**Comment by Juniorsnet** [comment]
This does not work on android phone

**Comment by rmayobre** [comment]
> This does not work on android phone

I don't have the full context to what's happening to you, but I believe Android has a system setting for DNS control that may help. I did notice on devices running Android 7 (maybe more versions are affected) the DNS setting does not work as intended. This might be an issue with the Wireguard app or the OS networking.

**Comment by rasodu** [comment]
I tried to set it to an empty string. I am also getting an error message while importing the connection to an Android device.

 When I scan the QR code, I get the error message "Unable to import tunnel. Cannot parse IP address '''' in interface's DNS.

**Comment by aptalca** [comment]
You can remove it from the peer/client template and it won't be added

**Comment by an-tex** [comment]
setting it to an empty string is treated the same as `auto` (due to -z check). setting it to `invalid` (or probably any non-ip) works though as wireguard client then ignores it
