### ISSUE TITLE
Peer config creation error when using string list

### ISSUE THREAD

**Issue by vinerich** [linuxserver/docker-wireguard#127]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

As stated in the official (documentation)[https://docs.linuxserver.io/images/docker-wireguard] the `PEERS` environment variable should be able to take both, an integer, or a list of comma separated strings.

A list of comma seperated strings should be used to create `peer_X` config entries for each specified string.
- The resulting peer config should be correctly loaded at server startup
- The resulting peer config should include the private key of the peer

## Current Behavior

To show the errors happening the environment is set as follows:
- `PEERS=test_user`
- `PEERS=test.user`
- `PEERS=testuser`

While creating the peers on initial startup different error message are shown, which I will keep separated for each test case.

### test_user
<details>
<summary>Log output</summary>

```
**** No wg0.conf found (maybe an initial install), generating 1 server and test_user peer/client confs ****
grep: /config/peer*/*.conf: No such file or directory
cat: /config/peertest_user/privatekey-peertest_user: No such file or directory
PEER test_user QR code:
XXXXX
```
</details>

- The `privatekey` of the user to create can't be inserted into the `peer.conf` since the needed underscore `peer_X` is missing in the `cat` command
- The server is not using the generated `peer.conf` since the grep pattern `grep: /config/peer*/*.conf` does not include the underscore

As a result the generated `peer.conf` is invalid and even if copied together with the privatekey is not working since the server does not know about it.

### test.user
<details>
<summary>Log output</summary>

```
**** No wg0.conf found (maybe an initial install), generating 1 server and test.user peer/client confs ****
grep: /config/peer*/*.conf: No such file or directory
/var/run/s6/etc/cont-init.d/30-config: line 204: test.user + 1 : syntax error: invalid arithmetic operator (error token is ".user + 1 ")
PEER test.user QR code:
/var/run/s6/etc/cont-init.d/30-config: line 212: /config/peer_testuser/peer_testuser.conf: No such file or directory
/var/run/s6/etc/cont-init.d/30-config: line 213: /config/peer_testuser/peer_testuser.conf: No such file or directory
```
</details>

The peer generation fails since the dot in `test.user` is not correctly handled. I'd love some kind of seperator available (`.`, `-`, `_`).
The documentation does not tell about which format the strings need to have to be accepted by the peer generation.

### testuser

Same error as `test_user`.

## Steps to Reproduce

1. Use docker-wireguard image `linuxserver/wireguard:amd64-version-v1.0.20210424`
2. Specify env `PEERS=test_user,test.user,testuser`
3. Observe errors on intial startup

## Environment
**OS:** Ubuntu 20.03
**CPU architecture:** x86_64
**How docker service was installed:** Official docker repo

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose up -d`
```docker-compose
  wireguard-temp:
    image: linuxserver/wireguard:amd64-version-v1.0.20210424
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=xxx
      - SERVERPORT=xxx
      - PEERS=test_user,test.user,testuser
      - PEERDNS=auto
    volumes:
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
```

## Docker logs

<details>

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
Uname info: Linux 4e12ca04281c 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 x86_64 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** Server mode is selected ****
**** External server address is set to xxx ****
**** External server port is set to xxx. Make sure that port is properly forwarded to port 51820 inside this container ****
**** Internal subnet is set to 10.13.13.0 ****
**** AllowedIPs for peers 0.0.0.0/0, ::/0 ****
**** PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.13.13.1 to use wireguard docker host's DNS. ****
**** No wg0.conf found (maybe an initial install), generating 1 server and test.user peer/client confs ****
PEER test.user QR code:
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
.:53
CoreDNS-1.8.4
linux/amd64, go1.16.4, 053c4d5
```
</details>

**Comment by vinerich** [comment]
Any news on this? Should I provide more information?
Thanks in advance!

**Comment by aptalca** [comment]
Sorry, forgot to respond to this issue. The PEERS list only supports alphanumeric, but the readme failed to detail that. It has now been fixed.
