### ISSUE TITLE
modprobe can't load ZSTD compressed kernel modules

### ISSUE THREAD

**Issue by sysedwinistrator** [linuxserver/docker-wireguard#128]
Hi,
the official Arch kernel ships with modules compressed via ZSTD (`CONFIG_MODULE_COMPRESS_ZSTD`). Compressing the modules via ZSTD during the kernel build is supported since Linux 5.13. But you also need userspace tools capable of loading them.

`kmod` supports ZSTD since version 28, which is only available in the Ubuntu repos for 21.04, but that build has ZSTD support disabled (Ubuntu also disables support for ZLIB compressed kernel modules, though I can't say how common those are).

This is obviously not an issue for Ubuntu or most other distros that don't use very recent kernels. But if the container runs on a system with such a configuration, it will fail to load the necessary kernel modules and consequently fail to set up the WireGuard interface.

Two possible solutions:
1. Provide an alternative image based on Alpine. Alpine has `kmod` 28 since 3.13, with support for both ZSTD and ZLIB enabled. Alpine does not support DKMS and thus cannot provide the functionality of building WireGuard for kernels that don't have the module. But since `CONFIG_MODULE_COMPRESS_ZSTD` is supported since 5.13, and `CONFIG_WIREGUARD` since 5.6; anybody who has ZSTD-compressed kernel modules *should* have WireGuard baked into the kernel.
2. Build `kmod` 28 with ZSTD support for the base image.

**Comment by aptalca** [comment]
There is no easy solution. Definitely don't have time to rebase on another OS, or maintain two images.

**Comment by aptalca** [comment]
@sysedwinistrator What's the status of this with ubuntu jammy? We can potentially rebase to that if that works

**Comment by sysedwinistrator** [comment]
Thanks @aptalca for coming back to this issue. Jammy has zstd enabled:
```
root@b30d91d252f0:/# modprobe -V                                            kmod version 29                                                             +ZSTD +XZ -ZLIB +LIBCRYPTO -EXPERIMENTAL
```
I was able to load a zstd-compressed host kernel module from inside a jammy container on Arch Linux running the default linux kernel package.

**Comment by bukowa** [comment]
Also cannot run on:

````bash
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
````
````bash
kmod version 29
+ZSTD +XZ -ZLIB +LIBCRYPTO -EXPERIMENTAL
````

**Comment by aptalca** [comment]
#189
