### ISSUE TITLE
I can connect to the VPN, however, I have no internet?

### ISSUE THREAD

**Issue by BrodyStone21** [linuxserver/docker-wireguard#130]
I've been trying to get this up and running for the past four hours. I've tried everything that I can think of, but I'm out of guesses. I tried googling around and found a couple similar issues but nothing that seemed to be the problem I'm experiencing. As the title states I can connect to the VPN and access it remotely, but if I try to ping or access a website from my phone I don't get any hits.

I have ran wireguard as a client on this same machine and it worked, but I can't get it working as a server. Could someone please take a look and let me know what you think it could be?

Docker run command:
```
docker run -d \
  --name=wireguard \
  --net=host \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/Indianapolis \
  -e SERVERPORT=51825 \
  -e SERVERURL=auto \
  -e PEERS="Pixel_5,Laptop,other" \
  -e PEERDNS=auto \
  -e INTERNAL_SUBNET=10.13.13.0 \
  -e ALLOWEDIPS=0.0.0.0/0 \
  -v /home/ubuntu/wireguard:/config \
  -v /lib/modules:/lib/modules \
  --restart unless-stopped \
  linuxserver/wireguard
```

Output of `docker logs wireguard:
```
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Another service is using port 53, disabling CoreDNS
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.13.1 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] ip -4 route add 10.13.13.4/32 dev wg0
[#] ip -4 route add 10.13.13.3/32 dev wg0
[#] ip -4 route add 10.13.13.2/32 dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
```
wg0.conf file:
```
[Interface]
Address = 10.13.13.1
ListenPort = 51820 
PrivateKey = 
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
# peer_Pixel_5
PublicKey = 
AllowedIPs = 10.13.13.2/32

[Peer]
# peer_Laptop
PublicKey = 
AllowedIPs = 10.13.13.3/32

[Peer]
# peer_other
PublicKey = 
AllowedIPs = 10.13.13.4/32
```
Environment: Ubuntu Server 20.04 LTS

Do note that the `ListenPort` shows 51820 in the wg0.conf but I have changed it in the container run command. I have updated the wg0.conf file to reflect this as well but to no avail at either 51820 or 51821.

Also, the only reason I'm using `--net=host` is because I was trying to see if it'd work, obviously, it did not. 

This may be a dumb question; do I need to be port forwarded?

**Comment by aptalca** [comment]
Don't run it in host mode. Especially when PEERDNS is set to auto. There is no coredns running, so no dns in the container

Check the wg status on the server to make sure your client indeed connected:
`docker exec -it wireguard wg show`
If it doesn't show a handshake, it's never connected. Check the server IPs and port forwarding.
Drop by our discord or forum for help
