### ISSUE TITLE
Add an option to specify the network interface for the iptables commands in wg0.conf

### ISSUE THREAD

**Issue by MatanSilver** [linuxserver/docker-wireguard#131]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
The proposed feature is to add a config option (to be set either with a flag in the docker invokation, or as a setting in `docker-compose.yml`), to change the network interface from `eth0` to a custom interface name.

## Current Behavior
Currently, if the suggested docker-compose configuration is used, a wg0.conf file will be generated with `eth0` as the hard-coded interface. However, some devices do not name their network interfaces `eth0` by default. For example, I am using an Odroid XU4 and for some reason the network interface is named `enx001e06377008`. If this config is used on a device with no `eth0` interface, the default generated config will result in incorrect routing.

## Alternatives Considered
The current workaround for me is to generate `wg0.conf` with docker-compose, and then manually modify the file to reference the correct interface. However, this gets wiped out if I ever need to regenerate the config. A config option in `docker-compose.yml` would allow `wg0.conf` to be correctly generated without manual intervention.

**Comment by aptalca** [comment]
`eth0` refers to the interface inside the container, not on host. That interface is always `eth0`
