### ISSUE TITLE
How to Change Port That Wireguard Uses?

### ISSUE THREAD

**Issue by BrodyStone21** [linuxserver/docker-wireguard#132]
I keep trying to change the port that wireguard runs on but I'm having issues. If I change the port in the container run command as well as changing the endpoint port in the `wg0.conf` file I can't connect to the internet.

If I change just the port in the run command it works fine but it still runs on port 51820.

I'm trying to set up two different wireguard containers; one connected to a VPN as a client. And then one that will run as a server for accessing my home network while away. 

Docker run command:
```
docker run -d \
  --privileged \
  --name=vpn \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/Indianapolis \
  -p 51825:51825/udp \
  -p 8080:8080 \
  -p 6595:6595 \
  -v ~/.config/wireguard:/config \
  -v /lib/modules:/lib/modules \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv6.conf.all.disable_ipv6=0" \
  --restart unless-stopped \
  linuxserver/wireguard
```

wg0.conf file:
```
[Interface]
PrivateKey = private.key
Address = address.here
DNS = 193.138.218.74
PostUp = FORWARDEDPORT=54955; iptables -A INPUT -i wg0 -p udp --dport $FORWARDEDPORT -j ACCEPT; iptables -A INPUT -i wg>PreDown = FORWARDEDPORT=54955; iptables -D INPUT -i wg0 -p udp --dport $FORWARDEDPORT -j ACCEPT; iptables -D INPUT -i w>
[Peer]
PublicKey =public.key.here
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = my.server.ip:51820
```

The above configuration will work but it's still running on port 51820. Does anyone know what I need to do differently?

**Comment by BrodyStone21** [comment]
> Also, you don't need to change the internal port

If I run two seperate docker containers I can't bind them both to 51820 or I get the below error. 

`Error response from daemon: driver failed programming external connectivity on endpoint vpn (a67dc5b7f3e0c87d8ad6ec6cc7c89360c4b2294f98516faf766a1e2b3781e267): Error starting userland proxy: listen udp4 0.0.0.0:51820: bind: address already in use`

**Comment by aptalca** [comment]
as detailed above, no need to bind to 51820 on the host and no need to change the internal port
