### ISSUE TITLE
New setup breaks when a peer has a - in them.

### ISSUE THREAD

**Issue by kristof-mattei** [linuxserver/docker-wireguard#135]
https://github.com/linuxserver/docker-wireguard/blob/8f2588727e807e30bcc4d0228125e64866ed6c06/root/etc/cont-init.d/40-confs#L53

I had `PEERS=iPhone-Kristof` and it failed to start. 

We may need to do a sanitization of the PEERS?

**Comment by aptalca** [comment]
from the readme: `Number of peers to create confs for. Required for server mode. Can also be a list of names: myPC,myPhone,myTablet (alphanumeric only)`

**Comment by kristof-mattei** [comment]
@aptalca sure, but it's part of the same codechange:

https://github.com/linuxserver/docker-wireguard/commit/928363d6944a4d8235d15d38c8cc7470236be3cf#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L179-R186

It's a change that caused my setup to break.

**Comment by aptalca** [comment]
The peer name only supported alphanumeric from the start. The person who PRed the functionality failed to document it properly. You got lucky that it worked before. The PR you linked updated the readme to reflect that. See this issue from before that PR: https://github.com/linuxserver/docker-wireguard/issues/127

**Comment by thomasmerz** [comment]
Well, this explains a lot to my problems today… 🤷🏻‍♂️
