### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by whatdemocracy** [linuxserver/docker-wireguard#140]
---
name: Web UI
about: A web interface to manage our clients

---
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Alternatives Considered

Hi friends.
Wouldn't be awesome having a Web UI to manage all our wireguard clients?
I've testing [this project](https://hub.docker.com/r/weejewel/wg-easy) an I can say that it's very usefull
![imagen](https://user-images.githubusercontent.com/57089805/148344961-1325d18d-f1f7-47c8-b463-eecc06dc1ac3.png)

Anyway, thanks for your hard work.

**Comment by dojo90** [comment]
There are some more UIs available:

- https://github.com/EmbarkStudios/wg-ui
- https://github.com/vx3r/wg-gen-web
- https://github.com/Place1/wg-access-server
- https://github.com/ngoduykhanh/wireguard-ui

**Comment by yllekz** [comment]
Also watching this as I also use wg-easy which has been easier to set up than this container. WireGuard is nice but limiting it to command line only makes it hard to approach. It would be cool if this container could add some way to configure it via a web interface like wg-easy but with more options.

**Comment by aptalca** [comment]
We don't currently have plans to add a gui, which would have to be developed in house as our current system is not compatible with an external option
