### ISSUE TITLE
Container doesn't exit when wg up failed

### ISSUE THREAD

**Issue by ahshum** [linuxserver/docker-wireguard#142]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When wg failed to start, the container should exit.

## Current Behavior

When wg failed to start, the container will sleep infinitely.

## Steps to Reproduce

1. When network is not ready and is down
2. Start a wireguard container in client mode

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

`docker run --network=none linuxserver/wireguard` with config in client mode

## Docker logs

[wg.log](https://github.com/linuxserver/docker-wireguard/files/7877277/wg.log)

**Comment by aptalca** [comment]
Your expectation is incorrect. The container behaves as intended
