### ISSUE TITLE
Container not working after latest update (Raspberry OMV 5)

### ISSUE THREAD

**Issue by RazorDarkAMG** [linuxserver/docker-wireguard#145]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Hello, since the last update with watchtower yesterday, my wireguard container does not work anymore, I also had an update of my Raspberry with OMV before, I think it is related.

Here are my logs on the wireguard container, do you have any idea what it could be?

## Environment
OS: OMV 5
CPU architecture: arm64

## Command used to create docker container : Compose

`version: "2.3"
services:
  wireguard:
    container_name: wireguard
    image: ghcr.io/linuxserver/wireguard:latest
    restart: unless-stopped
    ports:
      - 48573:48573/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SERVERURL=my.service.org
      - SERVERPORT=48573
      - PEERS=PC,TEL,VOITURE
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=192.168.1.0/24
    volumes:
      - /home/pi/docker/wireguard/config:/config
      - /lib/modules:/lib/modules
    labels:
      - com.centurylinklabs.watchtower.enable=true  `

## Docker logs

```
today at 01:38:57[cont-finish.d] executing container finish scripts...
today at 01:38:57[cont-finish.d] done.
today at 01:38:57[s6-finish] waiting for services.
today at 01:38:57[s6-finish] sending all processes the TERM signal.
today at 01:39:00[s6-finish] sending all processes the KILL signal and exiting.
today at 01:39:07[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
today at 01:39:07[s6-init] ensuring user provided files have correct perms...exited 0.
today at 01:39:07[fix-attrs.d] applying ownership & permissions fixes...
today at 01:39:07[fix-attrs.d] done.
today at 01:39:07[cont-init.d] executing container initialization scripts...
today at 01:39:07[cont-init.d] 01-envfile: executing... 
today at 01:39:08[cont-init.d] 01-envfile: exited 0.
today at 01:39:08[cont-init.d] 01-migrations: executing... 
today at 01:39:08[migrations] started
today at 01:39:08[migrations] no migrations found
today at 01:39:08[cont-init.d] 01-migrations: exited 0.
today at 01:39:08[cont-init.d] 02-tamper-check: executing... 
today at 01:39:08[cont-init.d] 02-tamper-check: exited 0.
today at 01:39:08[cont-init.d] 10-adduser: executing... 
today at 01:39:08usermod: no changes
today at 01:39:08
```
```
today at 01:39:08-------------------------------------
today at 01:39:08          _         ()
today at 01:39:08         | |  ___   _    __
today at 01:39:08         | | / __| | |  /  \ 
today at 01:39:08         | | \__ \ | | | () |
today at 01:39:08         |_| |___/ |_|  \__/
today at 01:39:08
today at 01:39:08
today at 01:39:08Brought to you by linuxserver.io
today at 01:39:08-------------------------------------
today at 01:39:08
today at 01:39:08To support the app dev(s) visit:
today at 01:39:08WireGuard: https://www.wireguard.com/donations/
today at 01:39:08
today at 01:39:08To support LSIO projects visit:
today at 01:39:08https://www.linuxserver.io/donate/
today at 01:39:08-------------------------------------
today at 01:39:08GID/UID
today at 01:39:08-------------------------------------
today at 01:39:08
today at 01:39:08User uid:    1000
today at 01:39:08User gid:    1000
today at 01:39:08-------------------------------------
today at 01:39:08
today at 01:39:08[cont-init.d] 10-adduser: exited 0.
today at 01:39:08[cont-init.d] 30-module: executing... 
today at 01:39:08Uname info: Linux 8cb84e953c39 5.10.63-v8+ #1496 SMP PREEMPT Wed Dec 1 15:59:46 GMT 2021 aarch64 aarch64 aarch64 GNU/Linux
today at 01:39:08RTNETLINK answers: Operation not permitted
today at 01:39:08**** The wireguard module is not active, will attempt kernel header install and module compilation. ****
today at 01:39:08**** Kernel headers seem to be present, attempting to build the wireguard module. . . ****
today at 01:39:08**** Building the module ****
```
```
today at 01:39:08make: Entering directory '/app/wireguard-linux-compat/src'
today at 01:39:11  CC [M]  /app/wireguard-linux-compat/src/main.o
today at 01:39:11  CC [M]  /app/wireguard-linux-compat/src/noise.o
today at 01:39:11  CC [M]  /app/wireguard-linux-compat/src/device.o
today at 01:39:11gcc: error: unrecognized command line option ‘-fpatchable-function-entry=2’
today at 01:39:11  CC [M]  /app/wireguard-linux-compat/src/peer.o
today at 01:39:11scripts/Makefile.build:280: recipe for target '/app/wireguard-linux-compat/src/main.o' failed
today at 01:39:11make[2]: *** [/app/wireguard-linux-compat/src/main.o] Error 1
today at 01:39:11make[2]: *** Waiting for unfinished jobs....
today at 01:39:11gcc: error: unrecognized command line option ‘-fpatchable-function-entry=2’
today at 01:39:11scripts/Makefile.build:280: recipe for target '/app/wireguard-linux-compat/src/noise.o' failed
today at 01:39:11make[2]: *** [/app/wireguard-linux-compat/src/noise.o] Error 1
today at 01:39:11gcc: error: unrecognized command line option ‘-fpatchable-function-entry=2’
today at 01:39:11scripts/Makefile.build:280: recipe for target '/app/wireguard-linux-compat/src/device.o' failed
today at 01:39:11make[2]: *** [/app/wireguard-linux-compat/src/device.o] Error 1
today at 01:39:11gcc: error: unrecognized command line option ‘-fpatchable-function-entry=2’
today at 01:39:11scripts/Makefile.build:280: recipe for target '/app/wireguard-linux-compat/src/peer.o' failed
today at 01:39:11make[2]: *** [/app/wireguard-linux-compat/src/peer.o] Error 1
today at 01:39:11Makefile:1825: recipe for target '/app/wireguard-linux-compat/src' failed
today at 01:39:11make[1]: *** [/app/wireguard-linux-compat/src] Error 2
today at 01:39:11Makefile:26: recipe for target 'module' failed
today at 01:39:11make: *** [module] Error 2
today at 01:39:11make: Leaving directory '/app/wireguard-linux-compat/src'
today at 01:39:11make: Entering directory '/app/wireguard-linux-compat/src'
today at 01:39:12cat: /app/wireguard-linux-compat/src/modules.order: No such file or directory
today at 01:39:12  DEPMOD  5.10.63-v8+
today at 01:39:12Warning: modules_install: missing 'System.map' file. Skipping depmod.
today at 01:39:12depmod -b "/" -a 5.10.63-v8+
today at 01:39:17make: Leaving directory '/app/wireguard-linux-compat/src'
today at 01:39:17**** Let's test our new module. ****
today at 01:39:17RTNETLINK answers: Operation not permitted
today at 01:39:17**** The module is not active, review the logs. Sleeping now. . . ****
```

Thank you for your help.

**Comment by aptalca** [comment]
Please wrap the code in 3 backticks. It's near impossible to read

**Comment by RazorDarkAMG** [comment]
ok i'm sorry, i go to edit.

**Comment by aptalca** [comment]
Somethings don't add up. I doubt it ever worked before, because the port mapping is wrong.

Also, Linux kernel 5.10 should have wireguard built in and there should be no need to compile it.

Reboot your device and recreate the container

**Comment by RazorDarkAMG** [comment]
Sorry I forgot to specify I don't use this port but the 51820 I modified it to post here for security but it was not useful.

I didn't try wireguard directly on the machine, I have to say that I prefer to have all my services in docker which simplifies a lot the management of them.

**Comment by angelfor3v3r** [comment]
The latest version of the container doesn't create configs with the environment variable for me and fails to do handshakes. I downgraded to the docker tags from sept 2021 and everything works fine.

**Comment by RazorDarkAMG** [comment]
> The latest version of the container doesn't create configs with the environment variable for me and fails to do handshakes. I downgraded to the docker tags from sept 2021 and everything works fine. Not sure if related but a very weird regression for me.

I'm also going to switch back to the old version I think, I couldn't fix the problem unfortunately, thanks for the tip!

**Comment by j0nnymoe** [comment]
You're missing 
```yaml
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
```
Also like @aptalca said, wireguard doesn't seem to be enabled in your kernel, so thats why it's trying to compile but you've also not got the `/src` mounted in your volumes so it's unable to compile the modules.

**Comment by angelfor3v3r** [comment]
I personally have both of those and it doesn't change anything for me. Downgrading to an old version fixed my issues, can the original poster of this issue test if configs are properly being created? Only the first one is created for me from the ENV variable.

**Comment by angelfor3v3r** [comment]
Right. I’ll just make a seperate issue since it may not fall in line with this one. Thanks!

**Comment by FedX-sudo** [comment]
Hi, just wanted to pipe in, I am seeing this same issue on Podman running on Fedora 35 in both root and rootless. I also tested it on NixOS 22.05 as a sanity check, but to my surprise I do not get this error whatsoever. I was using the compose file for Wireguard in the Awesome Compose repo, but am seeing the issue on `podman run` as well. I have podman version 3.4.4 on both the Fedora and the NixOS box. I have no clue what this issue is as both Fedora and NixOS are kernel 5.16 as well.

**Comment by aptalca** [comment]
Closing.

If you want to report issues, please open a new one and fill out the full template accurately.
