### ISSUE TITLE
add option to change the MTU of wg interface

### ISSUE THREAD

**Issue by shenjiangqiu** [linuxserver/docker-wireguard#158]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Add environment option to set the interface MTU
------------------------------
The default MTU is 1420, while it will cause some problems when the MTU of the internet provider is less than 1500. the data will be dropped.
## Desired Behavior

add an option MTU to control the MTU of the interface

**Comment by aptalca** [comment]
Can't you just modify it on the client conf?

**Comment by aptalca** [comment]
You can edit `/config/templates/server.conf` and add it there

**Comment by Taknok** [comment]
Yes, but an option to avoid extra steps would be nice. Currently:
1. Configuring
2. Starting container
3. Stopping container
4. Editing server.conf to add postup and postdown
5. Restarting

would become:
1. Configuring
2. Starting container

**Comment by aptalca** [comment]
This image has too many env vars as it is. I don't plan on adding any more vars unless absolutely necessary (def not for duplicate functionality).

If you'd like to add it, you can customize the image yourselves: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
