### ISSUE TITLE
Support for ListenPort in env Docker

### ISSUE THREAD

**Issue by mathe0esob** [linuxserver/docker-wireguard#161]
Hi mates, I would like to ask, about Listenport for Docker, because I wanna use it 2 Wireguard on Docker in the same host, but I have a problem with Listenport for wg0.cfg and peer. It is possible to add field in templates > peer + server.conf, variable ${LISTENPORT}, or ListenPort = ${SERVERPORT} ??. thanks in advance for a help.

Example:
wireguard1 - 51820/udp,
wireguard2 - 51821/udp,
etc.

```
cat config/templates/server.conf 
[Interface]
Address = ${INTERFACE}.1
**ListenPort = 51820**
PrivateKey = $(cat /config/server/privatekey-server)
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
```

```
cat config/templates/peer.conf 
[Interface]
Address = ${CLIENT_IP}
PrivateKey = $(cat /config/${PEER_ID}/privatekey-${PEER_ID})
**ListenPort = 51820**
DNS = ${PEERDNS}

[Peer]
PublicKey = $(cat /config/server/publickey-server)
Endpoint = ${SERVERURL}:${SERVERPORT}
AllowedIPs = ${ALLOWEDIPS}
```

**Comment by aptalca** [comment]
> if u change the docker port / forward, it doesn't matter and doesn't work

?? It works if you follow the readme.

After you scan the QR code, you can still edit it. It's not a permanent thing.
The listen port in the peer conf has nothing to do with the server port, which is controlled by the `SERVER_PORT` env var and is defined in the peer conf's `Endpoint` section.
The listen port in the wg0.conf needs to be 51820 if you're following the sample compose yaml.

**Comment by mathe0esob** [comment]
thx for a help, close issue :)
