### ISSUE TITLE
ListenPort within wg0.conf not set automatically during container creation

### ISSUE THREAD

**Issue by BrodyStone21** [linuxserver/docker-wireguard#163]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
ListenPort within wg0.conf should be set automatically during container creation. 

## Current Behavior
ListenPort within wg0.conf is not set automatically during container creation. 

## Steps to Reproduce
1. Create wireguard container using configuration below. 
2. `nano wg0.conf`
3. Look at `ListenPort = 51820`

## Command used to create docker container (run/create/compose/screenshot)
```
docker run -d \
  --name=wireguard \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  -p 51825:51825/udp \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/Indianapolis \
  -e SERVERPORT=51825 `#optional` \
  -e PEERS=1 `#optional` \
  -e PEERDNS=auto `#optional` \
  -e INTERNAL_SUBNET=10.13.13.0 `#optional` \
  -e LOG_CONFS=true `#optional` \
  -v /mnt/WD_White/Server_Stuff/wireguard:/config \
  -v /lib/modules:/lib/modules \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --restart unless-stopped \
  linuxserver/wireguard

```

If you create a container and set the `-e SERVERPORT = 51825` value and open those ports using `-p 51825:51825/udp`, the container will not work by default. You have to change the ListenPort value within wg0.conf to 51825. I spent a few hours trying to figure out why this wasn't working before trying to change the value inside of wg0.conf. 

I'm not sure if this is intended or not, but when I changed `SERVERPORT`, I expected that to change the ListenPort within wg0.conf.  

This might be an intended feature, I don't know. If so, let me know and I'll close this issue.

**Comment by aptalca** [comment]
`-e SERVERPORT=51820 | External port for docker host. Used in server mode.`

From the readme. Emphasis on `external`
