### ISSUE TITLE
Add TCP MSS clamp option

### ISSUE THREAD

**Issue by Taknok** [linuxserver/docker-wireguard#166]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Current Behavior
When adding another link with a greater MTU after the docker container, the TLS negotiation will fail for some sites, https://linuxserver.io for example ;) 

### Why
This happens when TLS response is bigger than 1500 and TLS client thinks PMTU is 1500. In the TLS negotiation, SSL server sets the `Do Not fragment` flag (normal behavior) on the server response, so docker drop because next MTU is 1480 and reply an ICMP `Fragmentation needed`, but the TLS server resends same packet with same size and again. (infinite loop until tcp fail after 2min). This can be observed by setting a Wireshark on the host, monitoring the docker-bridge interface.

#### Architecture
```
internet
    ^
    |
    v
   box
    ^ 192.168.1.1/24
    | 192.168.1.0/24
    v eth0: 192.168.1.2/24 * MTU 1500
physical server running docker (linux)
    ^
    |
    v br-docker * MTU 1420
docker-wg-server <-> phone (2)
    ^ wg0: 192.168.3./24 * MTU 1420
    | 192.168.3.0/24
    v wg0: 192.168.3.3/24 * MTU 1420
  wp-ap with rasp-ap (1)
    ^ wlan0: 192.168.100.1/24 * MTU 1500
    | 192.168.100.0/24
    v wlan0: 192.168.100.2/24 * MTU 1500
Personnal Computer (3)
```
The postUp and down rules are added in wg0.conf on wg-ap (1) in order to route packets:
```
iptables -A FORWARD -i wlan0 -o wg0 -j ACCEPT
iptables -A FORWARD -i wg0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -t nat -A  POSTROUTING -o wg0 -j MASQUERADE
```

Direct clients of the docker-wireguard are working flawlessly, because the TLS client knows the minimal MTU since it is the MTU of the interface.
So this `curl` command is working on hone(2) or wg-ap (1):
```bash
curl -v -tls-max https://linuxserverio/
```
But when executed on PC (3), the TLS negotiation fail (loop of TLS Server Response can be seen with Wireshark on docker host). Output:
```
Trying 139.59.198.96:443...
[...]
TLSv1.2 (OUT), TLS handshake, Client hello (1):
[timeout after 2min of tcp]
```

Strangely the PMTUD always returns the MTU of the direct interface and not working as expected, so on PC (3) (tested with both Windows 10 PC and debian PC) its returns 1500.

### Solution
Add TCP MSS Clamp on docker-wireguard
```bash
iptables -I FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
```

## Desired Behavior
TLS negotiation succeed and communication is established even for links after wireguard clients. This can be done by automatically adding this rule in the docker or setting an option to enable MSS clamping.

## Alternatives Considered

Adding a `PostUp` and `PostDown` option to add command in config file at generation. This would be more flexible, but it is a little more complicated for "standard" users than an option enabled by default (or just a switch).

**Comment by aptalca** [comment]
Isn't this something that needs to be done on the client only? And only when the client is acting as an ap?

In that case, you already have to modify the PostUp/PostDown in the client config to set it up properly as an ap (for routing). That's not something we set up for you in the confs. Similarly, clamping is also something you need to do as part of setting it up as an ap.

Therefore I believe that's beyond the scope of what this image auto configures for the users. Plus, the peer confs can be modified by editing the templates in the config folder.

Thanks for documenting it here, though. I'm sure other folks will stumble upon it via search.
