### ISSUE TITLE
Change default port wireguard in docker-compose file

### ISSUE THREAD

**Issue by ddd015** [linuxserver/docker-wireguard#175]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When i change default port wireguard in docker-compose file, config file server (wg0.conf) formed with default port, my change do not apply. I need manual change port in wg0.conf and peer#.conf files
## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by aptalca** [comment]
We do not provide an option to change the wireguard listen port. There is also no reason for you to change it.
