### ISSUE TITLE
Deleting peer folder and recreating the container does not recreate peer folder or configs

### ISSUE THREAD

**Issue by arjones85** [linuxserver/docker-wireguard#177]
As the subject says. I deleted my "peer5" folder with hopes the container would regenerate the peer configs. docker-compose down, and docker-compose up --force-recreate and the "peer5" folder is still missing.

Am I doing this wrong? I am following the documentation but it doesn't seem to work.

**Comment by andybe** [comment]
> As the subject says. I deleted my "peer5" folder with hopes the container would regenerate the peer configs. docker-compose down, and docker-compose up --force-recreate and the "peer5" folder is still missing.
> 
> Am I doing this wrong? I am following the documentation but it doesn't seem to work.

Did you write the configs to the filesystem or volume. Then please delete the volume / local files also.

**Comment by drizuid** [comment]
bug template not filled out, not enough info to proceed
