### ISSUE TITLE
Fails to start under Ubuntu 18.04.6

### ISSUE THREAD

**Issue by rmichelena** [linuxserver/docker-wireguard#178]
Container builds ok but the service does not start, the container console log only shows:

s6-overlay-suexec: fatal: can only run as pid 1

Base os is Ubuntu 18.04.6, system is a VPS x86_64, have various diverse docker containers running flawlessly (mail server, torrent downloader, media server, etc.)

Used the pull and run commands from dockerhub, just modified the server URL, Timezone and config directory; later also tried removing the internal subnet and allowed ips lines.

**Comment by andybe** [comment]
> Container builds ok but the service does not start, the container console log only shows:
> 
> s6-overlay-suexec: fatal: can only run as pid 1
> 
> Base os is Ubuntu 18.04.6, system is a VPS x86_64, have various diverse docker containers running flawlessly (mail server, torrent downloader, media server, etc.)
> 
> Used the pull and run commands from dockerhub, just modified the server URL, Timezone and config directory; later also tried removing the internal subnet and allowed ips lines.

Need more explanation. Looks like a snap problem.

**Comment by drizuid** [comment]
bug template not filled out. not enough information to proceed

**Comment by IcyMidnight** [comment]
Been running into this for a few months and tonight I stumbled upon a fix for this. My docker-compose.yaml had the init option enabled -- I must have copy-pasted that as part of old docs, whatever tutorial I was following, or maybe accidentally from some other config I had. For me removing this line from my config fixed it:
`init: true`

**Comment by drizuid** [comment]
Thank you for sharing, we have seen this a few times previously, it's made fairly obvious with full logs. We are glad you got it sorted
