### ISSUE TITLE
PostUp/PostDown as environment variable

### ISSUE THREAD

**Issue by hqas** [linuxserver/docker-wireguard#180]
---
name: Feature request
about: Suggest an idea for this project

---
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
## Desired Behavior
New environment variables to set custom PostUp/PostDown rules

## Current Behavior
Custom rules can be set by editing wg0.conf. But those get overwritten when e.g adding a new peer. Therefore they have to be rewritten whenever the container gets rebuilt which can be quite often

## Alternatives Considered
You can also run a custom script that replaces the hardcoded rules and restart the container to apply the new rules. But I feel like environment variables as e.g used in wg-easy could be quite handy. I believe there are a lot of usecases for custom rules and it would help the versatility of this container a lot. Happy to hear what you think about this

**Comment by aptalca** [comment]
There are templates for both the server and the peer confs in the config folder. Edit those and you don't have to worry about custom scripts or variables

**Comment by hqas** [comment]
Ah awesome I found it. Thank you very much for the fast response
