### ISSUE TITLE
ReOpen: Set template ListenPort based on SERVERPORT environment variable #52

### ISSUE THREAD

**Issue by andybe** [linuxserver/docker-wireguard#181]
The patches from #52 in the current version are gone.

While I was working on my Kubernetes DualStack variant I run in the SERVERPORT Issue:

To fix this I map the correct file into the container:

mountPath:  /config/templates/server.conf (root/defaults/server.conf)

```
server-conf: |
    [Interface]
    Address = ${INTERFACE}.1
    ListenPort = ${SERVERPORT}                                   <------
    PrivateKey = $(cat /config/server/privatekey-server)
    PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
    PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE  
   ```
mountPath:  /config/templates/peer.conf (root/defaults/peer.conf)
```
  peer-conf: |
    [Interface]
    Address = ${CLIENT_IP}
    PrivateKey = $(cat /config/${PEER_ID}/privatekey-${PEER_ID})
    ListenPort = ${SERVERPORT}                                                  <------
    DNS = ${PEERDNS}

    [Peer]
    PublicKey = $(cat /config/server/publickey-server)
    PresharedKey = $(cat /config/${PEER_ID}/presharedkey-${PEER_ID})
    Endpoint = ${SERVERURL}:${SERVERPORT}
    AllowedIPs = ${ALLOWEDIPS}
```
   And now it runs as it shoud.

**Comment by aptalca** [comment]
#52 was never merged

**Comment by aptalca** [comment]
I've explained the difference between the serverport var and the server listen port way too many times in this repo's issues.

**Comment by andybe** [comment]
> #52 was never merged
Hm. Ok.
Yes ports can mapped through docker / kubernets (pods), but then the generated client configs  include  the wrong port.
