### ISSUE TITLE
ReOpen: Set template ListenPort based on SERVERPORT environment variable #52 #181

### ISSUE THREAD

**Issue by andybe** [linuxserver/docker-wireguard#182]
Sorry for reopen again. 

I can't see any problem to configure the UDP Port in a 1:1 transfer from out to the inner.

It run's here:

OUT -> BRIDGE -> CALIO -> Kubernetes (Balancer) -> Pod.

If the User should change the outside port please:

Write the serverport into client configs.

or call it "client port".

I dont't mind.

**Comment by aptalca** [comment]
Dude, please stop opening new issues about this. I'm really tired of explaining it over and over again.

`SERVERPORT` var is what gets written to peer configs. That's it. Set it to whatever external port your server is listening on, whatever port mapping or forwarding you did on your server, router, whatever.

**Comment by andybe** [comment]
> Dude, please stop opening new issues about this. I'm really tired of explaining it over and over again.
> 
> `SERVERPORT` var is what gets written to peer configs. That's it. Set it to whatever external port your server is listening on, whatever port mapping or forwarding you did on your server, router, whatever.

@aptalca 
First:  It does not work for me: "SERVERPORT` var is what gets written to peer configs"
Second: Something else fails ....

Im not Dude ... admin and programmer for years (over 35 years).

I will take a deeper look into it ...
