### ISSUE TITLE
Wireguard client stuck in a loop

### ISSUE THREAD

**Issue by Berrus** [linuxserver/docker-wireguard#185]
Firstly i would like to know “Drop your client conf into the config folder as /config/wg0.conf and start the container”. How dow want me to rename file to /config/wg0.conf or just wg0.conf and drop in config folder?

Second it is stuck in a loop throwing error
Warning: `/config/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.42.47.73/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
sysctl: setting key "net.ipv4.conf.all.src_valid_mark", ignoring: Read-only file system
[#] iptables-restore -n

**Comment by drizuid** [comment]
OP did not fill out bug template, not enough info to proceed.
