### ISSUE TITLE
image fails to compile under EKS

### ISSUE THREAD

**Issue by brdelphus** [linuxserver/docker-wireguard#188]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Image doesn't work on aws EKS

## Expected Behavior

Compile and load wireguard module ?!?
## Current Behavior

 bash  30-module 
Uname info: Linux wireguard-client 5.4.196-108.356.amzn2.x86_64 #1 SMP Thu May 26 12:49:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Error: Unknown device type.
**** The wireguard module is not active, will attempt kernel header install and module compilation. If you believe that your kernel should have wireguard support already, make sure that it is activated via modprobe! ****
**** Attempting kernel header install ****
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Fetched 228 kB in 2s (107 kB/s)
Reading package lists... Done
**** No kernel headers found in the Ubuntu or Debian repos!! Will try the headers from host (if mapped), may or may not work ****
**** Kernel headers don't seem to be available in Ubuntu, Debian and Raspbian repos, or shared from the host; therefore can't compile the module. Sleeping now. . . ****

## Steps to Reproduce

1. start eks cluster
2. create pod that loads linuxserver image
3. try getting it to compile
4. ...??...

## Environment
**OS:** amazon linux
**CPU architecture:** x86_64

**How docker service was installed:**
it's a EKS Kubernetes cluster

**Comment by Roxedus** [comment]
We dont support Amazon Linux. We dont have, or plan to build the infrastructure to test against it.
