### ISSUE TITLE
Recent updates breaks WireGuard docker on Synology DSM7

### ISSUE THREAD

**Issue by MJVerhulst** [linuxserver/docker-wireguard#191]
---
name: Bug report
about: Recent updates breaks WireGuard docker on Synology DSM7

---
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

After the most recent update ([1.0.20210914](https://hub.docker.com/layers/linuxserver/wireguard/1.0.20210914/images/sha256-76efaa02c6699f50d094f60864913f9a40957b64e4887fbb1926c3c880a6a19f?context=explore)), Wireguard stopped working on my Synology DS918+. Client logins do no longer show up running wg show, and there is no connectivity on the client. 

------------------------------

## Expected Behavior
Working connectivity

## Current Behavior
No connectivity at client, clients do not show up using `wg show`
These lines in the logs seem suspicious to me. 
```[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j                                                            MASQUERADE
iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument

[#] ip link delete dev wg0
```

## Steps to Reproduce
1. Updated to [1.0.20210914]

## Environment
**OS:** Synology DS918+ running DSM 7.1-42661 Update 4
**CPU architecture:** x86_64
**How docker service was installed:**
Using docker-compose, after installing the Wireguard Synology package separately 

## Command used to create docker container (run/create/compose/screenshot)
```---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Amsterdam
      - SERVERURL=******
      - SERVERPORT=51338 #optional
      - PEERS=6  #optional
      - PEERDNS=192.168.1.202 #optional
      #- INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=192.168.1.0/24,192.168.10.0/24,10.13.13.0/24,172.17.0.1
      - LOG_CONFS=true 
    volumes:
      - /volume1/docker/wireguard:/config
      - /lib/modules:/lib/modules
      #- /usr/src:/usr/src:ro #kernel_headers?
    ports:
      - 51338:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    extra_hosts:
      - "pulstar:172.17.0.1"
      - "host.docker.internal:172.17.0.1"
    restart: unless-stopped
   ```
## Docker logs
```
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1026
User gid:    101
-------------------------------------

Uname info: Linux 89c2c6132c9d 4.4.180+ #42661 SMP Mon Jun 27 15:05:48 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** Server mode is selected ****
**** External server address is set to ***** ****
**** External server port is set to 51338. Make sure that port is properly forwarded to port 51820 inside this container                                                            ****
**** Internal subnet is set to 10.13.13.0 ****
**** AllowedIPs for peers 192.168.1.0/24,192.168.10.0/24,10.13.13.0/24,172.17.0.1 ****
**** Peer DNS servers will be set to 192.168.1.202 ****
**** Server mode is selected ****
**** No changes to parameters. Existing configs are used. ****
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Warning: `/config/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.13.1 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] ip -4 route add 10.13.13.7/32 dev wg0
[#] ip -4 route add 10.13.13.6/32 dev wg0
[#] ip -4 route add 10.13.13.5/32 dev wg0
[#] ip -4 route add 10.13.13.4/32 dev wg0
[#] ip -4 route add 10.13.13.3/32 dev wg0
[#] ip -4 route add 10.13.13.2/32 dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j                                                            MASQUERADE
iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument

[#] ip link delete dev wg0
.:53
CoreDNS-1.10.0
linux/amd64, go1.19.1, 596a9f9
```

**Comment by argymeg** [comment]
+1 for this bug. Getting the exact same error in a different environment:

OS: LibreElec 10.0.2
CPU architecture: aarch64
How docker service was installed: Using docker-compose

Downgrading to v1.0.20210914-ls81 fixes the issue.

**Comment by Akirainblack** [comment]
I can confirm this issue and as argymeg said after downgrading to previous version it works again. Thanks to argymeg for the version string.

**Comment by aptalca** [comment]
`I can confirm` is not helpful by itself.

Looking at the installed packages, the only relevant change during the rebase seems to be iptables getting updated from 1.8.4 to 1.8.7
https://github.com/linuxserver/docker-wireguard/commit/51f6bda1052c41a32ca9e1fdae14e3deb12e8b5c

Perhaps if the OS iptables is an older version, it might not support a call that the new version inside the container is trying to make?

What's the iptables version on libreelec?

**Comment by aptalca** [comment]
In the meantime, can you test this alpine based image and see if that works?
`lspipepr/wireguard:1.0.20210914-PR-192`

**Comment by argymeg** [comment]
iptables version doesn't seem to be the problem, at least not in this sense:
```
LibreELEC:~ # iptables --version
iptables v1.8.7 (legacy)
```

And yes, the alpine image works fine for me.

**Comment by aptalca** [comment]
Thanks

I'm testing on focal, which has iptables 1.8.4 and defaults to legacy. The new image works fine. We're spinning up libreelec to test. .

**Comment by Akirainblack** [comment]
Sorry, I am fully aware it isn't helpful by itself, I'm on my mobile, boarding a plane shortly, once I can get to a computer I am planning to add more information, I was simply confirming it wasn't end user error. Will confirm what the DS918+ on 7.1 has in the way of iptables once I reach my destination and have(hopefully) an Internet connectivity.

**Comment by aptalca** [comment]
just a heads up, even though nftables in container, legacy on host works fine on focal, it doesn't on some hosts (tested libreelec and confirmed). So we'll update the image to use legacy inside the container. But we're also adding some other improvements so it may be a few days before it's out.

Thanks for the heads up and testing help.

**Comment by drizuid** [comment]
We have confirmed that the issue on *elec is related to nftables (due to a suspected kernel issue in *elec) and have a plan to fix that. We assume our change will also fix dsm (due to a similar kernel issue) but we do not support dsm and have no way to test, so we will rely on others to test the change for us.   We have tested the change on libreelec, debian, ubuntu focal, ubuntu jammy, and alpine. 

I've harassed Aptalca to push our change prior to the larger set of improvements, so it should be forthcoming soon :)

**Comment by argymeg** [comment]
Brilliant, works like a charm again. Cheers for a spectacularly speedy fix.

**Comment by reconman** [comment]
@argymeg How did you get this running on Synology 7.1? I installed wireguard via https://github.com/vegardit/synology-wireguard but now the kernel module iptable_raw is still missing.

**Comment by drizuid** [comment]
> @argymeg How did you get this running on Synology 7.1? I installed wireguard via https://github.com/vegardit/synology-wireguard but now the kernel module iptable_raw is still missing.

well.. for starters he's using our container and not whatever you linked.. perhaps start there :)

**Comment by reconman** [comment]
@drizuid No, what I linked is for installing the wireguard.ko kernel in Synology.

I **am** using your docker container with the `latest` tag.

**Comment by argymeg** [comment]
@reconman I have only used this on LibreELEC, not DSM, so I can't help specifically. However according to my setup notes I did have an issue with `iptable_raw` missing, and the reason it was needed was for setting `AllowedIPs = 0.0.0.0/0`. If you are using that, try changing it and see if it helps - anything else, I can't really help with.

**Comment by reconman** [comment]
Here's my log if it helps in any way:
<details>

```
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║      
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
Uname info: Linux 9f040eccbbcb 4.4.180+ #42962 SMP Tue Jan 31 23:19:16 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** As the wireguard module is already active you can remove the SYS_MODULE capability from your container run/compose. ****
**** Client mode selected. ****
[custom-init] No custom files found, skipping...
**** Disabling CoreDNS ****
Warning: `/config/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.106.237/24 dev wg0
[#] ip link set mtu 1390 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
iptables-restore v1.8.7 (legacy): iptables-restore: unable to initialize table 'raw'
Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
[#] resolvconf -d wg0 -f
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
s6-rc: warning: unable to start service svc-wireguard: command exited 2
```

</details>

**Comment by reconman** [comment]
@argymeg What do you mean exactly with "changing it". I removed it, now I can't connect to any address inside the container.

Here's my current wg0.conf:
```
# TorGuard WireGuard Config
[Interface]
PrivateKey = removed
ListenPort = 52160
MTU = 1390
DNS = 1.1.1.1
Address = 10.13.106.237/24
PostUp = ip route add 192.168.0.0/24 via 172.20.0.1;
PreDown = ip route delete 192.168.0.0/24;
[Peer]
PublicKey = ydMhcNakO+DfbCOd28jBr1PlouUZz5tscwkTujQUiSw=
# AllowedIPs = 0.0.0.0/0
Endpoint = 37.120.155.10:1443
PersistentKeepalive = 25
```

My local network is 192.168.0.x, 172.20.0.1 is the ip address of the docker bridge the wireguard container is using.

**Comment by serious-angel** [comment]
Dear Developers, Artists,

Thank you for the marvel you do!

---

The legacy was added: 06f2db64c129be4d7fdf33e2ea985faa35329d52
The legacy was removed: 9d4ab33e3b9946d8478b38ebb8971cfb06e58c86

Yet, on up-to-date Synology NAS DSM7.2 the following Docker Compose fails with an error:
```
[#] wg setconf wg-test /dev/fd/63
[#] ip -4 address add 10.8.0.42/24 dev wg-test
[#] ip link set mtu 1420 up dev wg-test
[#] resolvconf -a wg-test -m 0 -x
[#] wg set wg-test fwmark 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] ip -4 route add 0.0.0.0/0 dev wg-test table 51820
[#] nft -f /dev/fd/63
netlink: Error: cache initialization failed: Invalid argument
[#] resolvconf -d wg-test -f
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg-test
**** Tunnel /config/wg_confs/wg-test.conf failed, will stop all others! ****
**** All tunnels are now down. Please fix the tunnel config /config/wg_confs/wg-test.conf and restart the container ****
```

Is it still anyhow possible to tell it use IPTables instead, nowadays?

---

Best and kind regards

**Comment by aptalca** [comment]
We added the legacy shim (basically forced everyone on legacy) to give distros and platforms extra time to update/migrate. We waited three and a half years. That's a long time. Syno never updated, that's on them.

¯\_(ツ)_/¯

Some people expressed interest in creating a mod for the shim. Until then you can stay on an older image with the shim.

**Comment by serious-angel** [comment]
> Some people expressed interest in creating a mod for the shim. Until then you can stay on an older image with the shim.

@aptalca , thank you for the response! I have absolutely no freaking idea why Synology just obliterates and forcefully ignores WireGuard and modern NetFilter, framing everyone who is dependent on networks with many devices to be responsible for, when even MikroTik has it built-in nowadays, and Android phones I have recently used of 5 years old (Xiaomi 10 T Pro).

So many people got involved to do Synology's job: <https://www.blackvoid.club/wireguard-spk-for-your-synology-nas/>

Regardless... may I ask what is the image? Do you mean the tag `:legacy`?

**Comment by reconman** [comment]
@serious-angel I solved my problem by switching to https://github.com/qdm12/gluetun

From what I can remember, there were some issues with wireguard at some point but those might have been fixed already.

Running gluetun with wireguard on QNAP right now.
