### ISSUE TITLE
PersistentKeepalive template for Peers on the server config file (wg0.conf)

### ISSUE THREAD

**Issue by szotsaki** [linuxserver/docker-wireguard#207]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Server is behind NAT and DDNS. In this case it's a good practice to set `PersistentKeepalive` to occasionally send a packet to the client which, in turn, can refresh its Endpoint IP address to the server (since the client doesn't do periodic DNS resolution on its own).

## Current Behavior

Currently, the generated `[Peer]` section of `wg0.conf` looks like this:

```
[Peer]                                                                                                                                                                                         
# peer_X                                                                                                                                                                            
PublicKey = [...]
PresharedKey = [...]
AllowedIPs = 10.13.13.X/32                                                                                                                                                                     
```

It'd be nice if I could assign a line, `PersistentKeepalive = 25`, to the end of the config section from a template.

## Alternatives Considered

Manually entering `PersistentKeepalive = 25`. It will be discarded when the container regenerates `wg0`. It's also against the current mindset that everything comes from either templates or from env. variables.

**Comment by nevarsin** [comment]
Wouldn't a peer.conf template customization make up for this?

**Comment by jrmagers** [comment]
I added `PersistentKeepalive = 25` to `templates/peer.conf`:

```
[Peer]
PublicKey = $(cat /config/server/publickey-server)
PresharedKey = $(cat /config/${PEER_ID}/presharedkey-${PEER_ID})
Endpoint = ${SERVERURL}:${SERVERPORT}
AllowedIPs = ${ALLOWEDIPS}
PersistentKeepalive = 25
```

And then rebuilt the wireguard container: 

`sudo docker-compose up -d --no-deps --build wireguard`

Unfortunately, that didn't seem to add `PersistentKeepalive = 25` to each peer in `wg0.conf`. Perhaps I didn't properly rebuild the containier?

**Comment by aptalca** [comment]
Unfortunately that's not currently supported as the other section of wg0.conf is auto generated but does not use a template. You'd need to customize the container to edit the init script that generated wg0.conf
https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
