### ISSUE TITLE
Add details about non-mobile clients connection

### ISSUE THREAD

**Issue by tigerblue77** [linuxserver/docker-wireguard#216]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Following #215, I think that non-mobile clients connection to the WireGuard VPN should be more detailed :
- in the Docker container logs, just like it prints the QR code for mobile devices, it should give hints for other devices :)
- in the documentation, with a paragraph explaining :
> To connect Windows clients, copy the configuration from `/path/to/appdata/config`" and add it to WireGuard client

So that users -like me- don't lose time finding clients configurations.

## Current Behavior

`-v /path/to/appdata/config:/config` docker run's parameter is not well detailed and nothing is printed in Docker logs to connect devices which doesn't accept QR codes.

## Alternatives Considered

No alternative.

**Comment by tigerblue77** [comment]
Any news ? :)

**Comment by aptalca** [comment]
I think the documentation is clear enough as it is. The config folder contains all persistent files and data and it's referenced throughout the readme.

**Comment by aptalca** [comment]
The readme already states:
```
The peer/client config qr codes will be output in the docker log. They will also be saved in text and png format under /config/peerX in case PEERS is a variable and an integer or /config/peer_X in case a list of names was provided instead of an integer.
```

**Comment by tigerblue77** [comment]
Hello @aptalca, my bad, I missed this phrase when read initially ! Thanks.
