### ISSUE TITLE
[FEAT] auto-restart wg-quick when custom wg0.conf is changed

### ISSUE THREAD

**Issue by bitdruid** [linuxserver/docker-wireguard#231]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

optional applying new wg0.conf while the container is running.

watch wg0.conf for changes and trigger a `wg-quick down / up` or at least do a `wg syncconf wg0`

### Reason for change

if you set env PEER=0 for the container, you can use your own wg0

there are many projects for very comfortable wireguard web-uis. changes in the wg0 configuration of the wireguard server or added clients are usually written from the ui to the wg0, but only registered when the container is manually restarted.

### Proposed code change

unfortunately, i don't know how the wireguard container handles wg-quick. by using systemd services or inotifyd / inotifywait, changes in wg0.conf would be easy to track and trigger the required wg-quick down / up.

**Comment by aptalca** [comment]
This is a good candidate for a mod
https://github.com/linuxserver/docker-mods

**Comment by rbnbr** [comment]
I would second this proposal of a feature.
Specifically I had in mind that you could use a healthcheck service to replace the configuration file with a new one if a failure was detected. So to say, use it as a failover possibility.

Having a bunch of configuration files in a separate folder and the container will choose the next one on failure of the current one.

I'd be happy to look into that and try to implement it as docker-mod. However, it would be nice if someone could point me into the right direction first, and or proof-read my approach if it should come to that.

If there are better options to implement a failover system for those containers please let me know.

**Comment by johannbrink** [comment]
There is already a systemd based example here: https://hub.docker.com/r/ngoduykhanh/wireguard-ui
Would be nice to have that incorporated into this container image.

**Comment by johannbrink** [comment]
bump
