### ISSUE TITLE
Client handshake / internet connection fails with extensive AllowedIPs list

### ISSUE THREAD

**Issue by StrikeAgainst** [linuxserver/docker-wireguard#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've set up a client container for other containers to connect through it with my VPN provider (Mullvad), configuring it by [your tutorial](https://www.linuxserver.io/blog/routing-docker-host-and-container-traffic-through-wireguard), using the routing table method for individual containers. My goal among others is to have my Pihole container run its traffic through the tunnel, so I can still browse my local network domains while avoiding DNS leaks. To have both my local (`192.168.0.0/16`) and the docker (`172.16.0.0/12`) range excluded from the tunnel, I used the [tool from Pro Custodibus](https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/) to calculate the complementary IP ranges to use in my Wireguard config.

Once I spun up the container, a simple `ping 8.8.8.8` inside of it failed to build up any connection though. When I set the allowed IPs to tunnel all traffic and restart the container, it works normally like it should.

I tried a bunch of different masking combinations, even trying to exclude the ranges for local network only first, then docker network only second, which rules out that any critical IP address is blocked from being tunneled.

`wg show` prints this:

	interface: wg0
	  public key: xxxx
	  private key: (hidden)
	  listening port: 38607

	peer: xxxx
	  endpoint: 146.70.117.162:51820
	  allowed ips: 0.0.0.0/1, 128.0.0.0/2, 192.0.0.0/9, 192.128.0.0/11, 192.160.0.0/13, 192.169.0.0/16, 192.170.0.0/15, 192.172.0.0/14, 192.176.0.0/12, 192.192.0.0/10, 193.0.0.0/8, 194.0.0.0/7, 196.0.0.0/6, 200.0.0.0/5, 208.0.0.0/4, 224.0.0.0/3
	  transfer: 0 B received, 27.89 KiB sent

### Expected Behavior

I expected the client to build up a connection to the internet no matter how convoluted the `AllowedIPs` list is, provided that no critical addresses are being filtered, which does not seem to be the problem here.

### Steps To Reproduce

The Wireguard configuration that fails looks like this:

	[Interface]
	PrivateKey = xxxx
	Address = 10.65.237.90/32
	DNS = 172.23.0.53
	PostUp = iptables -t nat -A POSTROUTING -o wg+ -j MASQUERADE
	PreDown = iptables -t nat -D POSTROUTING -o wg+ -j MASQUERADE

	[Peer]
	PublicKey = xxxx
	AllowedIPs = 0.0.0.0/1, 128.0.0.0/3, 160.0.0.0/5, 168.0.0.0/6, 172.0.0.0/12, 172.32.0.0/11, 172.64.0.0/10, 172.128.0.0/9, 173.0.0.0/8, 174.0.0.0/7, 176.0.0.0/4, 192.0.0.0/9, 192.128.0.0/11, 192.160.0.0/13, 192.169.0.0/16, 192.170.0.0/15, 192.172.0.0/14, 192.176.0.0/12, 192.192.0.0/10, 193.0.0.0/8, 194.0.0.0/7, 196.0.0.0/6, 200.0.0.0/5, 208.0.0.0/4, 224.0.0.0/3
	Endpoint = 146.70.117.162:51820

For the working configuration, I simply changed `AllowedIPs` to `0.0.0.0/0`.

### Environment

```markdown
- OS: openmediavault 6 (Debian 11.6)
- How docker service was installed: omv-extras
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3"

networks:
  nas2:
	external: true

services:
  wireguard:
	image: lscr.io/linuxserver/wireguard:latest
	container_name: wireguard-client
	cap_add:
	  - NET_ADMIN
	  - SYS_MODULE
	environment:
	  TZ: Europe/Berlin 
	volumes:
	  - /disk/web/config/wireguard/client:/config
	networks:
	  nas2:
		ipv4_address: 172.23.0.52
	sysctls:
	  net.ipv4.conf.all.src_valid_mark: 1
	  net.ipv4.ip_forward: 1
	dns:
	  - 172.23.0.53 # pihole container
	restart: always
```

### Container logs

```bash
[migrations] started
	[migrations] no migrations found
	usermod: no changes

	-------------------------------------
			  _         ()
			 | |  ___   _    __
			 | | / __| | |  /  \
			 | | \__ \ | | | () |
			 |_| |___/ |_|  \__/


	Brought to you by linuxserver.io
	-------------------------------------

	To support the app dev(s) visit:
	WireGuard: https://www.wireguard.com/donations/

	To support LSIO projects visit:
	https://www.linuxserver.io/donate/
	-------------------------------------
	GID/UID
	-------------------------------------

	User uid:    911
	User gid:    911
	-------------------------------------

	Uname info: Linux c42439b05dcc 6.0.0-0.deb11.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19) x86_64 x86_64 x86_64 GNU/Linux
	**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
	**** As the wireguard module is already active you can remove the SYS_MODULE capability from your container run/compose. ****
	**** Client mode selected. ****
	[custom-init] No custom files found, skipping...
	**** Disabling CoreDNS ****
	Warning: `/config/wg0.conf' is world accessible
	[#] ip link add wg0 type wireguard
	[#] wg setconf wg0 /dev/fd/63
	[#] ip -4 address add 10.65.237.90/32 dev wg0
	[#] ip link set mtu 1420 up dev wg0
	[#] resolvconf -a wg0 -m 0 -x
	[#] ip -4 route add 192.169.0.0/16 dev wg0
	[#] ip -4 route add 192.170.0.0/15 dev wg0
	[#] ip -4 route add 192.172.0.0/14 dev wg0
	[#] ip -4 route add 192.160.0.0/13 dev wg0
	[#] ip -4 route add 192.176.0.0/12 dev wg0
	[#] ip -4 route add 192.128.0.0/11 dev wg0
	[#] ip -4 route add 192.192.0.0/10 dev wg0
	[#] ip -4 route add 192.0.0.0/9 dev wg0
	[#] ip -4 route add 193.0.0.0/8 dev wg0
	[#] ip -4 route add 194.0.0.0/7 dev wg0
	[#] ip -4 route add 196.0.0.0/6 dev wg0
	[#] ip -4 route add 200.0.0.0/5 dev wg0
	[#] ip -4 route add 208.0.0.0/4 dev wg0
	[#] ip -4 route add 224.0.0.0/3 dev wg0
	[#] ip -4 route add 128.0.0.0/2 dev wg0
	[#] ip -4 route add 0.0.0.0/1 dev wg0
	[#] iptables -t nat -A POSTROUTING -o wg+ -j MASQUERADE
	[ls.io-init] done.
```

**Comment by StrikeAgainst** [comment]
So I checked the logs more carefully and noticed that part of the start commands is not being executed once I define any more than one IP masks in `AllowedIPs`, even for something like `0.0.0.0/1,128.0.0.0/1` which is supposed to cover the whole range. For one IP mask only this has some more lines:

	[#] ip link add wg0 type wireguard
	[#] wg setconf wg0 /dev/fd/63
	[#] ip -4 address add 10.13.13.2 dev wg0
	[#] ip link set mtu 1420 up dev wg0
	[#] resolvconf -a wg0 -m 0 -x
	[#] wg set wg0 fwmark 51820 # ------------------------------------ MISSING!
	[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
	[#] ip -4 rule add not fwmark 51820 table 51820 # ---------------- MISSING!
	[#] ip -4 rule add table main suppress_prefixlength 0 # ---------- MISSING!
	[#] iptables-restore -n # ---------------------------------------- MISSING!
	[#] iptables -t nat -A POSTROUTING -o wg+ -j MASQUERADE
	[ls.io-init] done.

**Comment by daromanyuk** [comment]
I have the same issue. How to fix it?

**Comment by StrikeAgainst** [comment]
I managed to work around it by not routing the IPs to be excluded to the client to begin with, instead sending them to the host gateway directly. This creates a bit more overhead to each container where you apply this routing though.

Overall I am not happy with the manual `ip route` solution though, as it is not persistent and lacks overview and control. I'm currently evaluating options where I could either apply another network to containers which is dedicated to VPN routing, or maybe even put a proxy server in place responsible for IP routing. I might check out [this WireProxy image](https://hub.docker.com/r/daycat/wireproxy-docker) soon, as it combines both the client and a proxy in one.
