### ISSUE TITLE
[FEAT] Ability to add iptables rules on container startup

### ISSUE THREAD

**Issue by ldavis2020** [linuxserver/docker-wireguard#246]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It would be great to be able to add iptables rules that are loaded on container startup, but I can't seem to be able to easily do this with the current container setup (unless someone else knows how to?).

### Reason for change

As per above.

**Comment by aptalca** [comment]
You can add them to `PostUp/PreDown` in the server template

**Comment by ldavis2020** [comment]
Thank you, I'm already using the `PostUp/PreDown` templates and they are great, but they only seem to take effect once the `wg0` interface has come up.
What I am looking for is "PreUp" iptables rules - to ensure required iptables rules are in place prior to bringing up the `wg0` interface.

**Comment by thespad** [comment]
Then you can use PreUp/Postdown

**Comment by ldavis2020** [comment]
Didn't know wg supported `PreUp` rules. Thanks I'll check them out and see how it goes.
