### ISSUE TITLE
[FEAT] can it support server mode and client mode at the same time

### ISSUE THREAD

**Issue by jaodei** [linuxserver/docker-wireguard#248]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It supports server mode and client mode at the same time.

### Reason for change

The client connecting to the container can get double wireguard tunnel protection.

**Comment by aptalca** [comment]
We recommend routing tables/rules and multiple containers for it: https://www.linuxserver.io/blog/advanced-wireguard-container-routing
