### ISSUE TITLE
Error response from daemon: stat /var/lib/docker/overlay2/

### ISSUE THREAD

**Issue by pierrotori** [linuxserver/docker-wireguard#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i try to pull this command docker pull linuxserver/wireguard
 ⠇ wireguard Pulling                                                                                                     2.7s
   ⠦ ed9ca2265ff7 Downloading  [===>                                               ]  2.166MB...                         1.5s
   ⠴ d2e3055e0657 Download complete                                                                                      1.5s
   ⠴ 3269109c65f2 Download complete                                                                                      1.5s
   ⠴ 471bddf08a66 Downloading  [==>                                                ]  789.8kB...                         1.5s
   ⠴ b8bb2c671f24 Download complete                                                                                      1.5s
   ⠴ f53ad78f007a Waiting                                                                                                1.5s
   ⠴ 61938edcaa7d Waiting                                                                                                1.5s
 Error response from daemon: stat /var/lib/docker/overlay2/e7b747702eed4753b42b0a60f2ef1937275931a4143ad645d9154aeb988a082a: no such file or directory
Could you check please ?
Regards

### Expected Behavior

pull error

### Steps To Reproduce

install

### Environment

```markdown
--Configuration --
rpi : Raspberry Pi 2 Model B Rev 1.1
Harware : a01041
Modele : Cortex-A7
OS rpi : Linux raspberrypi 6.1.19-v7+ #1637 SMP Tue Mar 14 11:04:52 GMT 2023 armv7l GNU/Linux
Os Name : bullseye
Release: 11
```

### CPU architecture

armhf

### Docker creation

```bash
sudo docker compose up -d
```

### Container logs

```bash
no log
```

**Comment by j0nnymoe** [comment]
That's a host issue, not a container issue.

**Comment by pierrotori** [comment]
My docker compose
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SERVEURURL=xxx.xxxx.xx #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.10.10.0 #optional
    volumes:
      - /home/pi/wireguard-server/config:/config
      - /home/pi/wireguard-server/lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
