### ISSUE TITLE
Add a ui for client and server management

### ISSUE THREAD

**Issue by jorgemtzh** [linuxserver/docker-wireguard#26]
I think this is a great first attempt creating a wireguard docker container, so congratulations. 
A ui for client management will simplify the process of adding and removing clients.

There are some projects available such as:
[wg-ui](https://github.com/EmbarkStudios/wg-ui)
[wg-gen-web](https://github.com/vx3r/wg-gen-web)
[wg-access-server](https://github.com/Place1/wg-access-server)

**Comment by aptalca** [comment]
At the time of development there was no ui that was actively maintained with a track record. They were either brand new, or seemed to be abandoned. So we decided to go a different route.

It's already as easy as it gets to add/remove clients. There really is no need for a ui. Just modify the `PEERS` var and recreate the container.

**Comment by nick2k3** [comment]
This recent fork of subspace might be interesting:
https://github.com/subspacecommunity/subspace
it relies on the host system to have wireguard installed. 
Maybe it would be worth considering?

> It's already as easy as it gets to add/remove clients. There really is no need for a ui. Just modify the `PEERS` var and recreate the container.
It is indeed easy to perform, but not so much to access. You need a shell to generate new peer and/or access to the folder with the correct credantials to grab the configuration or the QR code.

**Comment by tobbenb** [comment]
Doesn't  it kind of defeat the purpose of installing the container if you have wireguard installed on the host?

**Comment by nick2k3** [comment]
you're right, I didn't express it properly.
IMHO the best scenario would be an UI that sits on top or connects to the linuxserver/docker-wireguard container to configure it, so that those who only wants to use the "vanilla image" could use it. Those who need a more user friendly approach could use an UI.
First use case that comes to mind: giving a nickname to each peer to recognize it. If you have > 5 peer it's hard to remember which is which.

**Comment by anoma** [comment]
I would suggest that until one interface has risen to the top with a proven track record that no UI be included.

What we have this now is not point and click but it is very elegant and more importantly inherently secure. 

The time will come when a web interface for this project may be appropriate but that time is not now.

**Comment by TristanB1994** [comment]
This is still a blocker, creating or updating the peers isn't the only to do a UI would enable. It would also allow for others to self serve configuration without requiring a ops engineer to support.
