### ISSUE TITLE
wg0 device not found?  

### ISSUE THREAD

**Issue by icsy7867** [linuxserver/docker-wireguard#27]
If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Deploying WG pod starts update successfully

## Current Behavior
The container is either not permitted or is having trouble creating the wg0 interface

## Steps to Reproduce
deploy WG on Kubernetes cluster
View logs.

## Environment####
Kubernetes (v1.17.4) Deployed via RKE
Rancher 2.4.3
Centos7 Nodes
x86_64
  
## Command used to create docker container (run/create/compose/screenshot)

> `apiVersion: apps/v1
> kind: Deployment
> metadata:
>   annotations:
>     deployment.kubernetes.io/revision: "7"
>     field.cattle.io/creatorId: user-wzxh4
>   creationTimestamp: "2020-05-13T18:36:56Z"
>   generation: 7
>   labels:
>     cattle.io/creator: norman
>     workload.user.cattle.io/workloadselector: deployment-public-wireguard
>   name: wireguard
>   namespace: public
>   resourceVersion: "6153297"
>   selfLink: /apis/apps/v1/namespaces/public/deployments/wireguard
>   uid: eda2e41d-d514-403d-93dd-32bf230c59e0
> spec:
>   progressDeadlineSeconds: 600
>   replicas: 1
>   revisionHistoryLimit: 10
>   selector:
>     matchLabels:
>       workload.user.cattle.io/workloadselector: deployment-public-wireguard
>   strategy:
>     rollingUpdate:
>       maxSurge: 1
>       maxUnavailable: 0
>     type: RollingUpdate
>   template:
>     metadata:
>       annotations:
>         cattle.io/timestamp: "2020-05-18T17:33:13Z"
>         field.cattle.io/ports: '[[{"containerPort":51820,"dnsName":"wireguard-nodeport","kind":"NodePort","name":"wgdata","protocol":"UDP","sourcePort":51820}]]'
>       creationTimestamp: null
>       labels:
>         workload.user.cattle.io/workloadselector: deployment-public-wireguard
>     spec:
>       containers:
>       - env:
>         - name: GUID
>           value: "1000"
>         - name: PEERDNS
>           value: 17.181.30.3
>         - name: PEERS
>           value: "10"
>         - name: PUID
>           value: "1000"
>         - name: SERVERPORT
>           value: "51820"
>         - name: SERVERURL
>           value: vpn2.domain.com
>         - name: TZ
>           value: america/new_york
>         image: linuxserver/wireguard
>         imagePullPolicy: Always
>         name: wireguard
>         ports:
>         - containerPort: 51820
>           name: wgdata
>           protocol: UDP
>         resources: {}
>         securityContext:
>           allowPrivilegeEscalation: false
>           capabilities:
>             add:
>             - NET_ADMIN
>             - SYS_MODULE
>           privileged: false
>           readOnlyRootFilesystem: false
>           runAsNonRoot: false
>         stdin: true
>         terminationMessagePath: /dev/termination-log
>         terminationMessagePolicy: File
>         tty: true
>         volumeMounts:
>         - mountPath: /config
>           name: wg-config
>         - mountPath: /lib/modules
>           name: lib-module-volume
>       dnsPolicy: ClusterFirst
>       restartPolicy: Always
>       schedulerName: default-scheduler
>       securityContext: {}
>       terminationGracePeriodSeconds: 30
>       volumes:
>       - name: wg-config
>         persistentVolumeClaim:
>           claimName: wireguard-pvc
>       - name: lib-module-volume
>         persistentVolumeClaim:
>           claimName: lib-module-pvc
> status:
>   availableReplicas: 1
>   conditions:
>   - lastTransitionTime: "2020-05-18T17:29:06Z"
>     lastUpdateTime: "2020-05-18T17:29:06Z"
>     message: Deployment has minimum availability.
>     reason: MinimumReplicasAvailable
>     status: "True"
>     type: Available
>   - lastTransitionTime: "2020-05-13T18:36:57Z"
>     lastUpdateTime: "2020-05-18T17:33:19Z"
>     message: ReplicaSet "wireguard-86d55b77c7" has successfully progressed.
>     reason: NewReplicaSetAvailable
>     status: "True"
>     type: Progressing
>   observedGeneration: 7
>   readyReplicas: 1
>   replicas: 1
>   updatedReplicas: 1
> `

## Docker logs

(Logs were quite large, I included a pastebin for ease of viewability)
https://pastebin.com/zqksr6U2

Not sure if this is a bug on CentOS or if I should be seeking troubleshooting in discord.  Thanks!

**Comment by aptalca** [comment]
template not fully filled out

**Comment by icsy7867** [comment]
Fair enough, I updated, but dont know if it's too late now.

**Comment by aptalca** [comment]
No kernel headers found. You need to follow the directions for that in the readme

**Comment by icsy7867** [comment]
Thanks @aptalca !

It seems you are correct.  However, I still get the same issue. I installed the linux headers via YUM, but i am getting the same error.  I expect there is some sort of version mismatch or sonmething.

**Comment by aptalca** [comment]
did you map `/usr/src`?

**Comment by icsy7867** [comment]
Of course.  Actually read that part of the readme.  The headers were correctly in a "kernel" directory on the host.

**Comment by peterbuga** [comment]
@icsy7867 i've encountered the same problem with fresh debian10 docker host and i used this https://github.com/cmulk/wireguard-docker/blob/buster/install-module to compile the proper kernels on the host (kinda goes against the docker's way of doing things but it's a small side step i'm willing to take)
i've also added the `/usr/src` and `/lib/mobules` bindings as mentioned in Readme

@aptalca might worth mentioning this in the Readme too 🤷‍♂️

**Comment by aptalca** [comment]
Fresh Debian doesn't need kernels on the host. It's hard to say what your issue was since you didn't include any other info.

**Comment by peterbuga** [comment]
Thanks for quick reply!
> And funny enough, the script you posted is exactly what we do inside this container 

that's what I assumed so too after digging a bit into the logs, but for whatever reason the container kept complaining the headers are missing. 
I could give / post more details if you can quick point me wha to do. the env described above it's a fresh debian10 instance from hetzner, basically just docker installed on it + a few more helper binaries.

**Comment by john-arvid** [comment]
Same problem here with `wg0 device not found`
Using Ubuntu 18.04.4 with docker-compose and the yaml example in the readme. 
I don't get the issue where the kernel is not found. (I think)
Here is the log from the last startup:
<details>
<summary>log</summary>

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
linux-headers-5.3.0-53-generic is already the newest version (5.3.0-53.47~18.04.1).
wireguard is already the newest version (1.0.20200513-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
Server mode is selected
External server address is set to xxx.xxx
External server port is set to 51821. Make sure that port is properly forwarded to port 51820 inside this container
Internal subnet is set to 10.63.13.0
Peer DNS servers will be set to 192.168.1.2
Server mode is selected
No changes to parameters. Existing configs are used.
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[#] ip link add wg0 type wireguard
Error: Unknown device type.
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
Cannot find device "wg0"
.:53
CoreDNS-1.6.9
linux/amd64, go1.14.1, 1766568
```

</details>

Let me know if there is any other logs or information that can be helpful. (Or if I should create a new issue)

**Comment by aptalca** [comment]
Just a general comment, if you're getting the `wg0 device not found` error, please don't respond with an `I'm getting the same error`, because that's not informative at all. It just means the overall wireguard install failed, which could be due to a number of different issues.

Look through your logs right after container creation (not after a container restart), we tried to make them as verbose as possible. If you're still confused about the results, post them on pastebin or the like and leave a link here.

**Comment by john-arvid** [comment]
@aptalca Understood, just wrong wording by me, meant that the only similar thing was `wg0 device not found`

Here is the whole log after container creation: (Did a `docker container rm wireguard` before doing the `docker-compose up -d` again)
<details>
<summary>log</summary>

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic InRelease [15.9 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main Sources [1,161 B]
Get:5 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/restricted Sources [5,823 B]
Get:7 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main amd64 Packages [880 B]
Get:8 http://archive.ubuntu.com/ubuntu bionic/multiverse Sources [216 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/main Sources [1,063 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Sources [8,394 B]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [408 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [371 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Sources [7,152 B]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [73.6 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [20.1 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1,226 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,385 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-security/multiverse Sources [3,232 B]
Get:24 http://archive.ubuntu.com/ubuntu bionic-security/main Sources [192 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-security/universe Sources [216 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-security/restricted Sources [5,992 B]
Get:27 http://archive.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [8,815 B]
Get:28 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [852 kB]
Get:29 http://archive.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [59.3 kB]
Get:30 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [930 kB]
Fetched 31.9 MB in 4s (7,384 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  linux-headers-5.3.0-53 wireguard-dkms wireguard-tools
The following NEW packages will be installed:
  linux-headers-5.3.0-53 linux-headers-5.3.0-53-generic wireguard
  wireguard-dkms wireguard-tools
0 upgraded, 5 newly installed, 0 to remove and 19 not upgraded.
Need to get 12.6 MB of archives.
After this operation, 86.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-headers-5.3.0-53 all 5.3.0-53.47~18.04.1 [11.0 MB]
Get:2 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main amd64 wireguard-dkms all 1.0.20200506-1~18.04 [256 kB]
Get:3 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main amd64 wireguard-tools amd64 1.0.20200513-1~18.04 [88.5 kB]
Get:4 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main amd64 wireguard all 1.0.20200513-1~18.04 [8,100 B]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-headers-5.3.0-53-generic amd64 5.3.0-53.47~18.04.1 [1,215 kB]
Fetched 12.6 MB in 1s (9,225 kB/s)
Selecting previously unselected package linux-headers-5.3.0-53.
(Reading database ... 45903 files and directories currently installed.)
Preparing to unpack .../linux-headers-5.3.0-53_5.3.0-53.47~18.04.1_all.deb ...
Unpacking linux-headers-5.3.0-53 (5.3.0-53.47~18.04.1) ...
Selecting previously unselected package linux-headers-5.3.0-53-generic.
Preparing to unpack .../linux-headers-5.3.0-53-generic_5.3.0-53.47~18.04.1_amd64.deb ...
Unpacking linux-headers-5.3.0-53-generic (5.3.0-53.47~18.04.1) ...
Selecting previously unselected package wireguard-dkms.
Preparing to unpack .../wireguard-dkms_1.0.20200506-1~18.04_all.deb ...
Unpacking wireguard-dkms (1.0.20200506-1~18.04) ...
Selecting previously unselected package wireguard-tools.
Preparing to unpack .../wireguard-tools_1.0.20200513-1~18.04_amd64.deb ...
Unpacking wireguard-tools (1.0.20200513-1~18.04) ...
Selecting previously unselected package wireguard.
Preparing to unpack .../wireguard_1.0.20200513-1~18.04_all.deb ...
Unpacking wireguard (1.0.20200513-1~18.04) ...
Setting up wireguard-dkms (1.0.20200506-1~18.04) ...
Loading new wireguard-1.0.20200506 DKMS files...
It is likely that 5.3.0-53-generic belongs to a chroot's host
Building for 5.3.0-53-generic
Building initial module for 5.3.0-53-generic
Done.

wireguard:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-53-generic/updates/dkms/

depmod...

DKMS: install completed.
Setting up wireguard-tools (1.0.20200513-1~18.04) ...
Setting up linux-headers-5.3.0-53 (5.3.0-53.47~18.04.1) ...
Setting up wireguard (1.0.20200513-1~18.04) ...
Setting up linux-headers-5.3.0-53-generic (5.3.0-53.47~18.04.1) ...
/etc/kernel/header_postinst.d/dkms:
 * dkms: running auto installation service for kernel 5.3.0-53-generic
   ...done.
Server mode is selected
External server address is set to xxx.xxx
External server port is set to 51821. Make sure that port is properly forwarded to port 51820 inside this container
Internal subnet is set to 10.63.13.0
Peer DNS servers will be set to 192.168.1.2
No found wg0.conf found (maybe an initial install), generating 1 server and 5 peer/client confs
PEER 1 QR code:
PEER 2 QR code:
PEER 3 QR code:
PEER 4 QR code:
PEER 5 QR code:
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
.:53
CoreDNS-1.6.9
linux/amd64, go1.14.1, 1766568
[#] ip link add wg0 type wireguard
Error: Unknown device type.
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
Cannot find device "wg0"
```

</details>

**Comment by aptalca** [comment]
What's your compose yaml?

**Comment by john-arvid** [comment]
Same as in the readme, just with different timezone, port and volume directory.
<details>
<summary>docker-compose.yml</summary>

```
---
version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - SERVERURL=xxx.xx #optional
      - SERVERPORT=51821 #optional
      - PEERS=5 #optional
      - PEERDNS=192.168.1.2 #optional
      - INTERNAL_SUBNET=10.63.13.0 #optional
    volumes:
      - ./config:/config
      - ./modules:/lib/modules
    ports:
      - 51821:51821/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

</details>

**Comment by aptalca** [comment]
You're not supposed to customize the lib/modules mount. That has to be exactly `/lib/modules:/lib/modules`

**Comment by john-arvid** [comment]
That solved it for me. Sorry for the misunderstanding.
