### ISSUE TITLE
[FEAT] Support for many peers

### ISSUE THREAD

**Issue by FStefanni** [linuxserver/docker-wireguard#272]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi,

I like to give meaningful names to peers (this is super useful for maintenance), and I will have a lot of peers (hundreds).
So probably having a complementary way to the `PEERS` variable to give names to peers could be the best solution in these cases.

I am thinking to something similar to a list written in a configuration file, but any other easily manageable solution would be fine. For example,  `PEERS` could hold (as an additional alternative to current possibilities) the absolute path to the file which lists the names.

Regards

### Reason for change

I know the environmental variable `PEERS` allows to give meaningful names, but:

* I do not know if there is a limit in the length for an environmental variable
* Even if there is not, it seems not so handful to use in case of hundreds of names

At the moment, the easiest workaround seems to specify a number for `PEERS`, and then, in a separate file, track which certificate matches which host, and this is bug prone and not easily maintainable.

**Comment by aptalca** [comment]
You can set env var from a file: https://github.com/linuxserver/docker-wireguard#environment-variables-from-files-docker-secrets

**Comment by FStefanni** [comment]
Hi,

ok it seems fine enough. I'll try it.

Regards

**Comment by FStefanni** [comment]
Hi,

yes it works good enough.
It seems to:
- Allow peers on the same line, as in the env var. e.g.: `peer1,peer2`
- Allow to specify also the peers one per line

Minor issues:
- It prints a minor warning, which maybe it is related to the end-of-file (it actually generates all the peers):
```
 **** Peer  contains non-alphanumeric characters and thus will be skipped. No config for peer  will be generated. ****
```
- It does not seem to support comments (e.g. lines starting with `#`)

So apart these minor issues, it seems fine.
Could these be fixed?

Thank you,
regards

**Comment by drizuid** [comment]
> So apart these minor issues, it seems fine.
> Could these be fixed?

Feel free to submit a PR
