### ISSUE TITLE
[BUG] lscr.io/linuxserver/wireguard:latest does not work with arm64v8

### ISSUE THREAD

**Issue by logopk** [linuxserver/docker-wireguard#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following the announcement on https://www.linuxserver.io/blog/a-farewell-to-arm-hf I have updated my Pi 3b+ to 64bit.

Now my compose file with lscr.io/linuxserver/wireguard:latest fails with the message:

docker pull lscr.io/linuxserver/wireguard:latest        
latest: Pulling from linuxserver/wireguard
no matching manifest for linux/arm/v8 in the manifest list entries

### Expected Behavior

pulls automatically the arm64v8 image (as with armhf).

### Steps To Reproduce

Update Pi Kernel to 64bit

pull the latest image

### Environment

```markdown
- OS: Linux raspberrypi 6.1.34-v8+ #1657 SMP PREEMPT Fri Jun 16 12:36:29 BST 2023 aarch64 GNU/Linux

- How docker service was installed: distro's packagemanager
```

### CPU architecture

arm64

### Docker creation

```bash
docker pull lscr.io/linuxserver/wireguard:latest
```

### Container logs

```bash
latest: Pulling from linuxserver/wireguard
no matching manifest for linux/arm/v8 in the manifest list entries
```

**Comment by aptalca** [comment]
`linux/arm/v8` is 32bit and we don't support that
What we support is `linux/arm64`

Sounds like your kernel is updated to 64 bit but userspace is still 32 bit

**Comment by logopk** [comment]
Oh, OK I see. So once userspace is also 64bit it will bei arm64 (only)?

**Comment by logopk** [comment]
OK, then I will close this again.

**Comment by flippinger** [comment]
I have the same problem on a Raspi 4b, even though `docker info` shows `Architecture: aarch64`

```$ docker info
Client: Docker Engine - Community
 Version:    24.0.4
 ...
 Kernel Version: 6.1.21-v8+
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
```


```
$ docker-compose pull wireguard
Pulling wireguard ... pulling from linuxserver/wireguard
ERROR: for wireguard  no matching manifest for linux/arm/v8 in the manifest list entries
ERROR: no matching manifest for linux/arm/v8 in the manifest list entries
```

**Comment by thespad** [comment]
For whatever reason your host is still trying to pull a 32bit manifest. You can try pulling the `arm64v8-latest` tag directly and see if that helps.

**Comment by flippinger** [comment]
thank you, that fixed it. Pulling `image: linuxserver/wireguard:arm64v8-latest` works

**Comment by julius-gmeinder** [comment]
OK so i have the same problem, aarch64 on docker info and kernel level but docker still tries to pull linux/arm/v8. now i have specified that it should but after running docker compose i get " ! wireguard The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v8) and no specific platform was requested" so im kinda confused guys

**Comment by coderpop** [comment]
The same for me too...

**Comment by thespad** [comment]
Guys, this issue has been closed for 3 months. If you're having difficulties getting the image running then please either open a new issue with the necessary information or post a question on our [Discord server](https://discord.gg/YWrKVTn).
