### ISSUE TITLE
[FEAT] All environment variable per peer (not just SERVER_ALLOWEDIPS_PEER_)

### ISSUE THREAD

**Issue by igoooor** [linuxserver/docker-wireguard#284]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It would be nice that all environment variables used in `/config/templates/peer.conf` can be customised like `ALLOWEDIPS`.
In other words:
- CLIENT_IP => SERVER_CLIENT_IP_PEER_
- PEER_ID => SERVER_PEER_ID_PEER_
- PEERDNS => SERVER_PEERDNS_PEER_
- SERVERPORT => SERVER_SERVERPORT_PEER_
- SERVERURL => SERVER_SERVERURL_PEER_

So that I can configure each peer as I like (useful for site-to-site where I'd like to customize the Endpoint of a specific peer

### Reason for change

Currently peer1 get reverted to original template if I add one more peer, so I lose any custom setting I would have made in `/config/peer1/peer1.conf`

**Comment by aptalca** [comment]
Each env var we add increases the complexity of setup, the initial barrier of entry and the support requests we receive. I'm not in favor of adding env vars for things that can/should be easily edited by the user.

I don't see a common scenario where one would have to repeatedly import the same peer conf into the client. When you do import, you can easily edit as necessary. If for some reason you do need to repeatedly import, you can save your customized conf with a different name in the peer's folder and it won't be overwritten.

**Comment by igoooor** [comment]
Thank you for your reply @aptalca , I don't necessarily agree, because I do see the use case obviously ^^ but let say ok I'll go your way.
What I like with the `PEER` env var is that it will automatically create the peer, and the QR code. And the QR Code will be displayed in the logs, or with the `/app/show-peer` command.
Is there a way (a script or command) to generate these peers manually, similarly to the `PEER` var?

**Comment by aptalca** [comment]
If you mean the qr code, insert any conf name into this command: https://github.com/linuxserver/docker-wireguard/blob/master/root/etc/s6-overlay/s6-rc.d/init-wireguard-confs/run#L113

**Comment by igoooor** [comment]
thanks for the reference, that's already great :)
Can you maybe help me clarify something. Let's take the following scenario:
First start of the docker container with `PEER=2`. 2 new peers will be created: `peer1` and `peer2`
I would like to use `peer1` as my site-to-site peer, therefore I would need to set a different `Endpoint` for that peer. I can do it via editing manually `/config/peer1/peer1.conf`
But if I do that, and then set `PEER=3` then my `/config/peer1/peer1.conf` will be recreated and the `Endpoint` overwritten with default `SERVERURL`.

So this is the first thing I'm not sure if I do right or wrong.

Then you said I could rename the peer so that it won't get overwritten, but if I do that and increase `PEER` then I'm pretty sure that the renamed peer will not be included in `/config/wg0.conf`. Is that correct? Anyway to work around that?

Thank you very much for your patience

**Comment by aptalca** [comment]
> I would like to use peer1 as my site-to-site peer, therefore I would need to set a different Endpoint for that peer.

I don't follow what you're trying to do. `PEERS` var is used when you set this container up in server mode. Any peer you let it generate is meant to connect to this server container and the endpoint needs to point to this server container. Why would you need a different endpoint? If you need to create a different peer for a different wireguard tunnel, it should be created separately.

> Then you said I could rename the peer so that it won't get overwritten, but if I do that and increase PEER then I'm pretty sure that the renamed peer will not be included in /config/wg0.conf. Is that correct?

When you do that, there is no renamed peer. There is only a renamed conf (to prevent overwriting). The renamed conf has no relevance for the server container as it is not used anywhere. As long as a peer is included in the `PEERS` var (either by name or id number) and it has its folder with the main conf and keys in it, its public key and tunnel IP will be added to `wg0.conf` so it will be enabled. The peer conf itself is only there for you to transfer to the client device. There is no such thing as `renamed peer getting included in /config/wg0.conf` in this scenario.

**Comment by igoooor** [comment]
You are totally right, I apologize. I'm new to Wireguard and I misunderstood the config for site-to-site.
I'll close that issue as you already answered the initial question. Thank you very much
