### ISSUE TITLE
[BUG] As a client reconnect to a server with changing dynamic IP

### ISSUE THREAD

**Issue by vwkd** [linuxserver/docker-wireguard#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running `docker-wireguard` as a Wireguard client. It connects to a Wireguard server with a dynamic IP. However, when the dynamic IP of the server changes `docker-wireguard` loses the connection and doesn't re-establish it.

It seems known behavior for a Wireguard client to not re-establish the connection to a server with a dynamic IP, as it only resolves DNS once on initial startup [^1][^2]. wireguard-tools includes a [reresolve script](https://github.com/WireGuard/wireguard-tools/blob/master/contrib/reresolve-dns/reresolve-dns.sh) that the client can run periodically to re-establishe the connection.

It would be helpful if `docker-wireguard` could do this.

[^1]: https://wiki.archlinux.org/title/WireGuard#Endpoint_with_changing_IP
[^2]: https://www.netways.de/en/blog/2022/01/06/wireguard-mit-dynamischen-dns-namen/

### Expected Behavior

`docker-wireguard` used as a Wireguard client should reconnect automatically to a Wireguard server with dynamic IP after it changed its IP.

### Steps To Reproduce

1. Create a Wireguard server with dynamic IP
2. Set up `docker-wireguard` to connect to it as a client
3. Change the dynamic IP of the Wireguard server
4. Observe how `docker-wireguard` loses the connection and doesn't re-establish it

### Environment

```markdown
- OS: macOS 12.6.7
- How docker service was installed: Docker Desktop
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3.3"

services:
  wireguard:
    image: linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    secrets:
      - source: wg0_conf
        target: "/config/wg0.conf"
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

secrets:
  wg0_conf:
    environment: "WIREGUARD_CONFIG"
```

### Container logs

```bash
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 192.168.192.77/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

Uname info: Linux cb71aa9a2b9b 5.15.49-linuxkit-pr #1 SMP Thu May 25 07:17:40 UTC 2023 x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** Client mode selected. ****
[custom-init] No custom files found, skipping...
**** Disabling CoreDNS ****
[ls.io-init] done.
```

**Comment by aptalca** [comment]
This is not a bug, as it is just how wireguard (upstream) operates. We're not going to try and implement anything about this in the image as the client mode is partially supported as it is (requires the user to provide the full config and we do not provide support as we simply don't have the resources to deal with the multitude of options and variations between user config).

However, you have several options for implementing it yourself:
1. You can take advantage of the customization options we provide: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
2. You can rely on cron on host to run it via docker exec
3. You can use our cron mod: https://github.com/linuxserver/docker-mods/tree/universal-cron

**Comment by vwkd** [comment]
Here's the solution I came up with.

Set up a [Custom Script](https://docs.linuxserver.io/general/container-customization#custom-scripts) that registers a cron job that runs the reconnect script every minute. (Probably could use a Custom Service too, but unsure what's the benefit).

`docker-compose.yml`

```diff
+    volumes:
+      - ./wireguard/setup.sh:/custom-cont-init.d/setup.sh:ro
+      - ./wireguard/wireguard_reconnect.sh:/usr/local/bin/wireguard_reconnect.sh:ro
```

`wireguard/setup.sh`

```sh
#!/bin/bash

# reconnect WireGuard endpoint
echo "* * * * * /bin/bash /usr/local/bin/wireguard_reconnect.sh wg0" >> /etc/crontabs/root

crond
```

`wireguard/wireguard_reconnect.sh`

Note: I've created a modified reconnect script to tear down the whole interface with `wg-quick down wg0` and bring it back up with `wg-quick up wg0`, because the [reresolve script](https://github.com/WireGuard/wireguard-tools/blob/master/contrib/reresolve-dns/reresolve-dns.sh) didn't work.

```sh
#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2015-2020 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.

set -e
shopt -s nocasematch
shopt -s extglob
export LC_ALL=C

CONFIG_FILE="$1"
[[ $CONFIG_FILE =~ ^[a-zA-Z0-9_=+.-]{1,15}$ ]] && CONFIG_FILE="/config/$CONFIG_FILE.conf"
[[ $CONFIG_FILE =~ /?([a-zA-Z0-9_=+.-]{1,15})\.conf$ ]]
INTERFACE="${BASH_REMATCH[1]}"

process_peer() {
	[[ $PEER_SECTION -ne 1 || -z $PUBLIC_KEY || -z $ENDPOINT ]] && return 0
	[[ $(wg show "$INTERFACE" latest-handshakes) =~ ${PUBLIC_KEY//+/\\+}\	([0-9]+) ]] || return 0
	(( ($(date +%s) - ${BASH_REMATCH[1]}) > 135 )) || return 0
	wg-quick down "$INTERFACE"
	wg-quick up "$INTERFACE"
	reset_peer_section
}

reset_peer_section() {
	PEER_SECTION=0
	PUBLIC_KEY=""
	ENDPOINT=""
}

reset_peer_section
while read -r line || [[ -n $line ]]; do
	stripped="${line%%\#*}"
	key="${stripped%%=*}"; key="${key##*([[:space:]])}"; key="${key%%*([[:space:]])}"
	value="${stripped#*=}"; value="${value##*([[:space:]])}"; value="${value%%*([[:space:]])}"
	[[ $key == "["* ]] && { process_peer; reset_peer_section; }
	[[ $key == "[Peer]" ]] && PEER_SECTION=1
	if [[ $PEER_SECTION -eq 1 ]]; then
		case "$key" in
		PublicKey) PUBLIC_KEY="$value"; continue ;;
		Endpoint) ENDPOINT="$value"; continue ;;
		esac
	fi
done < "$CONFIG_FILE"
process_peer
```
