### ISSUE TITLE
[FEAT] PEERDNS setting should accept qualified hostname

### ISSUE THREAD

**Issue by anmshkmr** [linuxserver/docker-wireguard#289]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

`PEERDNS` env var setting should work without a static IP.

For example: 
```
        - name: "PEERDNS"
          value: "adguard.wireguard-adguard.svc.cluster.local"
```

does not work.

I am using a tandem kubernetes pod for adguard deployment, and it gets a random ip. I capture that ip through a Service resource, which gets a qualified hostname like the one I am trying to use above. But this setting doesn't work on wireguard.

### Reason for change

It will enable hostname based peerdns value, making wireguard more flexible

**Comment by aptalca** [comment]
Define `does not work.`

**Comment by anmshkmr** [comment]
> Define `does not work.`

By `does not work` I meant, wireguard peers do not discover the DNS host (adguard in this case). Wireguard peers are not able to resolve hostnames at all. 

Alternatively, when I change peerdns to a static IP, wireguard peers are able to resolve hostnames. Hope that clarifies.

**Comment by anmshkmr** [comment]
@aptalca does that clarify?

**Comment by aptalca** [comment]
PEERDNS determines what gets set as the dns address in the peer's wireguard conf. You're telling a peer to use that address as the dns server, but the peer has no way of resolving that address to an IP. I'm not sure what you expect to happen here.

You can however, set PEERDNS to auto, which sets it to the tunnel IP of the wireguard server, and then set your Coredns running inside the server container to forward to whatever address you like.

**Comment by anmshkmr** [comment]
In case I am using a custom DNS server (adguard, eg.), `PEERDNS` setting should resolve the hostname from coredns (kubedns in return, in case of a kubernetes cluster). Allow me to describe my kubernetes setup in which I am trying to use it.

Adguard setup:
1 k8s pod running adguard 
1 k8s service with dynamic clusterIP, this points to the pod running adguard

Wireguard setup:
1 k8s pod running wireguard
1 k8s service with load balancer, this points to the pod running wireguard

All IPs in this case should ideally be dynamic. PEERDNS setting for wireguard peers should resolve to the cluster hostname for adguard, something like `adguard.default.svc.cluster.local`

Without the ability to resolve the PEERDNS hostname, I am forced to use a static IP for the adguard k8s service.

Hope that makes sense.

**Comment by aptalca** [comment]
If you set PEERDNS to `auto`, it is set to use Coredns running on wg server. Coredns by default is set to forward all requests to whatever dns the container is set to use: https://github.com/linuxserver/docker-wireguard/blob/master/root/defaults/Corefile#L4

**Comment by anmshkmr** [comment]
Please note that if `PEERDNS` supported hostname, its IP will be resolved by coredns, which will be ideal.

**Comment by aptalca** [comment]
PEERDNS var is strictly for setting the DNS address in the peer's wireguard conf
