### ISSUE TITLE
Coredns process consumes high resources

### ISSUE THREAD

**Issue by mr-cn** [linuxserver/docker-wireguard#29]
## Expected Behavior
CPU Usage is acceptable, but such a high usage must be abnormal.

## Current Behavior
![图片](https://user-images.githubusercontent.com/19818121/82778981-8c4e4480-9e85-11ea-8ae7-f5d728922765.png)
![图片](https://user-images.githubusercontent.com/19818121/82779085-d33c3a00-9e85-11ea-8674-ac5e51c51c9e.png)

The coredns process in the image consumes a huge CPU usage (almost full of my dual-core CPU) and memory usage.

## Steps to Reproduce
1. Restart the container, and the usage is normally under 0.5%.
2. Connect the wireguard VPN. At the beginning, the device can't connect the internet, and at this time the CPU usage is normal. Wait a second, it can suddenly successfully connect, then the usage goes high as the screenshot showing above.
![图片](https://user-images.githubusercontent.com/19818121/82779401-b05e5580-9e86-11ea-9291-bccacd2b3e72.png)

## Environment
**OS:**    Debian buster  (OpenMediaVault 5)
**CPU architecture:** x86_64     
**How docker service was installed:**   I used script on https://get.docker.com (v19.03.8)

## Command used to create docker container (run/create/compose/screenshot)
![图片](https://user-images.githubusercontent.com/19818121/82779949-2c0cd200-9e88-11ea-8c2d-cac726dc60cc.png)
![图片](https://user-images.githubusercontent.com/19818121/82780004-4f378180-9e88-11ea-8033-6d4fe2dc5748.png)
![图片](https://user-images.githubusercontent.com/19818121/82780013-53fc3580-9e88-11ea-983d-51ba324a5eed.png)

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Get:3 http://deb.debian.org/debian buster-backports InRelease [46.7 kB]
Hit:4 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic InRelease
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1,226 kB]
Get:8 http://deb.debian.org/debian buster-backports/main Sources.diff/Index [27.8 kB]
Get:9 http://deb.debian.org/debian buster-backports/main amd64 Packages.diff/Index [27.8 kB]
Get:10 http://deb.debian.org/debian buster-backports/main Sources 2020-05-22-1409.45.pdiff [866 B]
Get:11 http://deb.debian.org/debian buster-backports/main Sources 2020-05-22-2010.56.pdiff [692 B]
Get:12 http://deb.debian.org/debian buster-backports/main Sources 2020-05-23-0210.02.pdiff [33 B]
Get:13 http://deb.debian.org/debian buster-backports/main Sources 2020-05-23-1400.49.pdiff [185 B]
Get:14 http://deb.debian.org/debian buster-backports/main Sources 2020-05-23-2018.42.pdiff [775 B]
Get:15 http://deb.debian.org/debian buster-backports/main Sources 2020-05-24-0211.50.pdiff [33 B]
Get:16 http://deb.debian.org/debian buster-backports/main Sources 2020-05-24-0809.52.pdiff [4,516 B]
Get:17 http://deb.debian.org/debian buster-backports/main Sources 2020-05-24-2010.35.pdiff [2,016 B]
Get:18 http://deb.debian.org/debian buster-backports/main Sources 2020-05-25-0206.42.pdiff [42 B]
Get:19 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-05-22-1409.45.pdiff [392 B]
Get:18 http://deb.debian.org/debian buster-backports/main Sources 2020-05-25-0206.42.pdiff [42 B]
Get:20 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-05-22-2010.56.pdiff [608 B]
Get:21 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-05-23-1400.49.pdiff [187 B]
Get:22 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-05-24-0211.50.pdiff [514 B]
Get:23 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-05-24-2010.35.pdiff [17.0 kB]
Get:24 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-05-25-0206.42.pdiff [1,703 B]
Get:24 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-05-25-0206.42.pdiff [1,703 B]
Get:25 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,385 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-security/restricted Sources [5,992 B]
Get:27 http://archive.ubuntu.com/ubuntu bionic-security/main Sources [192 kB]
Get:28 http://archive.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [59.3 kB]
Get:29 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [930 kB]
Fetched 4,108 kB in 2min 33s (26.8 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
linux-headers-5.5.0-0.bpo.2-amd64 is already the newest version (5.5.17-1~bpo10+1).
wireguard is already the newest version (1.0.20200513-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 200 not upgraded.
Server mode is selected
External server address is set to *****.*****.net
External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container
Internal subnet is set to 10.13.13.0
PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.13.13.1 to use wireguard docker host's DNS.
Server mode is selected
No changes to parameters. Existing configs are used.
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.13.1 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] ip -4 route add 10.13.13.3/32 dev wg0
[#] ip -4 route add 10.13.13.2/32 dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
.:53
CoreDNS-1.6.9
linux/amd64, go1.14.1, 1766568
Caught SIGTERM signal!
[INFO] SIGTERM: Shutting down servers then terminating
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[#] ip link delete dev wg0
[#] iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
s6-svwait: fatal: supervisor died
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by aptalca** [comment]
> Note: container is mapped with host network

That would be why you're having issues

**Comment by anoma** [comment]
> 
> 
> Found it !
> 
> CoreDNS config was pointing to itself, which lead to infinite loop
> 
> @mr-cn
> Check your `config/coredns/Corefile`
> 
> ```
> . {
>     forward . 127.0.0.11
> }
> ```
> 
> And point to another DNS
> 
> Example
> 
> ```
> . {
>     forward . 8.8.8.8
> }
> ```
> 
> Edit: Formatting

For the avoidance of doubt this quoted post is incorrect.

To expand on  @aptalca reply docker has an internal DNS system which presents as a loopback within each container on `127.0.0.11`. This allows you to lookup both public DNS (via hosts resolver) and internal docker DNS e.g. other container names.

If you make the change listed above you will fundamentally break internal docker lookups.

Unless you absolutely understand what this means and actually need to break it then do not do this.

**Comment by Hyurt** [comment]
Thanks for those explanations 

I needed to have access to wg0 interface from host, which is why I changed them and found myself in same position.  That's what lead me to this “fix”.

**Comment by lucaspiller** [comment]
I also have the high CPU usage when running this image out of the box. The command I'm using to create the container is:

```
docker create
--name=wireguard
--cap-add=NET_ADMIN
--cap-add=SYS_MODULE
-e PUID=1000
-e PGID=1000
-e TZ=<mytz>
-e SERVERURL=<mydomain> `#optional`
-e SERVERPORT=51820 `#optional`
-e PEERS=1 `#optional`
-e PEERDNS=192.168.1.1 `#optional`
-e INTERNAL_SUBNET=10.13.13.0 `#optional`
-p 51820:51820/udp
-v /wireguard/config:/config
-v /lib/modules:/lib/modules
--sysctl="net.ipv4.conf.all.src_valid_mark=1"
--restart unless-stopped
linuxserver/wireguard
```

What am I doing wrong?

**Comment by Hyurt** [comment]
Don’t you have logs for coreDNS ?
I would assume that PEERDNS host not reachable or wrong

**Comment by vimania** [comment]
I've had the same problem. try changing your Corefile in / coredns. Like this example:

```
$ cat Corefile
.:5353 {
  wgsd example.com. wg0
}

```
https://coredns.io/explugins/wgsd/

**Comment by anoma** [comment]
@vimania what exactly does that do and how does it work?

**Comment by drizuid** [comment]
> I also have the high CPU usage from coredns when running this image out of the box. The command I'm using to create the container is:
> 
> ```
> docker create
> --name=wireguard
> --cap-add=NET_ADMIN
> --cap-add=SYS_MODULE
> -e PUID=1000
> -e PGID=1000
> -e TZ=<mytz>
> -e SERVERURL=<mydomain> `#optional`
> -e SERVERPORT=51820 `#optional`
> -e PEERS=1 `#optional`
> -e PEERDNS=auto `#optional`
> -e INTERNAL_SUBNET=10.13.13.0 `#optional`
> -p 51820:51820/udp
> -v /wireguard/config:/config
> -v /lib/modules:/lib/modules
> --sysctl="net.ipv4.conf.all.src_valid_mark=1"
> --restart unless-stopped
> linuxserver/wireguard
> ```
> 
> What am I doing wrong? I tried changing `PEERDNS=auto` to `PEERDNS=<my router ip>` but it made no difference.

sorry for the delays but we've only just recently determined the root cause, thanks to user Tokugero on discord. The issue is that when you use docker create, as you did here without specifying a docker network, it will use the default bridge network which does NOT support docker dns. In compose, this is not an issue, with `docker run` or `docker create`, you must specify the user-defined docker network you created. You can also simply set `PEERDNS=8.8.8.8` or something.

 We are updating the application setup section in the readme to address this.

**Comment by aptalca** [comment]
specifically, the docker dns address we used, `127.0.0.11`, is not present in the default bridge network (or host networking). That's why coredns was going crazy.

We have a fix now, which will tell coredns to use the `/etc/resolv.conf` info instead rather than the hardcoded `127.0.0.11`. Existing users will have to delete their `/config/coredns/Corefile` and restart after updating the image to the next build.
