### ISSUE TITLE
[FEAT] KILL-SWITCH

### ISSUE THREAD

**Issue by Reaster0** [linuxserver/docker-wireguard#292]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

i would really prefer to have a killswitch on this docker, that cut all internet access if there's any issue

### Reason for change

because if my real ip leak... my seedbox run too many torrents to not get all the fines of the world by my local "government"

**Comment by aptalca** [comment]
> because if my real ip leak... my seedbox run too many torrents to not get all the fines of the world by my local "government"

That is not at all the purpose of this image and that is way beyond the scope. This image is for providing wireguard in a container so you can connect remote devices to each other.
