### ISSUE TITLE
[FEAT] Add healthcheck

### ISSUE THREAD

**Issue by Ziomal12** [linuxserver/docker-wireguard#303]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I'd like to propose adding healthcheck to dockerfile that would check that the VPN connection is successful and able to ping.

### Reason for change

To have other docker service start after the VPN connection is deemed healthy (using depends_on -> wireguard -> condition: service_healthy in docker compose)

**Comment by aptalca** [comment]
We don't add healthchecks.

You can however add your own healthcheck in docker compose or k8s, etc.
