### ISSUE TITLE
Ip range

### ISSUE THREAD

**Issue by Comandante1977** [linuxserver/docker-wireguard#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've installed WG with docker image. everything fine. But I cant change ip range. If I change 
range in docker-compose.yml to 10.13.8.0/21 and recreate docker image - all peers after 256 got address 10.13.8.254

### Steps To Reproduce

1

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
1
```

### Container logs

```bash
1
```

**Comment by aptalca** [comment]
#300
