### ISSUE TITLE
[FEAT] Improve observability capabilities within the container

### ISSUE THREAD

**Issue by proffalken** [linuxserver/docker-wireguard#309]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It would be great to be able to somehow expose metrics about number of clients connected, data throughput etc. from the Wireguard server and pull that information into Prometheus

### Reason for change

Observability is key in many organisations, adding this feature to the docker container will make it even more appealing in my view to other users.

**Comment by thespad** [comment]
Wireguard does not provide any kind of metrics endpoint that can be queried to obtain that kind of information and as it is stateless, the concept of a "connected" user doesn't really exist, just a user who has sent traffic in the last X timeframe.

**Comment by proffalken** [comment]
Ah, ok, I'd got confused by the availability of https://github.com/MindFlavor/prometheus_wireguard_exporter, but having re-read those docs I see now that it just runs commands against `wg` and reports back what it finds.

I'll close this, thanks.
