### ISSUE TITLE
[BUG] SERVER_ALLOWEDIPS_PEER_* include quotes inside AllowedIPs peer variable

### ISSUE THREAD

**Issue by rubencm** [linuxserver/docker-wireguard#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I set in my `docker-compose.yaml` the environment variable `SERVER_ALLOWEDIPS_PEER_laptop` like this
```
- SERVER_ALLOWEDIPS_PEER_laptop="192.168.1.0/24,192.168.2.0/24"
```

Then, when the `wg0.conf` is generated, the `AllowedIPs` property is set like this:
```
AllowedIPs = 10.13.13.3/32,"192.168.1.0/24,192.168.2.0/24"
```

### Expected Behavior

`AllowedIPs` should look like this, without quotes
```
AllowedIPs = 10.13.13.3/32,192.168.1.0/24,192.168.2.0/24
```

### Steps To Reproduce

Add `SERVER_ALLOWEDIPS_PEER_laptop` environment variable from README and run docker-compose

### Environment

```markdown
- OS: 
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose up
```

### Container logs

```bash
Irrelevant
```

**Comment by Roxedus** [comment]
Quote the line properly. 

```
- "SERVER_ALLOWEDIPS_PEER_laptop=192.168.1.0/24,192.168.2.0/24"
```

**Comment by rubencm** [comment]
> Quote the line properly.
> 
> ```
> - "SERVER_ALLOWEDIPS_PEER_laptop=192.168.1.0/24,192.168.2.0/24"
> ```

Then the README is wrong

**Comment by Roxedus** [comment]
`SERVER_ALLOWEDIPS_PEER_laptop="192.168.1.0/24,192.168.2.0/24"` is the correct quoting for a docker run

**Comment by rubencm** [comment]
Ok, I understand thank you. I will close the issue

**Comment by aptalca** [comment]
https://docs.linuxserver.io/general/docker-compose/#quoting-variables
