### ISSUE TITLE
[BUG] Improvement of the documentation of the ALLOWEDIPS parameter.

### ISSUE THREAD

**Issue by vladbejenaru** [linuxserver/docker-wireguard#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I know that a lot of people just use the 0.0.0.0/0 option but I think for the case when only certain traffic should go through the VPN that its important to mention that the IP Address of the server is the ip address of the `docker0` interface. 
In my case selfhosting I try to use the IP Address of the server hosting the wireguard docker (like 192.168.1.1) and did not work. Adding the address of the `docker0` interface solved the problem. I think it would be useful also for others that want to filter what goes through the VPN connection. This link helped me solve my problem: https://serverfault.com/questions/1083016/wireguard-not-working-with-enpoint-included-in-allowedips/1083431#1083431

### Expected Behavior

ALLOWEDIPS Parameter description should mention that the IP of the `docker0` network interface should be specified.

### Steps To Reproduce

1. Set allowed IP to the IP host where the docker is installed
2. Try to connect the client (I have tried in both linux and windows)
3. Failed to have internet connection

### Environment

```markdown
- OS:EndeavourOS XFCE, Windows 11
- How docker service was installed: docker-compose with standard parameters
```

### CPU architecture

x86-64

### Docker creation

```bash
wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/UTC
      - SERVERURL=mybeautiful.tld
      - SERVERPORT=51820
      - PEERS=2
      - PEERDNS=auto
#      - LOG_CONFS=true #confs will be displayed in log. otherwise they are available in /config/peerX
      - INTERNAL_SUBNET=10.13.13.0    #Only change if it conflicts
      - ALLOWEDIPS=192.168.1.0/24, 172.17.0.1/32, 10.13.13.0/24 #working config
#      - ALLOWEDIPS=192.168.1.0/24, 10.13.13.0/24 #NOT working config 
    volumes:
      - /mypath/wg/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

### Container logs

```bash
Uname info: Linux a5f2b8ffaa1c 6.1.15-1-pve #1 SMP PREEMPT_DYNAMIC PVE 6.1.15-1 (2023-03-08T08:53Z) x86_64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** As the wireguard module is already active you can remove the SYS_MODULE capability from your container run/compose. ****
**** Server mode is selected ****
**** External server address is set to mybeautiful.tld ****
**** External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container ****
**** Internal subnet is set to 10.13.13.0 ****
**** AllowedIPs for peers 192.168.1.0/24, 172.17.0.1/32, 10.13.13.0/24 ****
**** PEERDNS var is either not set or is set to "auto", setting peer DNS to 10.13.13.1 to use wireguard docker host's DNS. ****
**** Server mode is selected ****
**** Server related environment variables changed, regenerating 1 server and 8 peer/client confs ****
PEER 1 QR code (conf file is saved under /config/peer1):
...
[custom-init] No custom files found, skipping...
.:53
CoreDNS-1.10.1
linux/amd64, go1.20.11, 
**** Found WG conf /config/wg_confs/wg0.conf, adding to list ****
**** Activating tunnel /config/wg_confs/wg0.conf ****
Warning: `/config/wg_confs/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.13.1 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] ip -4 route add 10.13.13.9/32 dev wg0
[#] ip -4 route add 10.13.13.8/32 dev wg0
[#] ip -4 route add 10.13.13.7/32 dev wg0
[#] ip -4 route add 10.13.13.6/32 dev wg0
[#] ip -4 route add 10.13.13.5/32 dev wg0
[#] ip -4 route add 10.13.13.4/32 dev wg0
[#] ip -4 route add 10.13.13.3/32 dev wg0
[#] ip -4 route add 10.13.13.2/32 dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
**** All tunnels are now active ****
[ls.io-init] done.
```

**Comment by aptalca** [comment]
> ALLOWEDIPS Parameter description should mention that the IP of the docker0 network interface should be specified.

That may be the case for you here but I assure you it is not the case for everyone.

That parameter defines which connections should be sent through the tunnel. So whether you include a specific subnet in there depends on whether you want to access that subnet locally or through the tunnel. Everyone has different needs and setups. Upstream project has plenty of documentation on this parameter and further details would be beyond the scope of our readme.
