### ISSUE TITLE
[FEAT] mDNS (Avahi) support through Wireguard

### ISSUE THREAD

**Issue by mihaigalos** [linuxserver/docker-wireguard#317]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Please provide a condig or feature to enable Multicast DNS via Avahi to work using the linuxserver/docker-wireguard container.

Once connected via Wireguard, the client could directly access destination.local then.

### Reason for change

Currently, only direct IP access is possible, this feature would make access via hostnames possible.

**Comment by aptalca** [comment]
This is beyond the scope of this image.

Wireguard is just a tunnel. There are many different ways you can set up dns with it (locally, or through the tunnel, or via the included coredns). Some of which allows hostname resolution on the remote side but it depends on how you set it up.

The default server config (via env vars in the example) will use the server host's dns and do hostname resolution on the server side out of the box).
