### ISSUE TITLE
[BUG] Error generating QRCode  - qrencode: command not found

### ISSUE THREAD

**Issue by tanushshukla** [linuxserver/docker-wireguard#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you run the command to get the QRCode, it does not generate it but throws an error instead.
Command:
docker exec -it wireguard /app/show-peer 1

### Expected Behavior

It should display the QRCode

### Steps To Reproduce

use the docker compose stack provided in the example.
Then do docker-compose up -d
or 
run the below command if the container is already running:

docker exec -it wireguard /app/show-peer 1 

### Environment

```markdown
- OS: Raspberry Pi OS 64 bit
- How docker service was installed: 
Using the script provided at docker website
```

### CPU architecture

arm64

### Docker creation

```bash
---
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - /path/to/appdata/config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

### Container logs

```bash
/app/show-peer: line 18: qrencode: command not found
```

**Comment by aptalca** [comment]
already fixed in latest
