### ISSUE TITLE
[BUG] missing /32 in interface address

### ISSUE THREAD

**Issue by realies** [linuxserver/docker-wireguard#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

generated confs miss '/32' at the end of the 'Address' property of '[Interface']

### Steps To Reproduce

^

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: https://download.docker.com/linux/ubuntu
```

### CPU architecture

x86-64

### Docker creation

```bash
official docker compose with no changes
```

### Container logs

```bash
n/a
```

**Comment by thespad** [comment]
`/32` is implicit when no CIDR subnet mask is specified. Is there a specific problem you've encountered as a result of this or is a purely an aesthetic issue?

**Comment by realies** [comment]
yes, some devices report invalid configuration when the subnet is specified; fixed when '/32' is added manually, i don't see why it should be missing nor assumed an aesthetic issue

**Comment by aptalca** [comment]
It's prudent to be specific when reporting issues. 

I have never encountered this issue with Android, Windows and Linux clients as well as various router interfaces. And no one has reported this before.

Please list the devices affected so we can try and reproduce, or report to the device maintainers, whichever is appropriate.

**Comment by realies** [comment]
try anything from ubiquiti that supports vpn clients; i've never seen this issue before because all other conf generators i've tried so far include '/32' in the interface address

**Comment by thomashilzendegen** [comment]
I can confirm that Ubiquiti is complaining (and rejecting the config file) regarding the missing subnet mask.

**Comment by drizuid** [comment]
no surprise that everything works the same, except ubiquiti... pretty typical tbh.

**Comment by realies** [comment]
it was a surprise because all other profiles worked fine until I tried one generated from this image

**Comment by realies** [comment]
can someone review the pr?

**Comment by drizuid** [comment]
when we get through our backlog or it becomes more than one person requesting it, yes.

**Comment by realies** [comment]
> when we get through our backlog or it becomes more than one person requesting it, yes. 

it's literally a 6 symbol diff

**Comment by aptalca** [comment]
You can edit your peer conf template to add your 3 characters. There is no urgency for this
