### ISSUE TITLE
Old tags are wrong

### ISSUE THREAD

**Issue by ngosang** [linuxserver/docker-wireguard#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are old tags with higher number than the latest releases => v1.0.20210914-ls99
This causes confusion in docker updaters like diun / whatsupdocker. You should bump the `ls99` part to a higher number

![image](https://github.com/linuxserver/docker-wireguard/assets/10577978/8b595886-dcb9-46b8-9cde-0fae171d5691)

### Steps To Reproduce

.

### Environment

```markdown
.
```

### CPU architecture

x86-64

### Docker creation

```bash
.
```

### Container logs

```bash
.
```

**Comment by Roxedus** [comment]
While we think on this, its worth mentioning the lsxxx number did indeed restart, but it did not stop at 99, it went to 126. While our logic has some inconsistencies here, the detection you posted also isnt flawless.  
![image](https://github.com/linuxserver/docker-wireguard/assets/7110194/2135bb17-24f6-43ed-9df5-bae8bda344cd)

**Comment by ngosang** [comment]
Yeah, I have a regular expression with just 2 digits. It will be fine if we continue in 127

**Comment by aptalca** [comment]
To provide more context, we use skopeo to retrieve the last pushed version for the branch tag and extract the ls version to decide on the new tag.

Every once in a while it fails and starts from 1. Normally that's not an issue as the versions get bumped and there is no overlap. But wireguard tools did not get a version update in 3 years, and it led to overlap of tags

**Comment by ngosang** [comment]
I see with the new tags it's fixed => 1.0.20210914-r4-ls55
