### ISSUE TITLE
Setting SERVERPORT has no effect

### ISSUE THREAD

**Issue by elronzo** [linuxserver/docker-wireguard#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Setting the ENV variable SERVERPORT has no effect. Wireguard still listens on port 51280

### Expected Behavior

SERVERPORT should provide the ability to set a custom port.

### Steps To Reproduce

Set SERVERPORT to some other than the default port and do a wg show in the running container.

### Environment

```markdown
- K3s
- wireguard container running as a K8s pod
```

### CPU architecture

x86-64

### Docker creation

```bash
not relevant
```

### Container logs

```bash
n/a
```

**Comment by j0nnymoe** [comment]
Docker creation details are relevant and an example of the WG conf would be extremely helpful.

**Comment by Roxedus** [comment]
It will still listen to 51280. It will only set the port in the peer file, in the case you port forward 51280 to something else on the outside. It is only used as part of the generation of the endpoint line.

**Comment by aptalca** [comment]
There are lots of similar closed issues here
