### ISSUE TITLE
[FEAT] Enable logging in CoreDNS

### ISSUE THREAD

**Issue by FelixZY** [linuxserver/docker-wireguard#348]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It would be beneficial if CoreDNS logging was enabled by default as this helps with debugging.

### Reason for change

Logs help with diagnosing issues.

### Proposed code change

`/config/coredns/Corefile`
```diff
 . {
+    log
     loop
     health
     forward . /etc/resolv.conf
 }
```

**Comment by thespad** [comment]
We're not going to add `log` out of the box as it will generate way too much log volume with no real benefit to most users most of the time. I'm open to adding `error`, however, as that will help identify issues without flooding the logs with noise.

**Comment by aptalca** [comment]
Corefile is in the config folder and is user configurable. You're meant to edit it as necessary. I do split dns as well as DoT via edits for instance.
