### ISSUE TITLE
[FEAT] health check is must have feature for serious user

### ISSUE THREAD

**Issue by moralrebuild** [linuxserver/docker-wireguard#352]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

please provide a simple health check as Linuxserver.io did for other popular containers

### Reason for change

detecting if the VPN container is health is essential for other services depending it. For e.g., adding custom port forwarding function which is absent in current  feature set.

**Comment by aptalca** [comment]
> please provide a simple health check as Linuxserver.io did for other popular containers

We never added healthchecks. You can add it in yourself in compose.

**Comment by Roxedus** [comment]
We do not provide healthchecks for any of our containers because docker has no functionality that utilizes it, aside from docker ps. it does not take any action based on it.

**Comment by moralrebuild** [comment]
you are right. It looks like the gluetun is a much more decent solution than yours.
