### ISSUE TITLE
[FEAT] <miniscript>

### ISSUE THREAD

**Issue by techdron** [linuxserver/docker-wireguard#358]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I was unable to derive QR codes for configurations on the alpine docker container
#CodeBegine
#!/bin/sh
#alphine os, need install qrencode name: QrWGshow.sh
# Check if the qrencode utility is installed
if ! command -v qrencode >/dev/null 2>&1; then
    echo ‘The qrencode utility was not found. Install...’
    apk add --no-cache qrencode
    if [ $? -ne 0 ]; then
        echo ‘Failed to install qrencode. Check repository availability.’
        exit 1
    fi
else
    echo ‘The qrencode utility is already installed.’
fi

# Generate QR codes for all configuration files
for dir in /config/peer*/; do
    for conf in ‘$dir ’*.conf; do
        if [ -f ‘$conf’ ]; then
            echo ‘QR code for $conf:’
            qrencode -t ansi256utf8 < ‘$conf’
            echo ‘’ # Blank line to separate QR codes
        fi
    done
done
#endCode

### Reason for change

Wrote a script to automatically output

### Proposed code change

#wireguard-tools v1.0.20210914 - https://git.zx2c4.com/wireguard-tools/
#alpine-release 3.20.3

**Comment by aptalca** [comment]
I don't know if this is a bug report or a feature request bur qrencode is already installed in the image and the container should display the qr codes when keys and confs are generated by default. 

There is also a script at `/app/show-peer` that is designed to output the qr codes at will. It's described in the readme.

**Comment by techdron** [comment]
Он отказа работать по какой-то причине . Благодарю

пн, 14 окт. 2024 г., 21:58 aptalca ***@***.***>:
