### ISSUE TITLE
How to connect letsencrypt certificates? 

### ISSUE THREAD

**Issue by mihalt** [linuxserver/docker-wireguard#360]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Documentation

### Reason for change

I don't understand, what volumes should be used to connect certificates to use ssl? For example this:
```
$ ls /var/lib/angie/acme/https_validator/
account.key  certificate.pem  private.key
```

**Comment by j0nnymoe** [comment]
Wireguard doesn't have any use for letsencryt certs?

**Comment by mihalt** [comment]
> Wireguard doesn't have any use for letsencryt certs?

I don't know, what path should I use to connect this certs to your container?

**Comment by j0nnymoe** [comment]
What are you expecting to use the certificates for? Wireguard does not use SSL certs.

**Comment by mihalt** [comment]
> What are you expecting to use the certificates for? Wireguard does not use SSL certs.

Wireguard should support TLS, isn't it? So, it should use some certificates for this. I would like to use my letsencrypt certificates. Specially because my VPN server will work from domain and server the same as my website.

**Comment by j0nnymoe** [comment]
You should read up on wireguards feature set. It's not needed.

**Comment by mihalt** [comment]
> You should read up on wireguards feature set. It's not needed.

can you give me link on docs then, please? how does TLS work here?

**Comment by j0nnymoe** [comment]
https://www.wireguard.com/

It doesn't work with TLS.
