### ISSUE TITLE
[FEAT] README: Mark sysctl as always required

### ISSUE THREAD

**Issue by hoang-himself** [linuxserver/docker-wireguard#371]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Sysctl parameter should be required in both server and client mode
https://github.com/linuxserver/docker-wireguard/blob/master/readme-vars.yml#L40

### Reason for change

I was having problems with this image using rootless Podman, and I found that the sysctl parameter is necessary in server mode
I have not tried with rootful Podman or Docker, please advise otherwise

### Proposed code change

desc: "Required."

**Comment by aptalca** [comment]
It is not always required
