### ISSUE TITLE
Wireguard ls15 - RTNETLINK answers: Operation not supported

### ISSUE THREAD

**Issue by Chokoladekiks** [linuxserver/docker-wireguard#44]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
I expect the container to create 3 peers and make a wireguard point

## Current Behavior
The container starts, but never create the peers.

## Steps to Reproduce
1. create the docker compose file
2. sudo docker-compose up -d

## Environment
**OS:Ubuntu 18.04
**CPU architecture:** x86_64  
**How docker service was installed:**      
Sudo apt install docker.io docker-compose -y

## Command used to create docker container (run/create/compose/screenshot)
docker-compose.yml

---
version: "2.1"
services:
        wireguard:
                image: linuxserver/wireguard:amd64-1.0.20200319-1ubuntu118.04-ls11
                container_name: wireguard
                cap_add:
                        - NET_ADMIN
                        - SYS_MODULE
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=Europe/Copenhagen
                        - SERVERURL=85.184.164.50
                        - SERVERPORT=51820
                        - PEERS=3
                        - PEERDNS=1.1.1.1
                        - INTERNAL_SUBNET=10.13.13.0
                volumes:
                        - /docker/wireguard/config:/config
                        - /lib/modules:/lib/modules
                ports:
                        - 51820:51820/udp
                restart: unless-stopped

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
**** The wireguard module is not loaded, will attempt kernel header install and module compilation. ****
**** Attempting kernel header install ****
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/main Sources [1,063 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/restricted Sources [5,823 B]
Get:7 http://archive.ubuntu.com/ubuntu bionic/multiverse Sources [216 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [411 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Sources [9,368 B]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Sources [6,203 B]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [372 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1,270 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,398 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [93.9 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [13.4 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-security/main Sources [198 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-security/universe Sources [218 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-security/restricted Sources [7,075 B]
Get:23 http://archive.ubuntu.com/ubuntu bionic-security/multiverse Sources [3,235 B]
Get:24 http://archive.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [82.2 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [977 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [862 kB]
Get:27 http://archive.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [9,012 B]
Fetched 32.0 MB in 7s (4,455 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  linux-headers-4.15.0-69
The following NEW packages will be installed:
  linux-headers-4.15.0-69 linux-headers-4.15.0-69-generic
0 upgraded, 2 newly installed, 0 to remove and 4 not upgraded.
Need to get 12.2 MB of archives.
After this operation, 89.0 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-headers-4.15.0-69 all 4.15.0-69.78 [11.0 MB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-headers-4.15.0-69-generic amd64 4.15.0-69.78 [1,187 kB]
Fetched 12.2 MB in 2s (5,981 kB/s)
Selecting previously unselected package linux-headers-4.15.0-69.
(Reading database ... 17543 files and directories currently installed.)
Preparing to unpack .../linux-headers-4.15.0-69_4.15.0-69.78_all.deb ...
Unpacking linux-headers-4.15.0-69 (4.15.0-69.78) ...
Selecting previously unselected package linux-headers-4.15.0-69-generic.
Preparing to unpack .../linux-headers-4.15.0-69-generic_4.15.0-69.78_amd64.deb ...
Unpacking linux-headers-4.15.0-69-generic (4.15.0-69.78) ...
Setting up linux-headers-4.15.0-69 (4.15.0-69.78) ...
Setting up linux-headers-4.15.0-69-generic (4.15.0-69.78) ...
/etc/kernel/header_postinst.d/dkms:
 * dkms: running auto installation service for kernel 4.15.0-69-generic
   ...done.
**** Kernel headers seem to be present, attempting to build the wireguard module. . . ****
**** Generating signing key ****
Generating a RSA private key
...................++++
...................................................................................................................................++++
writing new private key to 'signing_key.pem'
-----
**** Building the module ****
make: Entering directory '/app/wireguard-linux-compat/src'
  CC [M]  /app/wireguard-linux-compat/src/main.o
  CC [M]  /app/wireguard-linux-compat/src/noise.o
  CC [M]  /app/wireguard-linux-compat/src/device.o
  CC [M]  /app/wireguard-linux-compat/src/peer.o
  CC [M]  /app/wireguard-linux-compat/src/timers.o
  CC [M]  /app/wireguard-linux-compat/src/queueing.o
  CC [M]  /app/wireguard-linux-compat/src/send.o
  CC [M]  /app/wireguard-linux-compat/src/receive.o
  CC [M]  /app/wireguard-linux-compat/src/socket.o
/app/wireguard-linux-compat/src/socket.c: In function ‘send6’:
/app/wireguard-linux-compat/src/socket.c:139:20: error: ‘const struct ipv6_stub’ has no member named ‘ipv6_dst_lookup_flow’; did you mean ‘ipv6_dst_lookup’?
   dst = ipv6_stub->ipv6_dst_lookup_flow(sock_net(sock), sock, &fl,
                    ^~~~~~~~~~~~~~~~~~~~
                    ipv6_dst_lookup
scripts/Makefile.build:330: recipe for target '/app/wireguard-linux-compat/src/socket.o' failed
make[2]: *** [/app/wireguard-linux-compat/src/socket.o] Error 1
Makefile:1577: recipe for target '_module_/app/wireguard-linux-compat/src' failed
make[1]: *** [_module_/app/wireguard-linux-compat/src] Error 2
Makefile:25: recipe for target 'module' failed
make: *** [module] Error 2
make: Leaving directory '/app/wireguard-linux-compat/src'
make: Entering directory '/app/wireguard-linux-compat/src'
  DEPMOD  4.15.0-69-generic
depmod -a 4.15.0-69-generic
make: Leaving directory '/app/wireguard-linux-compat/src'
**** Let's test our new module. ****
[!] Warning: This server is for testing purposes only. You may not use this server for abusive or illegal purposes.
[+] Generating private key.
[+] Sending public key to server.
[+] Parsing server response.
[+] Writing config file.
[+] Success. Run `wg-quick up demo` to turn on the tunnel to the demo server and `wg-quick down demo` to turn it off.
[#] ip link add demo type wireguard
RTNETLINK answers: Operation not supported
Unable to access interface: Protocol not supported
[#] ip link delete dev demo
Cannot find device "demo"
wg-quick: `demo' is not a WireGuard interface
**** The module is not working, review the logs. Sleeping now. . . ****

**Comment by j0nnymoe** [comment]
Try installing the binaries from http://get.docker.com first rather than the ones included in the ubuntu repos and try again.

**Comment by j0nnymoe** [comment]
Closing due to no response.

**Comment by SannanKhalid13** [comment]
I'm having the same above mentioned issue and my output is the same 
I also tried the binaries as mentioned but it didn't helped

**Comment by SannanKhalid13** [comment]
I was having the same issue but it was resolved after i mapped the /usr/src in volumes 
```
volumes:
    - /usr/src:/usr/src
```

**Comment by guillermolg00** [comment]
Hello, I am trying to create a double vpn tunnel in a vps server, therefore I am trying to have two containers, one with the configuration of a wireguard client and the other with a server configuration.

In my case I am using the client on the network host.

The server container works perfectly but the client container shows me an error
`RTNETLINK answers: Operation not permitted`

This are the logs:
`wg-client    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
wg-client    | [s6-init] ensuring user provided files have correct perms...exited 0.
wg-client    | [fix-attrs.d] applying ownership & permissions fixes...
wg-client    | [fix-attrs.d] done.
wg-client    | [cont-init.d] executing container initialization scripts...
wg-client    | [cont-init.d] 01-envfile: executing...
wg-client    | [cont-init.d] 01-envfile: exited 0.
wg-client    | [cont-init.d] 01-migrations: executing...
wg-client    | [migrations] started
wg-client    | [migrations] no migrations found
wg-client    | [cont-init.d] 01-migrations: exited 0.
wg-client    | [cont-init.d] 10-adduser: executing...
wg-client    | usermod: no changes
wg-client    |
wg-client    | -------------------------------------
wg-client    |           _         ()
wg-client    |          | |  ___   _    __
wg-client    |          | | / __| | |  /  \
wg-client    |          | | \__ \ | | | () |
wg-client    |          |_| |___/ |_|  \__/
wg-client    |
wg-client    |
wg-client    | Brought to you by linuxserver.io
wg-client    | -------------------------------------
wg-client    |
wg-client    | To support the app dev(s) visit:
wg-client    | WireGuard: https://www.wireguard.com/donations/
wg-client    |
wg-client    | To support LSIO projects visit:
wg-client    | https://www.linuxserver.io/donate/
wg-client    | -------------------------------------
wg-client    | GID/UID
wg-client    | -------------------------------------
wg-client    |
wg-client    | User uid:    911
wg-client    | User gid:    911
wg-client    | -------------------------------------
wg-client    |
wg-client    | [cont-init.d] 10-adduser: exited 0.
wg-client    | [cont-init.d] 30-module: executing...
wg-client    | Uname info: Linux srv32119-206152.vps.etecsa.cu 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
wg-client    | RTNETLINK answers: Operation not permitted
wg-client    | **** The wireguard module is not active, will attempt kernel header install and module compilation. ****
wg-client    | **** Kernel headers seem to be present, attempting to build the wireguard module. . . ****
wg-client    | **** Generating signing key ****
wg-client    | Generating a RSA private key
wg-client    | ..................++++
wg-client    | ......................................................................................++++
wg-client    | writing new private key to 'signing_key.pem'
wg-client    | -----
wg-client    | **** Building the module ****
wg-client    | make: Entering directory '/app/wireguard-linux-compat/src'
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/noise.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/main.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/device.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/peer.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/timers.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/queueing.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/send.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/receive.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/socket.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/peerlookup.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/allowedips.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/ratelimiter.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/cookie.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/netlink.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/crypto/zinc/chacha20/chacha20.o
wg-client    |   PERLASM /app/wireguard-linux-compat/src/crypto/zinc/chacha20/chacha20-x86_64.S
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/crypto/zinc/poly1305/poly1305.o
wg-client    |   PERLASM /app/wireguard-linux-compat/src/crypto/zinc/poly1305/poly1305-x86_64.S
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/crypto/zinc/chacha20poly1305.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/crypto/zinc/blake2s/blake2s.o
wg-client    |   AS [M]  /app/wireguard-linux-compat/src/crypto/zinc/blake2s/blake2s-x86_64.o
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/crypto/zinc/curve25519/curve25519.o
wg-client    |   AS [M]  /app/wireguard-linux-compat/src/crypto/zinc/chacha20/chacha20-x86_64.o
wg-client    |   AS [M]  /app/wireguard-linux-compat/src/crypto/zinc/poly1305/poly1305-x86_64.o
wg-client    |   LD [M]  /app/wireguard-linux-compat/src/wireguard.o
wg-client    |   Building modules, stage 2.
wg-client    |   MODPOST 1 modules
wg-client    |   CC [M]  /app/wireguard-linux-compat/src/wireguard.mod.o
wg-client    |   LD [M]  /app/wireguard-linux-compat/src/wireguard.ko
wg-client    | make: Leaving directory '/app/wireguard-linux-compat/src'
wg-client    | make: Entering directory '/app/wireguard-linux-compat/src'
wg-client    |   INSTALL /app/wireguard-linux-compat/src/wireguard.ko
wg-client    |   DEPMOD  5.4.0-96-generic
wg-client    | Warning: modules_install: missing 'System.map' file. Skipping depmod.
wg-client    | depmod -b "/" -a 5.4.0-96-generic
wg-client    | make: Leaving directory '/app/wireguard-linux-compat/src'
wg-client    | **** Let's test our new module. ****
wg-client    | RTNETLINK answers: Operation not permitted
wg-client    | **** The module is not active, review the logs. Sleeping now. . . ****`

and this is my compose file:
`version: '3.3'
services:
  wg-client:
    image: ghcr.io/linuxserver/wireguard
    container_name: wg-client
    network_mode: host
    volumes:
      - /path/to/appdata/config:/config
      - /lib/modules:/lib/modules
      - ./configClient/wg0.conf:/config/wg0.conf
      - /usr/src:/usr/src
    restart: unless-stopped

  wg-server:
    image: ghcr.io/linuxserver/wireguard
    container_name: wg-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL= #optional
      - SERVERPORT=51820 #optional
      - PEERS=20 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped`

**Comment by tandav** [comment]
I was having the same issue and was fixed by updating docker, docker-compose. Also you can try update ubuntu

**Comment by ClemTheStudent** [comment]
Just add this:
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
