### ISSUE TITLE
error: ‘const struct ipv6_stub’

### ISSUE THREAD

**Issue by JD99** [linuxserver/docker-wireguard#46]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Steps to Reproduce

1. run docker-compose up --build  -d
 

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

## Docker logs

writing new private key to 'signing_key.pem'
-----
**** Building the module ****
make: Entering directory '/app/wireguard-linux-compat/src'
  CC [M]  /app/wireguard-linux-compat/src/noise.o
  CC [M]  /app/wireguard-linux-compat/src/main.o
  CC [M]  /app/wireguard-linux-compat/src/device.o
  CC [M]  /app/wireguard-linux-compat/src/peer.o
  CC [M]  /app/wireguard-linux-compat/src/timers.o
  CC [M]  /app/wireguard-linux-compat/src/queueing.o
  CC [M]  /app/wireguard-linux-compat/src/send.o
  CC [M]  /app/wireguard-linux-compat/src/receive.o
  CC [M]  /app/wireguard-linux-compat/src/socket.o
  CC [M]  /app/wireguard-linux-compat/src/peerlookup.o
/app/wireguard-linux-compat/src/socket.c: In function ‘send6’:
/app/wireguard-linux-compat/src/socket.c:139:20: error: ‘const struct ipv6_stub’ has no member named ‘ipv6_dst_lookup_flow’; did you mean ‘ipv6_dst_lookup’?
   dst = ipv6_stub->ipv6_dst_lookup_flow(sock_net(sock), sock, &fl,
                    ^~~~~~~~~~~~~~~~~~~~
                    ipv6_dst_lookup
scripts/Makefile.build:330: recipe for target '/app/wireguard-linux-compat/src/socket.o' failed
make[2]: *** [/app/wireguard-linux-compat/src/socket.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:1577: recipe for target '_module_/app/wireguard-linux-compat/src' failed
make[1]: *** [_module_/app/wireguard-linux-compat/src] Error 2
Makefile:25: recipe for target 'module' failed
make: *** [module] Error 2
make: Leaving directory '/app/wireguard-linux-compat/src'
make: Entering directory '/app/wireguard-linux-compat/src'
  DEPMOD  4.15.0-96-generic
depmod -a 4.15.0-96-generic
make: Leaving directory '/app/wireguard-linux-compat/src'
**** Let's test our new module. ****
RTNETLINK answers: Operation not supported
**** The module is not active, review the logs. Sleeping now. . . ****

**Comment by aptalca** [comment]
do apt update/upgrade and restart

**Comment by Enissay** [comment]
Issue still exists. Any fix please ?

I am all up to date running `Linux devnode 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux`

**Comment by Enissay** [comment]
Any help please ?
My vpn is down for over 2 months now because of this :-/

**Comment by nickaein** [comment]
@Enissay 

I fixed the issue by building wireguard from the source: https://www.wireguard.com/compilation

I just had to switch to an older release. For this purpose, after **Step 2: Grab the code** run the following commands:

```
cd wireguard-linux-compat
git checkout v1.0.20200520
cd ..
```
The other steps are pretty straightforward to follow. 

If you still had any problems during complication, instead of `v1.0.20200520` you can try other tags listed at https://git.zx2c4.com/wireguard-linux-compat/refs/ to see which one works for your VM.
