### ISSUE TITLE
51820 is exposed regardless of settings

### ISSUE THREAD

**Issue by ThellraAK** [linuxserver/docker-wireguard#53]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Setting the port in the       - SERVERPORT=51821 #optional as well as the     ports:
      - 51821:51821/udp should result in the server listening on that port

## Current Behavior
`a78d1d056fc7        linuxserver/wireguard     "/init"             2 minutes ago       Up 2 minutes            51820/udp, 0.0.0.0:51821->51821/udp                            wireguard2
e47149b49b75        linuxserver/wireguard     "/init"             43 minutes ago      Up 43 minutes           0.0.0.0:51820->51820/udp                                       wireguard
`
Server attempts  to listen on the default port even if you tell it not to.
## Steps to Reproduce
Create wireguard as instructed by documents
Create wireguard2 as instructed by documents, changing instances of 51820 to 51821

Attempt to connect to wireguard2 using the provided configs

## Environment
**OS:**      20.04.01 
**CPU architecture:** x86_64
**How docker service was installed:** docker-compose.yml     

on the dockerfile on the last line, it says EXPOSE 51820/udp when it should probably be taking an arguement from the config or something
## Command used to create docker container (run/create/compose/screenshot)

`  wireguard2:
    image: linuxserver/wireguard
    container_name: wireguard2
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - SERVERURL= myurl.tld
      - SERVERPORT=51821 #optional
      - PEERS=2 #optional
      - PEERDNS=10.10.10.200 #optiol
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - /config/wireguard2:/config
      - /lib/modules:/lib/modules
    ports:
      - 51821:51821/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      app_net:
        ipv4_address: 10.10.10.222
    restart: unless-stopped`

`wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - SERVERURL=myhost.tld #optional
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=10.10.10.200 #optiol
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - /config/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      app_net:
        ipv4_address: 10.10.10.221
    restart: unless-stopped`

## Docker logs

`@omnibus:/config/wireguard2$ docker ps
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS                  PORTS                                                          NAMES
a78d1d056fc7        linuxserver/wireguard     "/init"             2 minutes ago       Up 2 minutes            51820/udp, 0.0.0.0:51821->51821/udp                            wireguard2
e47149b49b75        linuxserver/wireguard     "/init"             43 minutes ago      Up 43 minutes           0.0.0.0:51820->51820/udp                                       wireguard
`

**Comment by aptalca** [comment]
`SERVER_PORT` is only for setting the external port (wan port) so the correct info can be put into the peer/client confs for external connections. It has no bearing on what port wireguard listens on internally. 

The internal port is hardcoded to 51820, but you can map it to another port via `-p 51821:51820`, and/or port forward a different wan port on your router/firewall.

**Comment by ThellraAK** [comment]
@aptalca then what is   -e SERVERPORT=51820 `#optional` \ for?

**Comment by aptalca** [comment]
I don't follow. I literally just explained it right above your post. Although I made a typo: ~~`SERVER_PORT`~~`SERVERPORT`
