### ISSUE TITLE
ORIG_SERVERPORT=#SERVER_PORT bug

### ISSUE THREAD

**Issue by tynor88** [linuxserver/docker-wireguard#7]
https://github.com/linuxserver/docker-wireguard/blob/972e13cff089c340f48fbb1bb7048b93533e87d9/root/etc/cont-init.d/30-config#L115

Should be 
`ORIG_SERVERPORT=$SERVER_PORT `
to prevent code from regenrating wg0.conf

**Comment by nemchik** [comment]
Thanks! PR created to fix.
