### ISSUE TITLE
wireguard docker won't run because of issue with socket.c file

### ISSUE THREAD

**Issue by sonbyj01** [linuxserver/docker-wireguard#74]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

The docker should generate peer config files.

## Current Behavior

The docker does not generate peer config files.

## Steps to Reproduce

1. Run the docker-compose.yaml that's posted on the site.

## Environment
**OS:** Debian 10
**CPU architecture:** x86_64
**How docker service was installed:**

From the official docker repo. 

## Command used to create docker container (run/create/compose/screenshot)

docker-compose up -d

## Potentially useful information
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959157

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Uname info: Linux f75cd96521c9 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 x86_64 x86_64 GNU/Linux
RTNETLINK answers: Operation not supported
**** The wireguard module is not active, will attempt kernel header install and module compilation. ****
**** Attempting kernel header install ****
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/restricted Sources [5,823 B]
Get:5 http://archive.ubuntu.com/ubuntu bionic/multiverse Sources [216 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/main Sources [1,063 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Sources [11.6 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Sources [18.4 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [621 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [547 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [231 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [45.5 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,112 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2,150 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-security/universe Sources [331 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-security/multiverse Sources [4,352 B]
Get:22 http://archive.ubuntu.com/ubuntu bionic-security/main Sources [298 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-security/restricted Sources [13.0 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [205 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [15.0 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1,733 kB]
Get:27 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,348 kB]
Fetched 35.8 MB in 10s (3,606 kB/s)
Reading package lists...
**** Debian host detected, attempting to install kernel headers from Debian Buster repo ****
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Get:4 http://deb.debian.org/debian buster InRelease [121 kB]
Get:5 http://deb.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:6 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:7 http://deb.debian.org/debian buster-backports InRelease [46.7 kB]
Get:8 http://deb.debian.org/debian buster/contrib Sources [50.8 kB]
Get:9 http://deb.debian.org/debian buster/non-free Sources [104 kB]
Get:10 http://deb.debian.org/debian buster/main Sources [10.4 MB]
Get:11 http://deb.debian.org/debian buster/contrib amd64 Packages [60.7 kB]
Get:12 http://deb.debian.org/debian buster/main amd64 Packages [10.7 MB]
Get:13 http://deb.debian.org/debian buster/non-free amd64 Packages [107 kB]
Get:14 http://deb.debian.org/debian-security buster/updates/main Sources [190 kB]
Get:15 http://deb.debian.org/debian-security buster/updates/non-free Sources [610 B]
Get:16 http://deb.debian.org/debian-security buster/updates/non-free amd64 Packages [486 B]
Get:17 http://deb.debian.org/debian-security buster/updates/main amd64 Packages [295 kB]
Get:18 http://deb.debian.org/debian buster-updates/non-free Sources [638 B]
Get:19 http://deb.debian.org/debian buster-updates/main Sources [3,966 B]
Get:20 http://deb.debian.org/debian buster-updates/main amd64 Packages [8,791 B]
Get:21 http://deb.debian.org/debian buster-updates/non-free amd64 Packages [529 B]
Get:22 http://deb.debian.org/debian buster-backports/contrib Sources [4,220 B]
Get:23 http://deb.debian.org/debian buster-backports/main Sources [352 kB]
Get:24 http://deb.debian.org/debian buster-backports/non-free Sources [8,240 B]
Get:25 http://deb.debian.org/debian buster-backports/contrib amd64 Packages [7,788 B]
Get:26 http://deb.debian.org/debian buster-backports/main amd64 Packages [355 kB]
Get:27 http://deb.debian.org/debian buster-backports/non-free amd64 Packages [27.5 kB]
Fetched 23.0 MB in 11s (2,122 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  cpp-8 gcc-8 libasan5 libgcc-8-dev libubsan1 linux-compiler-gcc-8-x86
  linux-headers-4.19.0-8-common linux-kbuild-4.19
Suggested packages:
  gcc-8-locales gcc-8-multilib gcc-8-doc libgcc1-dbg libgomp1-dbg libitm1-dbg
  libatomic1-dbg libasan5-dbg liblsan0-dbg libtsan0-dbg libubsan1-dbg
  libmpx2-dbg libquadmath0-dbg
The following NEW packages will be installed:
  cpp-8 gcc-8 libasan5 libgcc-8-dev libubsan1 linux-compiler-gcc-8-x86
  linux-headers-4.19.0-8-amd64 linux-headers-4.19.0-8-common linux-kbuild-4.19
0 upgraded, 9 newly installed, 0 to remove and 183 not upgraded.
Need to get 28.5 MB of archives.
After this operation, 127 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 linux-compiler-gcc-8-x86 amd64 4.19.146-1 [476 kB]
Get:2 http://deb.debian.org/debian-security buster/updates/main amd64 linux-headers-4.19.0-8-common all 4.19.98-1+deb10u1 [8,329 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 linux-kbuild-4.19 amd64 4.19.146-1 [709 kB]
Get:4 http://deb.debian.org/debian-security buster/updates/main amd64 linux-headers-4.19.0-8-amd64 amd64 4.19.98-1+deb10u1 [879 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 cpp-8 amd64 8.4.0-1ubuntu1~18.04 [7,225 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libasan5 amd64 8.4.0-1ubuntu1~18.04 [366 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libubsan1 amd64 8.4.0-1ubuntu1~18.04 [122 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgcc-8-dev amd64 8.4.0-1ubuntu1~18.04 [2,305 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 gcc-8 amd64 8.4.0-1ubuntu1~18.04 [8,044 kB]
Fetched 28.5 MB in 7s (3,906 kB/s)
Selecting previously unselected package cpp-8.
(Reading database ... 14293 files and directories currently installed.)
Preparing to unpack .../0-cpp-8_8.4.0-1ubuntu1~18.04_amd64.deb ...
Unpacking cpp-8 (8.4.0-1ubuntu1~18.04) ...
Selecting previously unselected package libasan5:amd64.
Preparing to unpack .../1-libasan5_8.4.0-1ubuntu1~18.04_amd64.deb ...
Unpacking libasan5:amd64 (8.4.0-1ubuntu1~18.04) ...
Selecting previously unselected package libubsan1:amd64.
Preparing to unpack .../2-libubsan1_8.4.0-1ubuntu1~18.04_amd64.deb ...
Unpacking libubsan1:amd64 (8.4.0-1ubuntu1~18.04) ...
Selecting previously unselected package libgcc-8-dev:amd64.
Preparing to unpack .../3-libgcc-8-dev_8.4.0-1ubuntu1~18.04_amd64.deb ...
Unpacking libgcc-8-dev:amd64 (8.4.0-1ubuntu1~18.04) ...
Selecting previously unselected package gcc-8.
Preparing to unpack .../4-gcc-8_8.4.0-1ubuntu1~18.04_amd64.deb ...
Unpacking gcc-8 (8.4.0-1ubuntu1~18.04) ...
Selecting previously unselected package linux-compiler-gcc-8-x86.
Preparing to unpack .../5-linux-compiler-gcc-8-x86_4.19.146-1_amd64.deb ...
Unpacking linux-compiler-gcc-8-x86 (4.19.146-1) ...
Selecting previously unselected package linux-headers-4.19.0-8-common.
Preparing to unpack .../6-linux-headers-4.19.0-8-common_4.19.98-1+deb10u1_all.deb ...
Unpacking linux-headers-4.19.0-8-common (4.19.98-1+deb10u1) ...
Selecting previously unselected package linux-kbuild-4.19.
Preparing to unpack .../7-linux-kbuild-4.19_4.19.146-1_amd64.deb ...
Unpacking linux-kbuild-4.19 (4.19.146-1) ...
Selecting previously unselected package linux-headers-4.19.0-8-amd64.
Preparing to unpack .../8-linux-headers-4.19.0-8-amd64_4.19.98-1+deb10u1_amd64.deb ...
Unpacking linux-headers-4.19.0-8-amd64 (4.19.98-1+deb10u1) ...
Setting up cpp-8 (8.4.0-1ubuntu1~18.04) ...
Setting up linux-kbuild-4.19 (4.19.146-1) ...
Setting up linux-headers-4.19.0-8-common (4.19.98-1+deb10u1) ...
Setting up libasan5:amd64 (8.4.0-1ubuntu1~18.04) ...
Setting up libubsan1:amd64 (8.4.0-1ubuntu1~18.04) ...
Setting up libgcc-8-dev:amd64 (8.4.0-1ubuntu1~18.04) ...
Setting up gcc-8 (8.4.0-1ubuntu1~18.04) ...
Setting up linux-compiler-gcc-8-x86 (4.19.146-1) ...
Setting up linux-headers-4.19.0-8-amd64 (4.19.98-1+deb10u1) ...
/etc/kernel/header_postinst.d/dkms:
 * dkms: running auto installation service for kernel 4.19.0-8-amd64
   ...done.
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
**** Kernel headers seem to be present, attempting to build the wireguard module. . . ****
**** Generating signing key ****
Generating a RSA private key
..............................................................................................................................++++
.......................++++
writing new private key to 'signing_key.pem'
-----
**** Building the module ****
make: Entering directory '/app/wireguard-linux-compat/src'
  CC [M]  /app/wireguard-linux-compat/src/main.o
  CC [M]  /app/wireguard-linux-compat/src/noise.o
  CC [M]  /app/wireguard-linux-compat/src/device.o
  CC [M]  /app/wireguard-linux-compat/src/peer.o
  CC [M]  /app/wireguard-linux-compat/src/timers.o
  CC [M]  /app/wireguard-linux-compat/src/queueing.o
  CC [M]  /app/wireguard-linux-compat/src/send.o
  CC [M]  /app/wireguard-linux-compat/src/receive.o
  CC [M]  /app/wireguard-linux-compat/src/socket.o
  CC [M]  /app/wireguard-linux-compat/src/peerlookup.o
  CC [M]  /app/wireguard-linux-compat/src/allowedips.o
  CC [M]  /app/wireguard-linux-compat/src/ratelimiter.o
/app/wireguard-linux-compat/src/socket.c: In function ‘send6’:
/app/wireguard-linux-compat/src/socket.c:139:20: error: ‘const struct ipv6_stub’ has no member named ‘ipv6_dst_lookup_flow’; did you mean ‘ipv6_dst_lookup’?
   dst = ipv6_stub->ipv6_dst_lookup_flow(sock_net(sock), sock, &fl,
                    ^~~~~~~~~~~~~~~~~~~~
                    ipv6_dst_lookup
/usr/src/linux-headers-4.19.0-8-common/scripts/Makefile.build:308: recipe for target '/app/wireguard-linux-compat/src/socket.o' failed
make[4]: *** [/app/wireguard-linux-compat/src/socket.o] Error 1
make[4]: *** Waiting for unfinished jobs....
/usr/src/linux-headers-4.19.0-8-common/Makefile:1537: recipe for target '_module_/app/wireguard-linux-compat/src' failed
make[3]: *** [_module_/app/wireguard-linux-compat/src] Error 2
Makefile:146: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
make[1]: *** [all] Error 2
Makefile:8: recipe for target 'all' failed
Makefile:26: recipe for target 'module' failed
make: Leaving directory '/app/wireguard-linux-compat/src'
make: *** [module] Error 2
make: Entering directory '/app/wireguard-linux-compat/src'
  DEPMOD  4.19.0-8-amd64
Warning: modules_install: missing 'System.map' file. Skipping depmod.
depmod -b "/" -a 4.19.0-8-amd64
make: Leaving directory '/app/wireguard-linux-compat/src'
**** Let's test our new module. ****
RTNETLINK answers: Operation not supported
**** The module is not active, review the logs. Sleeping now. . . ****

**Comment by aptalca** [comment]
Do the usual apt update/upgrade on host and reboot, try again

**Comment by sonbyj01** [comment]
Ah thank you, that resolved the issue!
