### ISSUE TITLE
Confusing version tags

### ISSUE THREAD

**Issue by bonanitech** [linuxserver/docker-wireguard#80]
This is probably not that important, but I'm a little confused by the tags of the latest versions.

We had [v1.0.20200827-ls43](https://github.com/linuxserver/docker-wireguard/releases/tag/v1.0.20200827-ls43), [v1.0.20200827-ls1](https://github.com/linuxserver/docker-wireguard/releases/tag/v1.0.20200827-ls1), and today [v1.0.20200827-ls2](https://github.com/linuxserver/docker-wireguard/releases/tag/v1.0.20200827-ls2).

Shouldn't these last two end in ls44 and ls45?

**Comment by aptalca** [comment]
They should, but the process we use to get the latest build number failed right here: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-wireguard/detail/master/94/pipeline/17#step-20-log-5
This right is the code for that process: https://github.com/linuxserver/docker-wireguard/blob/master/Jenkinsfile#L43-L45

**Comment by bonanitech** [comment]
Thanks for the feedback.
