### ISSUE TITLE
QR Code not working

### ISSUE THREAD

**Issue by cltw666** [linuxserver/docker-wireguard#81]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

QR code should be scannable

## Current Behavior

![image](https://user-images.githubusercontent.com/45290547/100491379-e940f500-315d-11eb-8629-9f29e4e369bb.png)

## Steps to Reproduce

1. Installed docker on Windows 10 LTSC 2019
2. Pulled latest wireguard from hub
3. Created container with 3 peers
4. All peers QR code doesn't look right

## Environment
**OS:** Windows 10 LTSC 2019
**CPU architecture:** x86_64
**How docker service was installed:** Docker official repo

## Command used to create docker container (run/create/compose/screenshot)

 docker run -d --name=wireguard-server --cap-add=NET_ADMIN --cap-add=SYS_MODULE -e PUID=1000 -e PGID=1000 -e TZ=Australia/Perth -e SERVERURL=XXXXX.ddns.net -e SERVERPORT=51820 -e PEERS=Phone1,Phone2,Tablet1 -e PEERDNS=10.1.1.250 -e INTERNAL_SUBNET=10.13.13.0 -e ALLOWEDIPS=0.0.0.0/0 -p 51820:51820/udp -v /path/to/appdata/config:/config -v /lib/modules:/lib/modules --sysctl="net.ipv4.conf.all.src_valid_mark=1" --restart unless-stopped linuxserver/wireguard

NOTE: 10.1.1.250 is local PiHole service

## Docker logs

Not sure how to get logs.

**Comment by cltw666** [comment]
I have copied the png file from /config/peer_Phone1/peer_Phone1.png and it works.

Hopefully, this thread could be useful to others. Thanks.

**Comment by anoma** [comment]
I looks like something is truncating your logs at a fixed width. At a guess this is related to `Windows 10 LTSC 2019` as it is not a platform we test on.

Suggest you copy and paste the logs into a text editor, count the characters until cut off and see if google makes a suggestion.

**Comment by marleyjaffe** [comment]
i use the [imgcat cli app](https://pypi.org/project/imgcat/) to view the .png. When I load it this way, my iPhone always scans instantly.
