### ISSUE TITLE
Preserving existing peer configurations when modifying PEERS

### ISSUE THREAD

**Issue by rocwhite123** [linuxserver/docker-wireguard#86]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

When adding/removing clients to the PEERS variable, configurations for unmodified clients stay the same.

## Current Behavior

Whenever PEERS is modified, all existing clients without the corresponding private keys need to update. This becomes very difficult to do when one has set up a number of stable clients but need to add/remove clients on a ongoing basis.

## Alternatives Considered

1) Manually edit `config/wg0.conf`, which isn't ideal as it is no longer in sync with the docker setup.
2) Zero out the `privatekey-peer_ABC` file instead of deleting it.

**Comment by aptalca** [comment]
`Whenever PEERS is modified, all existing clients need to update.` That is not the case here. You need to clarify your changes and observation.

**Comment by rocwhite123** [comment]
> 
> 
> `Whenever PEERS is modified, all existing clients need to update.` That is not the case here. You need to clarify your changes and observation.

Yes, you're correct. I was just looking into the code, and realized that what I stated was not exactly the case. I deleted all files containing the private keys from the corresponding client folder. I think the code should check for publickey instead of privatekey for each peer.

**Comment by aptalca** [comment]
The code uses the private key to re/generate the peer/client confs whenever the other env vars are modified. It can't do that if you delete the private keys

**Comment by rocwhite123** [comment]
I'm trying to think of a good workflow without keeping the private keys for each peer on the server. Can one assume if a peer folder and client's public key are intact, then the configurations don't need to be regenerated?

**Comment by aptalca** [comment]
No, they need to be regenerated if one changes the server address, port, dns , etc., any of which would need to update the peer/client confs

**Comment by rocwhite123** [comment]
Ah, OK, so there is no good way to do that without changing the other logic. I'm closing this FR then.

**Comment by aptalca** [comment]
Yeah, this is the best we got with a bunch of bash scripts. If it was a full app with a db backend, things would be different.
