### ISSUE TITLE
Can't get Client browse either the local network or the internet

### ISSUE THREAD

**Issue by JohnGalt1717** [linuxserver/docker-wireguard#9]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
Android phone connected to server successfully should be able to browse both local servers and the internet

## Current Behavior
Client connects fine gets 10.13.13.2 as an address from wireguard.
Doesn't appear to get a gateway nor be able to browse across the network

## Steps to Reproduce
1. Fired up with defaults, but 5 peers.
2. Opened the port on my firewall and forwarded it to the ip of the host
3. Downloaded the android client
4. Scanned the Q/R Code.
5. Tried to browse the internet - Nothing
6. Tried to browse local by ip - Nothing
7. Used nettools to ping local by ip - nothing

## Environment
Linux Ubuntu 19.10 Host
**CPU architecture:** x86_64
**How docker service was installed:**      
apt install docker.io

## Command used to create docker container (run/create/compose/screenshot)
version: "3.0"
services:
  wireguard-server:
    image: linuxserver/wireguard
    container_name: wireguard-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Americas/New_York
      - SERVERURL=vpn.\<redacted\> #optional
      - SERVERPORT=51820 #optional
      - PEERS=5 #optional
      - PEERDNS=\<Internal IP Range\>.1 #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

## Logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1002
User gid:    1002
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Get:1 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic InRelease [15.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main Sources [1,170 B]
Get:4 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main amd64 Packages [924 B]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/multiverse Sources [216 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/restricted Sources [5,823 B]
Get:10 http://archive.ubuntu.com/ubuntu bionic/main Sources [1,063 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Sources [8,069 B]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [368 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [403 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Sources [6,197 B]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,371 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [12.6 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1,183 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [59.0 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-security/main Sources [187 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-security/multiverse Sources [3,232 B]
Get:25 http://archive.ubuntu.com/ubuntu bionic-security/universe Sources [215 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-security/restricted Sources [5,440 B]
Get:27 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [889 kB]
Get:28 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [839 kB]
Get:29 http://archive.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [44.6 kB]
Get:30 http://archive.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [8,213 B]
Fetched 31.7 MB in 4s (8,438 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  linux-headers-5.3.0-46 wireguard-dkms wireguard-tools
The following NEW packages will be installed:
  linux-headers-5.3.0-46 linux-headers-5.3.0-46-generic wireguard
  wireguard-dkms wireguard-tools
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 12.6 MB of archives.
After this operation, 86.5 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main amd64 wireguard-dkms all 1.0.20200401-1ubuntu1~18.04 [253 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-headers-5.3.0-46 all 5.3.0-46.38~18.04.1 [11.0 MB]
Get:3 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main amd64 wireguard-tools amd64 1.0.20200319-0ppa1~18.04 [88.2 kB]
Get:4 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic/main amd64 wireguard all 1.0.20200319-0ppa1~18.04 [7,980 B]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-headers-5.3.0-46-generic amd64 5.3.0-46.38~18.04.1 [1,198 kB]
Fetched 12.6 MB in 2s (6,542 kB/s)
Selecting previously unselected package linux-headers-5.3.0-46.
(Reading database ... 45886 files and directories currently installed.)
Preparing to unpack .../linux-headers-5.3.0-46_5.3.0-46.38~18.04.1_all.deb ...
Unpacking linux-headers-5.3.0-46 (5.3.0-46.38~18.04.1) ...
Selecting previously unselected package linux-headers-5.3.0-46-generic.
Preparing to unpack .../linux-headers-5.3.0-46-generic_5.3.0-46.38~18.04.1_amd64.deb ...
Unpacking linux-headers-5.3.0-46-generic (5.3.0-46.38~18.04.1) ...
Selecting previously unselected package wireguard-dkms.
Preparing to unpack .../wireguard-dkms_1.0.20200401-1ubuntu1~18.04_all.deb ...
Unpacking wireguard-dkms (1.0.20200401-1ubuntu1~18.04) ...
Selecting previously unselected package wireguard-tools.
Preparing to unpack .../wireguard-tools_1.0.20200319-0ppa1~18.04_amd64.deb ...
Unpacking wireguard-tools (1.0.20200319-0ppa1~18.04) ...
Selecting previously unselected package wireguard.
Preparing to unpack .../wireguard_1.0.20200319-0ppa1~18.04_all.deb ...
Unpacking wireguard (1.0.20200319-0ppa1~18.04) ...
Setting up linux-headers-5.3.0-46 (5.3.0-46.38~18.04.1) ...
Setting up wireguard-dkms (1.0.20200401-1ubuntu1~18.04) ...
Loading new wireguard-1.0.20200401 DKMS files...
It is likely that 5.3.0-46-generic belongs to a chroot's host
Building for 5.3.0-18-generic and 5.3.0-46-generic
Module build for kernel 5.3.0-18-generic was skipped since the
kernel headers for this kernel does not seem to be installed.
Building initial module for 5.3.0-46-generic
Done.

wireguard:
Running module version sanity check.

Good news! Module version 1.0.20200401 for wireguard.ko
exactly matches what is already found in kernel 5.3.0-46-generic.
DKMS will not replace this module.
You may override by specifying --force.

depmod...

DKMS: install completed.
Setting up wireguard-tools (1.0.20200319-0ppa1~18.04) ...
Setting up wireguard (1.0.20200319-0ppa1~18.04) ...
Setting up linux-headers-5.3.0-46-generic (5.3.0-46.38~18.04.1) ...
/etc/kernel/header_postinst.d/dkms:
 * dkms: running auto installation service for kernel 5.3.0-46-generic
   ...done.
Server mode is selected
External server address is set to vpn.\<redacted\>
External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container
Internal subnet is set to 10.13.13.0
Peer DNS servers will be set to \<Internal IP Range\>.1
Server mode is selected
Server related environment variables changed, regenerating 1 server and 5 peer/client confs
PEER 1 QR code: (image)

PEER 2 QR code: (image)

PEER 3 QR code: (image)

PEER 4 QR code: (image)

PEER 5 QR code: (image)

[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Warning: `/config/wg0.conf' is world accessible
.:53
CoreDNS-1.6.9
linux/amd64, go1.14.1, 1766568
[services.d] done.
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.13.13.1 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] ip -4 route add 10.13.13.6/32 dev wg0
[#] ip -4 route add 10.13.13.5/32 dev wg0
[#] ip -4 route add 10.13.13.4/32 dev wg0
[#] ip -4 route add 10.13.13.3/32 dev wg0
[#] ip -4 route add 10.13.13.2/32 dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

**Comment by aptalca** [comment]
Check the android client logs
Also check `docker exec -it wireguard-server wg show` on the server host to see if they completed a handshake
If no handshake, likely issue with server url and/or port

**Comment by JohnGalt1717** [comment]
I found the issue. It was my router wasn't set for nat reflection which apparently is required for this to work right. You might want to make a note.

**Comment by aptalca** [comment]
Nat reflection? Were you trying to connect to a wireguard server on the same lan via domain name?

**Comment by JohnGalt1717** [comment]
For it to be useful on a phone it has to be able to be able to go between LTE/5G and local wireless.  Otherwise it would just be annoying constantly having to turn it off and on.
