### ISSUE TITLE
Kernel headers not available

### ISSUE THREAD

**Issue by cobusvanzyl** [linuxserver/docker-wireguard#90]
Trying to install Wireguard on a Raspberry Pi running Docker and Portainer. I have several other containers running successfully on the Pi. However when looking at the log the installation does not seem to complete as some headers are missing.

------------------------------

## Expected Behavior
I am trying to install Wireguard using the instruction in the readme

## Current Behavior
When installing the stack via docker-compose the installation does not complete, I get the error "**** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ****"
I have done a sudo apt-get update && upgrade, did not help.
I searched the other reported issues and followed the recommendations in other posts with similar issues.

## Environment
uname -a
Linux raspberrypi 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux

## Command used to create docker container (run/create/compose/screenshot)
version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - SERVERURL=*******.duckdns.org
      - SERVERPORT=51820
      - PEERS=5
      - PEERDNS=auto
      - INTERNAL_SUBNET=192.168.1.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - /home/pi/wireguard/config:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    restart: unless-stopped

## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support the app dev(s) visit:,
WireGuard: https://www.wireguard.com/donations/,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    1000,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
Uname info: Linux 650fd0e7e056 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l armv7l armv7l GNU/Linux,
Error: Unknown device type.,
**** The wireguard module is not active, will attempt kernel header install and module compilation. ****,
**** Attempting kernel header install ****,
Get:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease [242 kB],
Get:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease [88.7 kB],
Get:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease [74.6 kB],
Get:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease [88.7 kB],
Get:5 http://ports.ubuntu.com/ubuntu-ports bionic/main armhf Packages [1,277 kB],
Get:6 http://ports.ubuntu.com/ubuntu-ports bionic/universe armhf Packages [11.0 MB],
Get:7 http://ports.ubuntu.com/ubuntu-ports bionic/multiverse armhf Packages [157 kB],
Get:8 http://ports.ubuntu.com/ubuntu-ports bionic/restricted armhf Packages [12.5 kB],
Get:9 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main armhf Packages [1,326 kB],
Get:10 http://ports.ubuntu.com/ubuntu-ports bionic-updates/restricted armhf Packages [14.9 kB],
Get:11 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe armhf Packages [1,759 kB],
Get:12 http://ports.ubuntu.com/ubuntu-ports bionic-updates/multiverse armhf Packages [7,265 B],
Get:13 http://ports.ubuntu.com/ubuntu-ports bionic-backports/universe armhf Packages [11.0 kB],
Get:14 http://ports.ubuntu.com/ubuntu-ports bionic-backports/main armhf Packages [11.2 kB],
Get:15 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe armhf Packages [1,088 kB],
Get:16 http://ports.ubuntu.com/ubuntu-ports bionic-security/multiverse armhf Packages [2,424 B],
Get:17 http://ports.ubuntu.com/ubuntu-ports bionic-security/main armhf Packages [954 kB],
Get:18 http://ports.ubuntu.com/ubuntu-ports bionic-security/restricted armhf Packages [8,098 B],
Fetched 18.1 MB in 20s (883 kB/s),
Reading package lists...,
**** Raspbian kernel naming convention detected, attempting to install raspbian kernel headers ****,
Warning: apt-key output should not be parsed (stdout is not a terminal),
OK,
Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.8 kB],
Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic InRelease,
Hit:3 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease,
Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease,
Hit:5 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease,
Get:6 http://archive.raspberrypi.org/debian buster/main Sources [99.4 kB],
Get:7 http://archive.raspberrypi.org/debian buster/main armhf Packages [351 kB],
Fetched 484 kB in 3s (172 kB/s),
Reading package lists...,
Reading package lists...,
Building dependency tree...,
Reading state information...,
The following NEW packages will be installed:,
  raspberrypi-kernel-headers,
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.,
Need to get 26.3 MB of archives.,
After this operation, 171 MB of additional disk space will be used.,
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20210108-1 [26.3 MB],
Fetched 26.3 MB in 40s (661 kB/s),
Selecting previously unselected package raspberrypi-kernel-headers.
,
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 14046 files and directories currently installed.)
,
Preparing to unpack .../raspberrypi-kernel-headers_1.20210108-1_armhf.deb ...
,
Unpacking raspberrypi-kernel-headers (1.20210108-1) ...
,
Setting up raspberrypi-kernel-headers (1.20210108-1) ...
,
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.4.83+
,
 * dkms: running auto installation service for kernel 5.4.83+        
[ OK ]
,
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.4.83-v7+
,
 * dkms: running auto installation service for kernel 5.4.83-v7+        
[ OK ]
,
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.4.83-v7l+
,
 * dkms: running auto installation service for kernel 5.4.83-v7l+        
[ OK ]
,
run-parts: executing /etc/kernel/header_postinst.d/dkms 5.4.83-v8+
,
 * dkms: running auto installation service for kernel 5.4.83-v8+        
[ OK ]
,
**** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ****,

**Comment by aptalca** [comment]
Update your pi and reboot. Your kernel is older than the headers provided by the repo

**Comment by thardbarger** [comment]
Same but with newer kernel.
raspberrypi-kernel-headers is already the newest version (1.20210108-1).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
**** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ****

**Comment by aptalca** [comment]
What am I looking at?

**Comment by thardbarger** [comment]
Apologies for being vague. That was from the Docker container logs for wireguard. Below is my kernel info and further entries in the log. Thanks!

-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Uname info: Linux a221eb831789 5.10.9-v7l+ #1396 SMP Thu Jan 21 15:57:42 GMT 2021 armv7l armv7l armv7l GNU/Linux
RTNETLINK answers: Operation not permitted
**** The wireguard module is not active, will attempt kernel header install and module compilation. ****
**** Attempting kernel header install ****
Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Get:2 http://archive.raspberrypi.org/debian buster InRelease [32.8 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease [88.7 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease [74.6 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease [88.7 kB]
Get:6 http://archive.raspberrypi.org/debian buster/main Sources [100 kB]
Get:7 http://archive.raspberrypi.org/debian buster/main armhf Packages [353 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe armhf Packages [1,769 kB]
Fetched 2,507 kB in 7s (337 kB/s)
Reading package lists...
**** Raspbian kernel naming convention detected, attempting to install raspbian kernel headers ****
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Hit:5 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
raspberrypi-kernel-headers is already the newest version (1.20210108-1).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
**** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ****

**Comment by aptalca** [comment]
You just needed to do apt update & upgrade and reboot
Whatever you did, you broke it further.

Before, your host was on kernel 5.4.79, but needed to be on 5.4.83, which is what's in the buster repo. Now it's on 5.10.9, which is not the buster stable. You probably enabled beta kernels or something.

**Comment by thardbarger** [comment]
Thanks @aptalca. I downgraded to the stable version which resolved that issue. Am now getting a "Warning: modules_install: missing 'System.map' file. Skipping depmod" error. I see there is some discussion about this on issue #47 that I'll read through. Appreciate you help!

**Comment by aptalca** [comment]
Make sure you're using the latest image. It initially gives you a warning about it but then fixes it. I just tried on my pi4 with buster on kernel 5.4.83 and it worked fine

**Comment by enigma158an201** [comment]
hi,
i have a quite similar issue on debian buster:
$ uname -a
Linux ServeurDebian 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

here is a log file obtained without -d switch
http://paste.debian.net/1185595/

it seems problems came from line 50, 52 et 53:
missing System.map 
and 
WARNING: could not open //lib/modules/4.19.0-14-amd64/

PS: sorry if needed opening new issue

**Comment by aptalca** [comment]
Your mappings may not be correct. Open a new issue and fill out the issue template
