### ISSUE TITLE
Changing INTERNAL_SUBNET in server mode doesn't regenerate CLIENT_IP/Address peers config

### ISSUE THREAD

**Issue by Baryczka** [linuxserver/docker-wireguard#95]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
 Changing INTERNAL_SUBNET in docker-compose.yml should change Address in .conf files

## Current Behavior

Changing INTERNAL_SUBNET in docker-compose.yml server mode doesn't regenerate Address in peers .conf files
## Steps to Reproduce

1. Run docker-compose up with INTERNAL_SUBNET=10.0.0.0 to generate peers and client configs and stop docker-compose
2. Change INTERNAL_SUBNET=10.2.2.2 and run docker-compose up
3. Client configs are updated for _AllowedIPs_ and _DNS_ but not **Address**

**Notes**:
* Having wide subnet can be used to workaround this problem, or just edit the peers configuration files.
* "Problem" lays in https://github.com/linuxserver/docker-wireguard/blob/master/root/etc/cont-init.d/30-config#L187
* Other smaller issue: _ListenPort_ for peers is not necessary when peers configs are generated in Server mode

## Environment
**OS:** Ubuntu 20.04 LTS
**CPU architecture:** x86_64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)
Edit docker-compose.yml and docker-compose up

## Docker logs
```
wireguard    | **** External server port is set to 51820. Make sure that port is properly forwarded to port 51820 inside this container ****
wireguard    | **** Internal subnet is set to 10.2.7.0 ****
wireguard    | **** AllowedIPs for peers 10.2.7.0/24 ****
wireguard    | **** Peer DNS servers will be set to 10.2.7.1 ****
wireguard    | **** Server mode is selected ****
wireguard    | **** Server related environment variables changed, regenerating 1 server and user1,user2,user3 peer/client confs ****
...
wireguard    | [#] ip link add wg0 type wireguard
wireguard    | [#] wg setconf wg0 /dev/fd/63
wireguard    | [#] ip -4 address add 10.2.7.1 dev wg0
wireguard    | [#] ip link set mtu 1420 up dev wg0
wireguard    | [#] ip -4 route add 10.2.5.3/32 dev wg0
wireguard    | [#] ip -4 route add 10.2.5.2/32 dev wg0
wireguard    | [#] ip -4 route add 10.2.3.4/32 dev wg0
```

**Comment by aptalca** [comment]
Yeah, it seems that was introduced when we added the `named` peers functionality. We want to preserve the existing IPs for named peers, but instead of preserving the full IP, we should preserve the last digits only and update the subnet if necessary.

**Comment by aptalca** [comment]
@Baryczka can you test this image and let us know if it works?
`lspipepr/wireguard:v1.0.20200827-pkg-8e9a9884-pr-96`

Just replace `ghcr.io/linuxserver/wireguard` with the above and recreate the image

Thanks

**Comment by Baryczka** [comment]
Thanks for very fast PR and sorry for late response. So far I tested it changing subnet and all peers were regenerated correctly including final wg0.conf

Side question, could you quickly explain what does sed with pipes instead of slashes is doing?
`s|${ORIG_INTERFACE}|${INTERFACE}|`
PS. I found funny usage of DUDE word as eof in files with cat generations ^^

**Comment by Roxedus** [comment]
They are not pipes, they act as separators, the same way slashes do. It could also have been @ instead

**Comment by Baryczka** [comment]
> They are not pipes, they act as separators, the same way slashes do. It could also have been @ instead

Thanks, TIL and even found some old article with confirmation: https://backreference.org/2010/02/20/using-different-delimiters-in-sed/
