### ISSUE TITLE
167035 user

### ISSUE THREAD

**Issue by Bammede** [linuxserver/docker-wireguard#97]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Able to edit wg0.conf by nano

## Current Behavior

I cannot open files under wireguard folder, because folder and its files have different (weird) user permission.

After checking with ls -ll . I figured out the permission is set to "167035" user. I have no such user with this ID or name in the system.

I use docker rootless installation.

Thought PUID and PGUID env. will solve the problem, but nothing changed.

I use wireguard service alongside with other services, apps in docker-compose and they are ok.

## Steps to Reproduce

1. docker rootless installation
2. docker compose 2.4
3.
4.

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:**

**Comment by aptalca** [comment]
Our images aren't designed to work with rootless docker

**Comment by Bammede** [comment]
Shame.
